/**
 * Example: create-pnft
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { generateKeyPairSigner } from '@solana/kit';\nimport { createProgrammableNft } from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, and sendAndConfirmInstructions are set up\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet",
  "main": "// Create and mint a Programmable NFT in one step\nconst [createIx, mintIx] = await createProgrammableNft({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My Programmable NFT',\n  uri: 'https://example.com/my-programmable-nft.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  tokenOwner: authority.address,\n  // Optional: add to collection (must verify separately)\n  // collection: { key: collectionMint.address, verified: false },\n});\n\n// Send both instructions in one transaction\nawait sendAndConfirm({\n  instructions: [createIx, mintIx],\n  payer: authority,\n});",
  "output": "console.log('Programmable NFT created:', mint.address);",
  "full": "// [IMPORTS]\nimport { generateKeyPairSigner } from '@solana/kit';\nimport { createProgrammableNft } from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, and sendAndConfirmInstructions are set up\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet\n// [/SETUP]\n\n// [MAIN]\n// Create and mint a Programmable NFT in one step\nconst [createIx, mintIx] = await createProgrammableNft({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My Programmable NFT',\n  uri: 'https://example.com/my-programmable-nft.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  tokenOwner: authority.address,\n  // Optional: add to collection (must verify separately)\n  // collection: { key: collectionMint.address, verified: false },\n});\n\n// Send both instructions in one transaction\nawait sendAndConfirm({\n  instructions: [createIx, mintIx],\n  payer: authority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Programmable NFT created:', mint.address);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { percentAmount, generateSigner } from '@metaplex-foundation/umi';\nimport { createProgrammableNft } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mint = generateSigner(umi);",
  "main": "// Create and mint a Programmable NFT in one step\nawait createProgrammableNft(umi, {\n  mint,\n  name: 'My Programmable NFT',\n  uri: 'https://example.com/my-programmable-nft.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  // Optional: add to collection (must verify separately)\n  // collection: some({ key: collectionMint.publicKey, verified: false }),\n}).sendAndConfirm(umi);",
  "output": "console.log('Programmable NFT created:', mint.publicKey);",
  "full": "// [IMPORTS]\nimport { percentAmount, generateSigner } from '@metaplex-foundation/umi';\nimport { createProgrammableNft } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mint = generateSigner(umi);\n// [/SETUP]\n\n// [MAIN]\n// Create and mint a Programmable NFT in one step\nawait createProgrammableNft(umi, {\n  mint,\n  name: 'My Programmable NFT',\n  uri: 'https://example.com/my-programmable-nft.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  // Optional: add to collection (must verify separately)\n  // collection: some({ key: collectionMint.publicKey, verified: false }),\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Programmable NFT created:', mint.publicKey);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "create-pnft",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
