/**
 * Example: read_agent_das_search
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('<DAS_ENDPOINT>').use(dasApi())",
  "main": "const results = await umi.rpc.searchAssets({\n  isAgent: true,\n  interface: 'MplCoreAsset',\n  limit: 100,\n})\n\nfor (const agent of results.items) {\n  console.log(agent.id, agent.asset_signer, agent.agent_token ?? 'no token')\n}",
  "output": "// 1RUC5FMQherGNoLF9wDBxa1oznbq1mTieWLZ8gU8S31 DwgDrVVwcuXGU2MjHcZEcNtG2cGF6cLXCS35gPiUsU6p no token",
  "full": "// [IMPORTS]\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<DAS_ENDPOINT>').use(dasApi())\n// [/SETUP]\n\n// [MAIN]\nconst results = await umi.rpc.searchAssets({\n  isAgent: true,\n  interface: 'MplCoreAsset',\n  limit: 100,\n})\n\nfor (const agent of results.items) {\n  console.log(agent.id, agent.asset_signer, agent.agent_token ?? 'no token')\n}\n// [/MAIN]\n\n// [OUTPUT]\n// 1RUC5FMQherGNoLF9wDBxa1oznbq1mTieWLZ8gU8S31 DwgDrVVwcuXGU2MjHcZEcNtG2cGF6cLXCS35gPiUsU6p no token\n// [/OUTPUT]\n"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "curl -X POST <DAS_ENDPOINT> \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"jsonrpc\": \"2.0\",\n    \"id\": 1,\n    \"method\": \"searchAssets\",\n    \"params\": {\n      \"isAgent\": true,\n      \"interface\": \"MplCoreAsset\",\n      \"limit\": 100\n    }\n  }'\n"
}

export const metadata = {
  title: "read_agent_das_search",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
