/**
 * Example: claim_distribution
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  distribute,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// The payer may be the recipient or a third-party distributor, depending on\n// the distribution's allowedDistributor setting.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst recipients = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100_000n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 250_000n },\n]\nconst recipientIndex = 0\nconst { proofs } = prepareDistribution(recipients)",
  "main": "await distribute(umi, {\n  distribution,\n  mint,\n  recipient: recipients[recipientIndex].address,\n  amount: recipients[recipientIndex].amount,\n  proof: proofs[recipientIndex],\n  nonce: 0,\n}).sendAndConfirm(umi)",
  "output": "// The recipient ATA receives 100000 base units and a claim receipt is created.",
  "full": "// [IMPORTS]\nimport {\n  distribute,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// The payer may be the recipient or a third-party distributor, depending on\n// the distribution's allowedDistributor setting.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst recipients = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100_000n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 250_000n },\n]\nconst recipientIndex = 0\nconst { proofs } = prepareDistribution(recipients)\n// [/SETUP]\n\n// [MAIN]\nawait distribute(umi, {\n  distribution,\n  mint,\n  recipient: recipients[recipientIndex].address,\n  amount: recipients[recipientIndex].amount,\n  proof: proofs[recipientIndex],\n  nonce: 0,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// The recipient ATA receives 100000 base units and a claim receipt is created.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "claim_distribution",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
