/**
 * Example: initialize_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  findGenesisAccountV2Pda,\n  genesis,\n  initializeV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { generateSigner, keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));",
  "main": "const baseMint = generateSigner(umi)\nconst TOTAL_SUPPLY = 1_000_000_000_000_000n // 1 million tokens (9 decimals)\n\n// Store this account address for later or recreate it when needed.\nconst [genesisAccount] = findGenesisAccountV2Pda(umi, {\n  baseMint: baseMint.publicKey,\n  genesisIndex: 0,\n})\n\nawait initializeV2(umi, {\n  baseMint,\n  fundingMode: 0,\n  totalSupplyBaseToken: TOTAL_SUPPLY,\n  name: 'My Token',\n  symbol: 'MTK',\n  uri: 'https://example.com/metadata.json',\n}).sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  findGenesisAccountV2Pda,\n  genesis,\n  initializeV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { generateSigner, keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n// [/SETUP]\n\n// [MAIN]\nconst baseMint = generateSigner(umi)\nconst TOTAL_SUPPLY = 1_000_000_000_000_000n // 1 million tokens (9 decimals)\n\n// Store this account address for later or recreate it when needed.\nconst [genesisAccount] = findGenesisAccountV2Pda(umi, {\n  baseMint: baseMint.publicKey,\n  genesisIndex: 0,\n})\n\nawait initializeV2(umi, {\n  baseMint,\n  fundingMode: 0,\n  totalSupplyBaseToken: TOTAL_SUPPLY,\n  name: 'My Token',\n  symbol: 'MTK',\n  uri: 'https://example.com/metadata.json',\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "initialize_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
