/**
 * Example: fetch-by-metadata
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport { fetchDigitalAssetByMetadata } from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc is set up\n// See getting-started for full setup\n\nconst metadataAddress = address('Gz3vYbpsB2agTsAwedtvtTkQ1CG9Cpo6eTq59rrEGCKF');",
  "main": "// Fetch a digital asset by its metadata address\nconst asset = await fetchDigitalAssetByMetadata(rpc, metadataAddress);",
  "output": "console.log('Asset:', asset.address);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport { fetchDigitalAssetByMetadata } from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc is set up\n// See getting-started for full setup\n\nconst metadataAddress = address('Gz3vYbpsB2agTsAwedtvtTkQ1CG9Cpo6eTq59rrEGCKF');\n// [/SETUP]\n\n// [MAIN]\n// Fetch a digital asset by its metadata address\nconst asset = await fetchDigitalAssetByMetadata(rpc, metadataAddress);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset:', asset.address);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAssetByMetadata } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst metadataAddress = publicKey('Gz3vYbpsB2agTsAwedtvtTkQ1CG9Cpo6eTq59rrEGCKF');",
  "main": "// Fetch a digital asset by its metadata address\nconst asset = await fetchDigitalAssetByMetadata(umi, metadataAddress);",
  "output": "console.log('Asset:', asset.publicKey);\nconsole.log('Metadata:', asset.metadata.publicKey);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAssetByMetadata } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst metadataAddress = publicKey('Gz3vYbpsB2agTsAwedtvtTkQ1CG9Cpo6eTq59rrEGCKF');\n// [/SETUP]\n\n// [MAIN]\n// Fetch a digital asset by its metadata address\nconst asset = await fetchDigitalAssetByMetadata(umi, metadataAddress);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset:', asset.publicKey);\nconsole.log('Metadata:', asset.metadata.publicKey);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-by-metadata",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
