/**
 * Example: verify-creator
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getVerifyCreatorV1Instruction,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and creator (signer) are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address",
  "main": "// Find the metadata PDA\nconst [metadata] = await findMetadataPda({ mint: mintAddress });\n\n// Verify the creator on the NFT\nconst verifyIx = getVerifyCreatorV1Instruction({\n  metadata,\n  authority: creator,\n});\n\nawait sendAndConfirm({\n  instructions: [verifyIx],\n  payer: creator,\n});",
  "output": "console.log('Creator verified on NFT');",
  "full": "// [IMPORTS]\nimport {\n  getVerifyCreatorV1Instruction,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and creator (signer) are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address\n// [/SETUP]\n\n// [MAIN]\n// Find the metadata PDA\nconst [metadata] = await findMetadataPda({ mint: mintAddress });\n\n// Verify the creator on the NFT\nconst verifyIx = getVerifyCreatorV1Instruction({\n  metadata,\n  authority: creator,\n});\n\nawait sendAndConfirm({\n  instructions: [verifyIx],\n  payer: creator,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Creator verified on NFT');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { verifyCreatorV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, metadata, and creator are set up",
  "main": "await verifyCreatorV1(umi, {\n  metadata,\n  authority: creator,\n}).sendAndConfirm(umi);",
  "output": "console.log('Creator verified');",
  "full": "// [IMPORTS]\nimport { verifyCreatorV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, metadata, and creator are set up\n// [/SETUP]\n\n// [MAIN]\nawait verifyCreatorV1(umi, {\n  metadata,\n  authority: creator,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Creator verified');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "verify-creator",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
