/**
 * Example: fetch-all-with-token-by-mint
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { fetchAllDigitalAssetWithTokenByMint } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mint = publicKey('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');",
  "main": "// Fetch all token accounts for a given mint\nconst assets = await fetchAllDigitalAssetWithTokenByMint(umi, mint);",
  "output": "console.log('Found', assets.length, 'token accounts');\nassets.forEach((asset) => {\n  console.log('Owner:', asset.token.owner);\n  console.log('Amount:', asset.token.amount);\n});",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { fetchAllDigitalAssetWithTokenByMint } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mint = publicKey('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');\n// [/SETUP]\n\n// [MAIN]\n// Fetch all token accounts for a given mint\nconst assets = await fetchAllDigitalAssetWithTokenByMint(umi, mint);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Found', assets.length, 'token accounts');\nassets.forEach((asset) => {\n  console.log('Owner:', asset.token.owner);\n  console.log('Amount:', asset.token.amount);\n});\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-all-with-token-by-mint",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
