/**
 * Example: trigger_claim_schedule_conditions_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { genesis, triggerConditionsV2 } from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst baseMint = publicKey('YOUR_PROJECT_TOKEN_MINT')\nconst vestingBucket = publicKey('CLAIM_SCHEDULE_BUCKET_PDA')\nconst referenceBucket = publicKey('REFERENCE_BUCKET_PDA')",
  "main": "await triggerConditionsV2(umi, {\n  genesisAccount,\n  bucket: vestingBucket,\n  baseMint,\n})\n  .addRemainingAccounts([\n    { pubkey: referenceBucket, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)",
  "output": "// Eligible TimeRelative conditions on the vesting bucket are now triggered.",
  "full": "// [IMPORTS]\nimport { genesis, triggerConditionsV2 } from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst baseMint = publicKey('YOUR_PROJECT_TOKEN_MINT')\nconst vestingBucket = publicKey('CLAIM_SCHEDULE_BUCKET_PDA')\nconst referenceBucket = publicKey('REFERENCE_BUCKET_PDA')\n// [/SETUP]\n\n// [MAIN]\nawait triggerConditionsV2(umi, {\n  genesisAccount,\n  bucket: vestingBucket,\n  baseMint,\n})\n  .addRemainingAccounts([\n    { pubkey: referenceBucket, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// Eligible TimeRelative conditions on the vesting bucket are now triggered.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "trigger_claim_schedule_conditions_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
