/**
 * Example: swap_quote_sell
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n} from '@metaplex-foundation/genesis';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);",
  "main": "const TOKENS_IN = 500_000_000_000n; // 500 tokens (9 decimals)\n\nconst sellQuote = getSwapResult(bucket, TOKENS_IN, 'sell');\n\nconsole.log('Tokens input: ', sellQuote.amountIn.toString());\nconsole.log('Total fee:    ', sellQuote.fee.toString(), 'lamports');\nconsole.log('SOL out:      ', sellQuote.amountOut.toString(), 'lamports');",
  "output": "// Tokens input:  500000000000\n// Total fee:     <fee in lamports>\n// SOL out:       <calculated SOL amount>",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n} from '@metaplex-foundation/genesis';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);\n// [/SETUP]\n\n// [MAIN]\nconst TOKENS_IN = 500_000_000_000n; // 500 tokens (9 decimals)\n\nconst sellQuote = getSwapResult(bucket, TOKENS_IN, 'sell');\n\nconsole.log('Tokens input: ', sellQuote.amountIn.toString());\nconsole.log('Total fee:    ', sellQuote.fee.toString(), 'lamports');\nconsole.log('SOL out:      ', sellQuote.amountOut.toString(), 'lamports');\n// [/MAIN]\n\n// [OUTPUT]\n// Tokens input:  500000000000\n// Total fee:     <fee in lamports>\n// SOL out:       <calculated SOL amount>\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Get a sell quote without executing a swap (--info flag)\nmplx genesis swap <GENESIS_ACCOUNT> --info --sellAmount 500000000000\n"
}

export const metadata = {
  title: "swap_quote_sell",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
