/**
 * Example: fetch-all-by-update-authority
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { fetchAllDigitalAssetByUpdateAuthority } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst updateAuthority = publicKey('updateAuthorityAddress...');",
  "main": "// Fetch all digital assets by update authority\nconst assets = await fetchAllDigitalAssetByUpdateAuthority(umi, updateAuthority);",
  "output": "console.log('Found', assets.length, 'assets');\nassets.forEach((asset) => {\n  console.log('Name:', asset.metadata.name);\n  console.log('Mint:', asset.publicKey);\n});",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { fetchAllDigitalAssetByUpdateAuthority } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst updateAuthority = publicKey('updateAuthorityAddress...');\n// [/SETUP]\n\n// [MAIN]\n// Fetch all digital assets by update authority\nconst assets = await fetchAllDigitalAssetByUpdateAuthority(umi, updateAuthority);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Found', assets.length, 'assets');\nassets.forEach((asset) => {\n  console.log('Name:', asset.metadata.name);\n  console.log('Mint:', asset.publicKey);\n});\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-all-by-update-authority",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
