/**
 * Example: delegate-authority-item-revoke
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getRevokeAuthorityItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, updateAuthority, and authorityItemDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address",
  "main": "// Revoke an Authority Item delegate\n// Note: Either the update authority or the delegate itself can revoke\nconst revokeIx = await getRevokeAuthorityItemV1InstructionAsync({\n  mint: mintAddress,\n  delegate: authorityItemDelegate,\n  authority: updateAuthority, // Or pass the delegate to self-revoke\n  payer: updateAuthority,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [revokeIx],\n  payer: updateAuthority,\n});",
  "output": "console.log('Authority Item delegate revoked');",
  "full": "// [IMPORTS]\nimport {\n  getRevokeAuthorityItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, updateAuthority, and authorityItemDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address\n// [/SETUP]\n\n// [MAIN]\n// Revoke an Authority Item delegate\n// Note: Either the update authority or the delegate itself can revoke\nconst revokeIx = await getRevokeAuthorityItemV1InstructionAsync({\n  mint: mintAddress,\n  delegate: authorityItemDelegate,\n  authority: updateAuthority, // Or pass the delegate to self-revoke\n  payer: updateAuthority,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [revokeIx],\n  payer: updateAuthority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Authority Item delegate revoked');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { revokeAuthorityItemV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, mint, updateAuthority, and authorityItemDelegate are set up",
  "main": "await revokeAuthorityItemV1(umi, {\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke.\n  delegate: authorityItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Authority Item delegate revoked');",
  "full": "// [IMPORTS]\nimport { revokeAuthorityItemV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, mint, updateAuthority, and authorityItemDelegate are set up\n// [/SETUP]\n\n// [MAIN]\nawait revokeAuthorityItemV1(umi, {\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke.\n  delegate: authorityItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Authority Item delegate revoked');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-authority-item-revoke",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
