/**
 * Example: fund_distribution
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  deposit,\n  mplDistro,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// The Umi identity must be the current distribution authority.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst totalAmount = 350_000n",
  "main": "await deposit(umi, {\n  distribution,\n  mint,\n  amount: totalAmount,\n}).sendAndConfirm(umi)",
  "output": "// The distribution ATA contains 350000 base units.",
  "full": "// [IMPORTS]\nimport {\n  deposit,\n  mplDistro,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// The Umi identity must be the current distribution authority.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst totalAmount = 350_000n\n// [/SETUP]\n\n// [MAIN]\nawait deposit(umi, {\n  distribution,\n  mint,\n  amount: totalAmount,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// The distribution ATA contains 350000 base units.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fund_distribution",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
