/**
 * Example: Mint and Submit an Agent
 *
 * Create an onchain AI agent in one call using mintAndSubmitAgent and the Metaplex API.
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mintAndSubmitAgent } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "const result = await mintAndSubmitAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  name: 'My AI Agent',\n  uri: 'https://example.com/agent-metadata.json',  // Core asset NFT metadata URI\n  agentMetadata: {                                  // Stored off-chain by the Metaplex API\n    type: 'agent',\n    name: 'My AI Agent',\n    description: 'An autonomous trading agent',\n    services: [\n      { name: 'trading', endpoint: 'https://myagent.ai/trade' },\n    ],\n    registrations: [],\n    supportedTrust: [],\n  },\n})\n\nconsole.log('Asset address:', result.assetAddress)\nconsole.log('Transaction signature:', result.signature)",
  "output": "// Asset address: <base58 address>\n// Transaction signature: <base58 signature>",
  "full": "// [IMPORTS]\nimport { mintAndSubmitAgent } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\nconst result = await mintAndSubmitAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  name: 'My AI Agent',\n  uri: 'https://example.com/agent-metadata.json',  // Core asset NFT metadata URI\n  agentMetadata: {                                  // Stored off-chain by the Metaplex API\n    type: 'agent',\n    name: 'My AI Agent',\n    description: 'An autonomous trading agent',\n    services: [\n      { name: 'trading', endpoint: 'https://myagent.ai/trade' },\n    ],\n    registrations: [],\n    supportedTrust: [],\n  },\n})\n\nconsole.log('Asset address:', result.assetAddress)\nconsole.log('Transaction signature:', result.signature)\n// [/MAIN]\n\n// [OUTPUT]\n// Asset address: <base58 address>\n// Transaction signature: <base58 signature>\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Mint and Submit an Agent",
  description: "Create an onchain AI agent in one call using mintAndSubmitAgent and the Metaplex API.",
  tags: ['agents', 'mint', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
