/**
 * Example: delegate-transfer-transfer
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and transferDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address\nconst currentOwner = 'currentOwnerAddress...';\nconst newOwner = 'newOwnerAddress...';",
  "main": "// Transfer as Transfer delegate (pNFT only)\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  authority: transferDelegate,\n  payer: transferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [transferIx],\n  payer: transferDelegate,\n});",
  "output": "console.log('pNFT transferred by Transfer delegate');",
  "full": "// [IMPORTS]\nimport {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and transferDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address\nconst currentOwner = 'currentOwnerAddress...';\nconst newOwner = 'newOwnerAddress...';\n// [/SETUP]\n\n// [MAIN]\n// Transfer as Transfer delegate (pNFT only)\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  authority: transferDelegate,\n  payer: transferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [transferIx],\n  payer: transferDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred by Transfer delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { transferV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, mint, transferDelegate, currentOwner, and newOwner are set up",
  "main": "await transferV1(umi, {\n  mint,\n  authority: transferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('pNFT transferred by Transfer delegate');",
  "full": "// [IMPORTS]\nimport { transferV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, mint, transferDelegate, currentOwner, and newOwner are set up\n// [/SETUP]\n\n// [MAIN]\nawait transferV1(umi, {\n  mint,\n  authority: transferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred by Transfer delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-transfer-transfer",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
