/**
 * Example: Create a Collection
 *
 * Basic example of creating a Collection with Core
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { createCollection } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())",
  "main": "// Generate a new keypair for the collection\nconst collectionSigner = generateSigner(umi)\n\n// Create a new Collection\nawait createCollection(umi, {\n  collection: collectionSigner,\n  name: 'My Collection',\n  uri: 'https://example.com/collection.json',\n}).sendAndConfirm(umi)",
  "output": "console.log('Collection created:', collectionSigner.publicKey)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { createCollection } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n// [/SETUP]\n\n// [MAIN]\n// Generate a new keypair for the collection\nconst collectionSigner = generateSigner(umi)\n\n// Create a new Collection\nawait createCollection(umi, {\n  collection: collectionSigner,\n  name: 'My Collection',\n  uri: 'https://example.com/collection.json',\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection created:', collectionSigner.publicKey)\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::instructions::CreateCollectionV1Builder;\nuse solana_sdk::signer::Signer;",
  "setup": "",
  "main": "// Create a new Collection\nlet create_collection_ix = CreateCollectionV1Builder::new()\n    .collection(collection.pubkey())\n    .payer(payer.pubkey())\n    .name(\"My Collection\".to_string())\n    .uri(\"https://example.com/collection.json\".to_string())\n    .instruction();",
  "output": "println!(\"Collection instruction created\");",
  "full": "// [IMPORTS]\nuse mpl_core::instructions::CreateCollectionV1Builder;\nuse solana_sdk::signer::Signer;\n// [/IMPORTS]\n\n// [MAIN]\n// Create a new Collection\nlet create_collection_ix = CreateCollectionV1Builder::new()\n    .collection(collection.pubkey())\n    .payer(payer.pubkey())\n    .name(\"My Collection\".to_string())\n    .uri(\"https://example.com/collection.json\".to_string())\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Collection instruction created\");\n// [/OUTPUT]\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\nuse mpl_core::instructions::CreateCollectionV1CpiBuilder;",
  "setup": "",
  "main": "// Create a new Collection via CPI\nCreateCollectionV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .collection(&ctx.accounts.collection)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"My Collection\".to_string())\n    .uri(\"https://example.com/collection.json\".to_string())\n    .invoke()?;",
  "output": "msg!(\"Collection created: {}\", ctx.accounts.collection.key());",
  "full": "// [IMPORTS]\nuse anchor_lang::prelude::*;\nuse mpl_core::instructions::CreateCollectionV1CpiBuilder;\n// [/IMPORTS]\n\n// [MAIN]\n// Create a new Collection via CPI\nCreateCollectionV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .collection(&ctx.accounts.collection)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"My Collection\".to_string())\n    .uri(\"https://example.com/collection.json\".to_string())\n    .invoke()?;\n// [/MAIN]\n\n// [OUTPUT]\nmsg!(\"Collection created: {}\", ctx.accounts.collection.key());\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Create a Collection",
  description: "Basic example of creating a Collection with Core",
  tags: ['core', 'collection', 'create', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
