/**
 * Example: delegate-data-approve
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getDelegateDataV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst dataDelegate = address('delegateAddress...');",
  "main": "const delegateIx = await getDelegateDataV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: dataDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([delegateIx], [updateAuthority]);",
  "output": "console.log('Data delegate approved');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getDelegateDataV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst dataDelegate = address('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst delegateIx = await getDelegateDataV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: dataDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([delegateIx], [updateAuthority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Data delegate approved');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateDataV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst dataDelegate = publicKey('delegateAddress...');",
  "main": "await delegateDataV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: dataDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Data delegate approved');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateDataV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst dataDelegate = publicKey('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait delegateDataV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: dataDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Data delegate approved');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-data-approve",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
