/**
 * Example: read_agent_fetch_from_seeds
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  fetchAgentIdentityV1FromSeeds,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(mplAgentIdentity())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')",
  "main": "// Throws if the identity account does not exist — use safeFetchAgentIdentityV1 for unregistered assets.\nconst identity = await fetchAgentIdentityV1FromSeeds(umi, {\n  asset: assetPublicKey,\n})\n\nconsole.log('Identity:', identity)",
  "output": "// Identity: { ... }",
  "full": "// [IMPORTS]\nimport {\n  fetchAgentIdentityV1FromSeeds,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(mplAgentIdentity())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\n// Throws if the identity account does not exist — use safeFetchAgentIdentityV1 for unregistered assets.\nconst identity = await fetchAgentIdentityV1FromSeeds(umi, {\n  asset: assetPublicKey,\n})\n\nconsole.log('Identity:', identity)\n// [/MAIN]\n\n// [OUTPUT]\n// Identity: { ... }\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "read_agent_fetch_from_seeds",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
