/**
 * Example: Update away from inherited royalties
 *
 * Switch a cNFT from inherited seller fees to an explicit rate before removing it from its collection.
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  getAssetWithProof,\n  updateMetadataV2,\n  UpdateArgsArgs,\n  mplBubblegum,\n} from '@metaplex-foundation/mpl-bubblegum'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { keypairIdentity, publicKey, some } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { readFileSync } from 'fs'",
  "setup": "// getAssetWithProof calls getAsset and getAssetProof, so this needs a\n// DAS-capable RPC. The public Solana endpoints do not serve DAS methods.\nconst umi = createUmi('YOUR_DAS_ENABLED_RPC_URL')\n  .use(mplBubblegum())\n  .use(dasApi())\n\n// The leaf owner or an authorised delegate must sign the update.\nconst keypair = umi.eddsa.createKeypairFromSecretKey(\n  new Uint8Array(JSON.parse(readFileSync('./keypair.json', 'utf8')))\n)\numi.use(keypairIdentity(keypair))\n\nconst assetId = publicKey('YOUR_ASSET_ID')\nconst collectionPublicKey = publicKey('YOUR_COLLECTION_ADDRESS')",
  "main": "const assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Switch from inherited royalties to an explicit seller fee before removing\n// the cNFT from its collection.\nconst updateArgs: UpdateArgsArgs = {\n  sellerFeeBasisPoints: some(550), // explicit 5.5%\n}\n\n// Spread includes currentMetadata (leaf-canonical). Do not pass metadata here.\nawait updateMetadataV2(umi, {\n  ...assetWithProof,\n  updateArgs,\n  coreCollection: collectionPublicKey,\n}).sendAndConfirm(umi)",
  "output": "// Leaf seller fee updated from inherit sentinel (65535) to 550 basis points",
  "full": "// [IMPORTS]\nimport {\n  getAssetWithProof,\n  updateMetadataV2,\n  UpdateArgsArgs,\n  mplBubblegum,\n} from '@metaplex-foundation/mpl-bubblegum'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { keypairIdentity, publicKey, some } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { readFileSync } from 'fs'\n// [/IMPORTS]\n\n// [SETUP]\n// getAssetWithProof calls getAsset and getAssetProof, so this needs a\n// DAS-capable RPC. The public Solana endpoints do not serve DAS methods.\nconst umi = createUmi('YOUR_DAS_ENABLED_RPC_URL')\n  .use(mplBubblegum())\n  .use(dasApi())\n\n// The leaf owner or an authorised delegate must sign the update.\nconst keypair = umi.eddsa.createKeypairFromSecretKey(\n  new Uint8Array(JSON.parse(readFileSync('./keypair.json', 'utf8')))\n)\numi.use(keypairIdentity(keypair))\n\nconst assetId = publicKey('YOUR_ASSET_ID')\nconst collectionPublicKey = publicKey('YOUR_COLLECTION_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\nconst assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Switch from inherited royalties to an explicit seller fee before removing\n// the cNFT from its collection.\nconst updateArgs: UpdateArgsArgs = {\n  sellerFeeBasisPoints: some(550), // explicit 5.5%\n}\n\n// Spread includes currentMetadata (leaf-canonical). Do not pass metadata here.\nawait updateMetadataV2(umi, {\n  ...assetWithProof,\n  updateArgs,\n  coreCollection: collectionPublicKey,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// Leaf seller fee updated from inherit sentinel (65535) to 550 basis points\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Update away from inherited royalties",
  description: "Switch a cNFT from inherited seller fees to an explicit rate before removing it from its collection.",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
