/**
 * Example: search-assets-agents
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'",
  "setup": "const umi = createUmi('<ENDPOINT>').use(dasApi())",
  "main": "const agents = await das.searchAssets(umi, {\n  isAgent: true,\n  // agentToken: publicKey('<GenesisMint>'),\n  // assetSigner: publicKey('<AssetSignerPda>'),\n  skipDerivePlugins: true,\n})",
  "output": "// When indexed: agents[i].is_agent, .agent_token, .asset_signer\nconsole.log(agents)",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<ENDPOINT>').use(dasApi())\n// [/SETUP]\n\n// [MAIN]\nconst agents = await das.searchAssets(umi, {\n  isAgent: true,\n  // agentToken: publicKey('<GenesisMint>'),\n  // assetSigner: publicKey('<AssetSignerPda>'),\n  skipDerivePlugins: true,\n})\n// [/MAIN]\n\n// [OUTPUT]\n// When indexed: agents[i].is_agent, .agent_token, .asset_signer\nconsole.log(agents)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "search-assets-agents",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
