export const installationPackages = {
  umi: {
    name: 'umi',
    description: 'A client wrapper for Solana protocols by Metaplex',
    npm: '@metaplex-foundation/umi',
    crate: null,
    docs: '/umi',
  },
  umiDefaults: {
    name: 'umi',
    description: 'A client wrapper for Solana protocols by Metaplex',
    npm: '@metaplex-foundation/umi-bundle-defaults',
    crate: null,
    docs: '/umi',
  },
  tokenMetadata: {
    name: 'token-metadata',
    description: 'Token Metadata program by Metaplex',
    npm: '@metaplex-foundation/mpl-token-metadata',
    crate: 'mpl-token-metadata',
    docs: '/token-metadata',
  },
  core: {
    name: 'core',
    description: 'Newest Core Asset standard by Metaplex',
    npm: '@metaplex-foundation/mpl-core',
    crate: 'mpl-core',
    docs: '/core',
  },
  candyMachineTm: {
    name: 'candy-machine',
    description: 'A toolkit for React best practices.',
    npm: '@metaplex-foundation/mpl-candy-machine',
    crate: 'mpl-candy-machine',
    docs: '/candy-machine',
  },
  candyMachineCore: {
    name: 'candy-machine-core',
    description: 'A toolkit for React best practices.',
    npm: '@metaplex-foundation/mpl-core-candy-machine',
    crate: 'mpl-core-candy-machine-core',
    docs: '/candy-machine-core',
  },
  bubblegum: {
    name: 'bubblegum',
    description: 'Compressed Nft standard by Metaplex',
    npm: '@metaplex-foundation/mpl-bubblegum',
    crate: 'mpl-bubblegum',
    docs: '/bubblegum',
  },
  toolbox: {
    name: 'toolbox',
    description: 'A toolkit wrapped for Solana protocols by Metaplex',
    npm: '@metaplex-foundation/mpl-toolbox',
    crate: 'mpl-toolbox',
  },
  hydra: {
    name: 'hydra',
    description: 'A toolkit wrapped for Solana protocols by Metaplex',
    npm: '@metaplex-foundation/mpl-hydra',
    crate: 'mpl-hydra',
    docs: '/hydra',
  },
}
