/**
 * Example: api_bonding_curve_devnet
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createAndRegisterLaunch } from '@metaplex-foundation/genesis/api';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { keypairIdentity } from '@metaplex-foundation/umi';",
  "setup": "const umi = createUmi('https://api.devnet.solana.com');\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes);\numi.use(keypairIdentity(keypair));",
  "main": "const result = await createAndRegisterLaunch(umi, {}, {\n  wallet: umi.identity.publicKey,\n  launchType: 'bondingCurve',\n  network: 'solana-devnet',\n  token: {\n    name: 'Test Token',\n    symbol: 'TEST',\n    image: 'https://gateway.irys.xyz/test-image',\n  },\n  launch: {},\n});",
  "output": "",
  "full": "// [IMPORTS]\nimport { createAndRegisterLaunch } from '@metaplex-foundation/genesis/api';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { keypairIdentity } from '@metaplex-foundation/umi';\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.devnet.solana.com');\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes);\numi.use(keypairIdentity(keypair));\n// [/SETUP]\n\n// [MAIN]\nconst result = await createAndRegisterLaunch(umi, {}, {\n  wallet: umi.identity.publicKey,\n  launchType: 'bondingCurve',\n  network: 'solana-devnet',\n  token: {\n    name: 'Test Token',\n    symbol: 'TEST',\n    image: 'https://gateway.irys.xyz/test-image',\n  },\n  launch: {},\n});\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Network is determined by your configured RPC endpoint.\nmplx genesis launch create --launchType bonding-curve \\\n  --name \"Test Token\" \\\n  --symbol \"TEST\" \\\n  --image \"https://gateway.irys.xyz/test-image\"\n"
}

export const metadata = {
  title: "api_bonding_curve_devnet",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
