/**
 * Example: deposit_from_separate_wallet
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { deposit, mplDistro } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst amount = 350_000n\nconst treasurySigner = umi.identity\nconst feePayer = umi.payer\nconst distributionAuthority = umi.identity",
  "main": "await deposit(umi, {\n  distribution,\n  mint,\n  depositor: treasurySigner,\n  payer: feePayer,\n  authority: distributionAuthority,\n  amount,\n}).sendAndConfirm(umi)",
  "output": "// Tokens move from the treasury ATA to the distribution vault.",
  "full": "// [IMPORTS]\nimport { deposit, mplDistro } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst amount = 350_000n\nconst treasurySigner = umi.identity\nconst feePayer = umi.payer\nconst distributionAuthority = umi.identity\n// [/SETUP]\n\n// [MAIN]\nawait deposit(umi, {\n  distribution,\n  mint,\n  depositor: treasurySigner,\n  payer: feePayer,\n  authority: distributionAuthority,\n  amount,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// Tokens move from the treasury ATA to the distribution vault.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "deposit_from_separate_wallet",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
