/**
 * Example: delegate-locked-transfer-transfer
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst currentOwner = address('currentOwnerAddress...');\nconst newOwner = address('newOwnerAddress...');",
  "main": "const transferIx = await getTransferV1InstructionAsync({\n  mint,\n  authority: lockedTransferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [transferIx],\n  payer: lockedTransferDelegate,\n});",
  "output": "console.log('pNFT transferred via Locked Transfer delegate');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst currentOwner = address('currentOwnerAddress...');\nconst newOwner = address('newOwnerAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst transferIx = await getTransferV1InstructionAsync({\n  mint,\n  authority: lockedTransferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [transferIx],\n  payer: lockedTransferDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred via Locked Transfer delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  transferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst lockedTransferDelegate = umi.identity; // The delegate authority\nconst currentOwner = publicKey('currentOwnerAddress...');\nconst newOwner = publicKey('newOwnerAddress...');",
  "main": "await transferV1(umi, {\n  mint,\n  authority: lockedTransferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('pNFT transferred via Locked Transfer delegate');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  transferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst lockedTransferDelegate = umi.identity; // The delegate authority\nconst currentOwner = publicKey('currentOwnerAddress...');\nconst newOwner = publicKey('newOwnerAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait transferV1(umi, {\n  mint,\n  authority: lockedTransferDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred via Locked Transfer delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-locked-transfer-transfer",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
