/**
 * Example: pnft-auth-rules-program
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';",
  "setup": "",
  "main": "// Token Auth Rules Program ID\nconst authorizationRulesProgram = address('auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg');",
  "output": "console.log('Auth Rules Program:', authorizationRulesProgram);",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\n// [/IMPORTS]\n\n// [SETUP]\n// [/SETUP]\n\n// [MAIN]\n// Token Auth Rules Program ID\nconst authorizationRulesProgram = address('auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg');\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Auth Rules Program:', authorizationRulesProgram);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { getMplTokenAuthRulesProgramId } from '@metaplex-foundation/mpl-token-auth-rules';",
  "setup": "",
  "main": "const authorizationRulesProgram = getMplTokenAuthRulesProgramId(umi);",
  "output": "console.log('Auth Rules Program:', authorizationRulesProgram);",
  "full": "// [IMPORTS]\nimport { getMplTokenAuthRulesProgramId } from '@metaplex-foundation/mpl-token-auth-rules';\n// [/IMPORTS]\n\n// [SETUP]\n// [/SETUP]\n\n// [MAIN]\nconst authorizationRulesProgram = getMplTokenAuthRulesProgramId(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Auth Rules Program:', authorizationRulesProgram);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "pnft-auth-rules-program",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
