/**
 * Example: api_error_handling
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  createAndRegisterLaunch,\n  isGenesisApiError,\n  isGenesisApiNetworkError,\n  isGenesisValidationError,\n} from '@metaplex-foundation/genesis'",
  "setup": "// Assumes umi and input from the Easy Mode example.",
  "main": "try {\n  const result = await createAndRegisterLaunch(umi, input)\n  console.log(`Launch live at: ${result.launch.link}`)\n} catch (err) {\n  if (isGenesisValidationError(err)) {\n    console.error(`Invalid input \"${err.field}\":`, err.message)\n  } else if (isGenesisApiError(err)) {\n    console.error('API error:', err.statusCode, err.responseBody)\n  } else if (isGenesisApiNetworkError(err)) {\n    console.error('Network error:', err.cause.message)\n  } else {\n    throw err\n  }\n}",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  createAndRegisterLaunch,\n  isGenesisApiError,\n  isGenesisApiNetworkError,\n  isGenesisValidationError,\n} from '@metaplex-foundation/genesis'\n// [/IMPORTS]\n\n// [SETUP]\n// Assumes umi and input from the Easy Mode example.\n// [/SETUP]\n\n// [MAIN]\ntry {\n  const result = await createAndRegisterLaunch(umi, input)\n  console.log(`Launch live at: ${result.launch.link}`)\n} catch (err) {\n  if (isGenesisValidationError(err)) {\n    console.error(`Invalid input \"${err.field}\":`, err.message)\n  } else if (isGenesisApiError(err)) {\n    console.error('API error:', err.statusCode, err.responseBody)\n  } else if (isGenesisApiNetworkError(err)) {\n    console.error('Network error:', err.cause.message)\n  } else {\n    throw err\n  }\n}\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "api_error_handling",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
