/**
 * Example: verify-collection
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getVerifyCollectionV1InstructionAsync,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and collectionAuthority are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT to verify\nconst collectionMintAddress = 'collectionMintAddress...'; // The collection NFT",
  "main": "// Find the metadata PDA\nconst [metadata] = await findMetadataPda({ mint: mintAddress });\n\n// Verify the collection on the NFT\nconst verifyIx = await getVerifyCollectionV1InstructionAsync({\n  metadata,\n  collectionMint: collectionMintAddress,\n  authority: collectionAuthority,\n  payer: collectionAuthority,\n});\n\nawait sendAndConfirm([verifyIx], [collectionAuthority]);",
  "output": "console.log('Collection verified on NFT');",
  "full": "// [IMPORTS]\nimport {\n  getVerifyCollectionV1InstructionAsync,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and collectionAuthority are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT to verify\nconst collectionMintAddress = 'collectionMintAddress...'; // The collection NFT\n// [/SETUP]\n\n// [MAIN]\n// Find the metadata PDA\nconst [metadata] = await findMetadataPda({ mint: mintAddress });\n\n// Verify the collection on the NFT\nconst verifyIx = await getVerifyCollectionV1InstructionAsync({\n  metadata,\n  collectionMint: collectionMintAddress,\n  authority: collectionAuthority,\n  payer: collectionAuthority,\n});\n\nawait sendAndConfirm([verifyIx], [collectionAuthority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection verified on NFT');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { verifyCollectionV1, findMetadataPda } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, collectionMint, and collectionAuthority are set up\n\nconst mintAddress = publicKey('mintAddress...');",
  "main": "// First find the metadata PDA to use later\nconst metadata = findMetadataPda(umi, {\n  mint: mintAddress,\n});\n\nawait verifyCollectionV1(umi, {\n  metadata,\n  collectionMint,\n  authority: collectionAuthority,\n}).sendAndConfirm(umi);",
  "output": "console.log('Collection verified on NFT');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { verifyCollectionV1, findMetadataPda } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, collectionMint, and collectionAuthority are set up\n\nconst mintAddress = publicKey('mintAddress...');\n// [/SETUP]\n\n// [MAIN]\n// First find the metadata PDA to use later\nconst metadata = findMetadataPda(umi, {\n  mint: mintAddress,\n});\n\nawait verifyCollectionV1(umi, {\n  metadata,\n  collectionMint,\n  authority: collectionAuthority,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection verified on NFT');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "verify-collection",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
