/**
 * Example: api_claim_creator_rewards
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { claimCreatorRewards } from '@metaplex-foundation/genesis'\nimport { base58 } from '@metaplex-foundation/umi/serializers'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "const result = await claimCreatorRewards(umi, {}, {\n  wallet: umi.identity.publicKey,\n  network: 'solana-mainnet',\n  // payer is optional — defaults to `wallet` on the server.\n  // Set it to have a different wallet cover rent and transaction fees.\n  // payer: umi.identity.publicKey,\n})\n\nfor (const tx of result.transactions) {\n  const signed = await umi.identity.signTransaction(tx)\n  const signature = await umi.rpc.sendTransaction(signed, {\n    preflightCommitment: 'confirmed',\n  })\n  await umi.rpc.confirmTransaction(signature, {\n    strategy: { type: 'blockhash', ...result.blockhash },\n    commitment: 'confirmed',\n  })\n  console.log('Claimed:', base58.deserialize(signature)[0])\n}",
  "output": "// Claimed: 5uGGYEMmjP2HpyFCvLPNpVDSQEBtUE3LR6ZQFqhJxQSh5FbKacSyN8nQmAJowuFs6BTCdwzoFyyJz8Y2hQx8kPxo\n// Claimed: 3TAroVovEap1ZEAJYq3WiDZoMK3GU3soCdrhvZJNg6b9EANqvWrVcDGNffm7mD8wvtpR7ynWQBcbrmz8AK6nrhfy",
  "full": "// [IMPORTS]\nimport { claimCreatorRewards } from '@metaplex-foundation/genesis'\nimport { base58 } from '@metaplex-foundation/umi/serializers'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\nconst result = await claimCreatorRewards(umi, {}, {\n  wallet: umi.identity.publicKey,\n  network: 'solana-mainnet',\n  // payer is optional — defaults to `wallet` on the server.\n  // Set it to have a different wallet cover rent and transaction fees.\n  // payer: umi.identity.publicKey,\n})\n\nfor (const tx of result.transactions) {\n  const signed = await umi.identity.signTransaction(tx)\n  const signature = await umi.rpc.sendTransaction(signed, {\n    preflightCommitment: 'confirmed',\n  })\n  await umi.rpc.confirmTransaction(signature, {\n    strategy: { type: 'blockhash', ...result.blockhash },\n    commitment: 'confirmed',\n  })\n  console.log('Claimed:', base58.deserialize(signature)[0])\n}\n// [/MAIN]\n\n// [OUTPUT]\n// Claimed: 5uGGYEMmjP2HpyFCvLPNpVDSQEBtUE3LR6ZQFqhJxQSh5FbKacSyN8nQmAJowuFs6BTCdwzoFyyJz8Y2hQx8kPxo\n// Claimed: 3TAroVovEap1ZEAJYq3WiDZoMK3GU3soCdrhvZJNg6b9EANqvWrVcDGNffm7mD8wvtpR7ynWQBcbrmz8AK6nrhfy\n// [/OUTPUT]\n"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Claim creator rewards. Response contains base64-encoded transactions\n# the wallet (or payer) must sign and send.\ncurl -X POST https://api.metaplex.com/v1/creator-rewards/claim \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"wallet\": \"CREATOR_FEE_WALLET_ADDRESS_HERE\",\n    \"network\": \"solana-mainnet\"\n  }'\n\n# Add \"payer\" when the creator fee wallet does not hold SOL (e.g. an agent PDA):\n#   \"payer\": \"PAYER_WALLET_ADDRESS_HERE\"\n"
}

export const metadata = {
  title: "api_claim_creator_rewards",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
