/**
 * Example: convert-to-asset
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'",
  "setup": "const umi = createUmi('<ENDPOINT>').use(dasApi())",
  "main": "const dasAssets = await umi.rpc.getAssetsByOwner({ owner: publicKey('<pubkey>') })\n\nconst dasCoreAssets = dasAssets.items.filter((a) => a.interface === 'MplCoreAsset')\n\nconst coreAssets = await das.dasAssetsToCoreAssets(umi, dasCoreAssets)",
  "output": "console.log(coreAssets)",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<ENDPOINT>').use(dasApi())\n// [/SETUP]\n\n// [MAIN]\nconst dasAssets = await umi.rpc.getAssetsByOwner({ owner: publicKey('<pubkey>') })\n\nconst dasCoreAssets = dasAssets.items.filter((a) => a.interface === 'MplCoreAsset')\n\nconst coreAssets = await das.dasAssetsToCoreAssets(umi, dasCoreAssets)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log(coreAssets)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "convert-to-asset",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
