/**
 * Example: persist_claim_records
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst allocations = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100_000n, nonce: 0n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 250_000n, nonce: 0n },\n]",
  "main": "const { root, proofs, treeHeight } = prepareDistribution(allocations)\n\nconst claimRecords = allocations.map((allocation, index) => ({\n  address: allocation.address,\n  amount: allocation.amount.toString(),\n  nonce: (allocation.nonce ?? 0n).toString(),\n  proof: proofs[index],\n}))\n\n// Persist claimRecords with the distribution PDA after createDistribution.\nconsole.log(root, treeHeight, claimRecords.length)",
  "output": "// One durable record per allocation: address, amount, nonce, and proof.",
  "full": "// [IMPORTS]\nimport { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst allocations = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100_000n, nonce: 0n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 250_000n, nonce: 0n },\n]\n// [/SETUP]\n\n// [MAIN]\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\n\nconst claimRecords = allocations.map((allocation, index) => ({\n  address: allocation.address,\n  amount: allocation.amount.toString(),\n  nonce: (allocation.nonce ?? 0n).toString(),\n  proof: proofs[index],\n}))\n\n// Persist claimRecords with the distribution PDA after createDistribution.\nconsole.log(root, treeHeight, claimRecords.length)\n// [/MAIN]\n\n// [OUTPUT]\n// One durable record per allocation: address, amount, nonce, and proof.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "persist_claim_records",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
