import {
  documentationSection
} from '@/shared/sections';
import { TableCellsIcon } from '@heroicons/react/24/solid';
import { Hero } from './Hero';

export const das = {
  name: 'DAS API',
  headline: 'Fetch Digital Asset Data',
  description:
    'A DAS API Client to access Digital Asset data on chain',
  path: 'das-api',
  icon: <TableCellsIcon />,
  github: 'https://github.com/metaplex-foundation/digital-asset-standard-api',
  navigationMenuCatergory: 'Dev Tools',
  className: 'accent-sky',
  heroes: [{ path: '/das-api', component: Hero }],
  sections: [
    {
      ...documentationSection('das-api'),
      navigation: [
        {
          title: 'Introduction',
          links: [
            { title: 'Overview', href: '/das-api' },
            { title: 'Getting Started', href: '/das-api/getting-started' },
            { title: 'DAS API RPC Providers', href: '/rpc-providers' },
            { title: 'Display Options', href: '/das-api/display-options' },
          ],
        },
        {
          title: 'Methods & Playground',
          links: [
            { title: 'Method Overview', href: '/das-api/methods' },
            { title: 'Get Asset', href: '/das-api/methods/get-asset' },
            { title: 'Get Assets', href: '/das-api/methods/get-assets' },
            { title: 'Get Asset Proof', href: '/das-api/methods/get-asset-proof' },
            { title: 'Get Asset Proofs', href: '/das-api/methods/get-asset-proofs' },
            { title: 'Get Asset Signatures', href: '/das-api/methods/get-asset-signatures' },
            { title: 'Get Assets By Authority', href: '/das-api/methods/get-assets-by-authority' },
            { title: 'Get Assets By Creator', href: '/das-api/methods/get-assets-by-creator' },
            { title: 'Get Assets By Group', href: '/das-api/methods/get-assets-by-group' },
            { title: 'Get Assets By Owner', href: '/das-api/methods/get-assets-by-owner' },
            { title: 'Get NFT Editions', href: '/das-api/methods/get-nft-editions' },
            { title: 'Get Token Accounts', href: '/das-api/methods/get-token-accounts' },
            { title: 'Search Assets', href: '/das-api/methods/search-assets' },
          ],
        },
        {
          title: 'Guides',
          links: [
            { title: 'Guides Overview', href: '/das-api/guides' },
            { title: 'Pagination', href: '/das-api/guides/pagination' },
            { title: 'Get Collection NFTs', href: '/das-api/guides/get-collection-nfts' },
            { title: 'Get NFTs by Owner', href: '/das-api/guides/get-nfts-by-owner' },
            { title: 'Get Wallet Tokens', href: '/das-api/guides/get-wallet-tokens' },
            { title: 'Get Fungible Assets', href: '/das-api/guides/get-fungible-assets' },
            { title: 'Search by Criteria', href: '/das-api/guides/search-by-criteria' },
            { title: 'Owner and Collection', href: '/das-api/guides/owner-and-collection' },
            { title: 'Find Compressed NFTs', href: '/das-api/guides/find-compressed-nfts' },
            { title: 'Collection Statistics', href: '/das-api/guides/collection-statistics' },
            { title: 'Find Token Holders', href: '/das-api/guides/find-token-holders' },
          ],
        },
        {
          title: 'Core Extension SDK',
          links: [
            { title: 'Extension Overview', href: '/das-api/core-extension' },
            { title: 'Get Core Asset', href: '/das-api/core-extension/methods/get-asset' },
            { title: 'Get Core Collection', href: '/das-api/core-extension/methods/get-collection' },
            { title: 'Get Core Assets By Authority', href: '/das-api/core-extension/methods/get-assets-by-authority' },
            { title: 'Get Core Assets By Collection', href: '/das-api/core-extension/methods/get-assets-by-collection' },
            { title: 'Get Core Assets By Owner', href: '/das-api/core-extension/methods/get-assets-by-owner' },
            { title: 'Search Core Assets', href: '/das-api/core-extension/methods/search-assets' },
            { title: 'Search Core Collections', href: '/das-api/core-extension/methods/search-collections' },
            { title: 'Plugin Derivation', href: '/das-api/core-extension/plugin-derivation' },
            { title: 'Type Conversion', href: '/das-api/core-extension/convert-das-asset-to-core' },
          ],
        },
      ],
    },
  ],
  localizedNavigation: {
    en: {
      headline: 'Fetch Digital Asset Data',
      description: 'A DAS API Client to access Digital Asset data on chain',
      sections: {
        'Introduction': 'Introduction',
        'Methods & Playground': 'Methods & Playground',
        'Guides': 'Guides',
        'Core Extension SDK': 'Core Extension SDK'
      },
      links: {
        'Overview': 'Overview',
        'Getting Started': 'Getting Started',
        'DAS API RPC Providers': 'DAS API RPC Providers',
        'Display Options': 'Display Options',
        'Method Overview': 'Method Overview',
        'Get Asset': 'Get Asset',
        'Get Assets': 'Get Assets',
        'Get Asset Proof': 'Get Asset Proof',
        'Get Asset Proofs': 'Get Asset Proofs',
        'Get Asset Signatures': 'Get Asset Signatures',
        'Get Assets By Authority': 'Get Assets By Authority',
        'Get Assets By Creator': 'Get Assets By Creator',
        'Get Assets By Group': 'Get Assets By Group',
        'Get Assets By Owner': 'Get Assets By Owner',
        'Get NFT Editions': 'Get NFT Editions',
        'Get Token Accounts': 'Get Token Accounts',
        'Search Assets': 'Search Assets',
        'Guides Overview': 'Guides Overview',
        'Pagination': 'Pagination',
        'Get Collection NFTs': 'Get Collection NFTs',
        'Get NFTs by Owner': 'Get NFTs by Owner',
        'Get Wallet Tokens': 'Get Wallet Tokens',
        'Get Fungible Assets': 'Get Fungible Assets',
        'Search by Criteria': 'Search by Criteria',
        'Owner and Collection': 'Owner and Collection',
        'Find Compressed NFTs': 'Find Compressed NFTs',
        'Collection Statistics': 'Collection Statistics',
        'Find Token Holders': 'Find Token Holders',
        'Extension Overview': 'Extension Overview',
        'Get Core Asset': 'Get Core Asset',
        'Get Core Collection': 'Get Core Collection',
        'Get Core Assets By Authority': 'Get Core Assets By Authority',
        'Get Core Assets By Collection': 'Get Core Assets By Collection',
        'Get Core Assets By Owner': 'Get Core Assets By Owner',
        'Search Core Assets': 'Search Core Assets',
        'Search Core Collections': 'Search Core Collections',
        'Plugin Derivation': 'Plugin Derivation',
        'Type Conversion': 'Type Conversion'
      }
    },
    ja: {
      headline: 'デジタルアセットデータの取得',
      description: 'オンチェーンデジタルアセットデータにアクセスするDAS APIクライアント',
      sections: {
        'Introduction': '紹介',
        'Methods & Playground': 'メソッドとプレイグラウンド',
        'Guides': 'ガイド',
        'Core Extension SDK': 'Core拡張SDK'
      },
      links: {
        'Overview': '概要',
        'Getting Started': 'はじめに',
        'DAS API RPC Providers': 'DAS API RPCプロバイダー',
        'Display Options': '表示オプション',
        'Method Overview': 'メソッド概要',
        'Get Asset': 'アセットの取得',
        'Get Assets': '複数アセットの取得',
        'Get Asset Proof': 'アセット証明の取得',
        'Get Asset Proofs': '複数アセット証明の取得',
        'Get Asset Signatures': 'アセット署名の取得',
        'Get Assets By Authority': '権限別アセットの取得',
        'Get Assets By Creator': '作成者別アセットの取得',
        'Get Assets By Group': 'グループ別アセットの取得',
        'Get Assets By Owner': '所有者別アセットの取得',
        'Get NFT Editions': 'NFTエディションの取得',
        'Get Token Accounts': 'トークンアカウントの取得',
        'Search Assets': 'アセットの検索',
        'Guides Overview': 'ガイド概要',
        'Pagination': 'ページネーション',
        'Get Collection NFTs': 'コレクションNFTの取得',
        'Get NFTs by Owner': '所有者別NFTの取得',
        'Get Wallet Tokens': 'ウォレットトークンの取得',
        'Get Fungible Assets': 'ファンジブルアセットの取得',
        'Search by Criteria': '条件による検索',
        'Owner and Collection': '所有者とコレクション',
        'Find Compressed NFTs': '圧縮NFTの検索',
        'Collection Statistics': 'コレクション統計',
        'Find Token Holders': 'トークン保有者の検索',
        'Extension Overview': '拡張機能の概要',
        'Get Core Asset': 'Coreアセットの取得',
        'Get Core Collection': 'Coreコレクションの取得',
        'Get Core Assets By Authority': '権限別Coreアセットの取得',
        'Get Core Assets By Collection': 'コレクション別Coreアセットの取得',
        'Get Core Assets By Owner': '所有者別Coreアセットの取得',
        'Search Core Assets': 'Coreアセットの検索',
        'Search Core Collections': 'Coreコレクションの検索',
        'Plugin Derivation': 'プラグインの導出',
        'Type Conversion': '型変換'
      }
    },
    ko: {
      headline: '디지털 에셋 데이터 가져오기',
      description: '온체인 디지털 에셋 데이터에 접근하는 DAS API 클라이언트',
      sections: {
        'Introduction': '소개',
        'Methods & Playground': '메서드와 플레이그라운드',
        'Guides': '가이드',
        'Core Extension SDK': 'Core 확장 SDK'
      },
      links: {
        'Overview': '개요',
        'Getting Started': '시작하기',
        'DAS API RPC Providers': 'DAS API RPC 제공업체',
        'Display Options': '표시 옵션',
        'Method Overview': '메서드 개요',
        'Get Asset': '에셋 가져오기',
        'Get Assets': '여러 에셋 가져오기',
        'Get Asset Proof': '에셋 증명 가져오기',
        'Get Asset Proofs': '여러 에셋 증명 가져오기',
        'Get Asset Signatures': '에셋 서명 가져오기',
        'Get Assets By Authority': '권한별 에셋 가져오기',
        'Get Assets By Creator': '생성자별 에셋 가져오기',
        'Get Assets By Group': '그룹별 에셋 가져오기',
        'Get Assets By Owner': '소유자별 에셋 가져오기',
        'Get NFT Editions': 'NFT 에디션 가져오기',
        'Get Token Accounts': '토큰 계정 가져오기',
        'Search Assets': '에셋 검색',
        'Guides Overview': '가이드 개요',
        'Pagination': '페이지네이션',
        'Get Collection NFTs': '컬렉션 NFT 가져오기',
        'Get NFTs by Owner': '소유자별 NFT 가져오기',
        'Get Wallet Tokens': '지갑 토큰 가져오기',
        'Get Fungible Assets': '대체 가능 에셋 가져오기',
        'Search by Criteria': '조건별 검색',
        'Owner and Collection': '소유자와 컬렉션',
        'Find Compressed NFTs': '압축 NFT 찾기',
        'Collection Statistics': '컬렉션 통계',
        'Find Token Holders': '토큰 보유자 찾기',
        'Extension Overview': '확장 개요',
        'Get Core Asset': 'Core 에셋 가져오기',
        'Get Core Collection': 'Core 컬렉션 가져오기',
        'Get Core Assets By Authority': '권한별 Core 에셋 가져오기',
        'Get Core Assets By Collection': '컬렉션별 Core 에셋 가져오기',
        'Get Core Assets By Owner': '소유자별 Core 에셋 가져오기',
        'Search Core Assets': 'Core 에셋 검색',
        'Search Core Collections': 'Core 컬렉션 검색',
        'Plugin Derivation': '플러그인 파생',
        'Type Conversion': '타입 변환'
      }
    }
  }
}
