/**
 * Example: add_unlocked_bucket_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  addUnlockedBucketV2,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, baseMint, claimStart, and claimEnd from previous steps.",
  "main": "await addUnlockedBucketV2(umi, {\n  genesisAccount,\n  baseMint: baseMint.publicKey,\n  baseTokenAllocation: 0n,\n  recipient: umi.identity.publicKey,\n  claimStartCondition: {\n    __kind: 'TimeAbsolute',\n    padding: Array(47).fill(0),\n    time: claimStart,\n    triggeredTimestamp: null,\n  },\n  claimEndCondition: {\n    __kind: 'TimeAbsolute',\n    padding: Array(47).fill(0),\n    time: claimEnd,\n    triggeredTimestamp: null,\n  },\n  backendSigner: null,\n}).sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  addUnlockedBucketV2,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, baseMint, claimStart, and claimEnd from previous steps.\n// [/SETUP]\n\n// [MAIN]\nawait addUnlockedBucketV2(umi, {\n  genesisAccount,\n  baseMint: baseMint.publicKey,\n  baseTokenAllocation: 0n,\n  recipient: umi.identity.publicKey,\n  claimStartCondition: {\n    __kind: 'TimeAbsolute',\n    padding: Array(47).fill(0),\n    time: claimStart,\n    triggeredTimestamp: null,\n  },\n  claimEndCondition: {\n    __kind: 'TimeAbsolute',\n    padding: Array(47).fill(0),\n    time: claimEnd,\n    triggeredTimestamp: null,\n  },\n  backendSigner: null,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "add_unlocked_bucket_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
