/**
 * Example: add_unlocked_bucket_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\r\n  addUnlockedBucketV2,\r\n  genesis,\r\n} from '@metaplex-foundation/genesis'\r\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\r\nimport { generateSigner, keypairIdentity } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\r\n  .use(mplToolbox())\r\n  .use(genesis())\r\n\r\n// umi.use(keypairIdentity(yourKeypair));\r\n\r\n// Assumes genesisAccount, baseMint, claimStart, and claimEnd from previous steps.",
  "main": "await addUnlockedBucketV2(umi, {\r\n  genesisAccount,\r\n  baseMint: baseMint.publicKey,\r\n  baseTokenAllocation: 0n,\r\n  recipient: umi.identity.publicKey,\r\n  claimStartCondition: {\r\n    __kind: 'TimeAbsolute',\r\n    padding: Array(47).fill(0),\r\n    time: claimStart,\r\n    triggeredTimestamp: null,\r\n  },\r\n  claimEndCondition: {\r\n    __kind: 'TimeAbsolute',\r\n    padding: Array(47).fill(0),\r\n    time: claimEnd,\r\n    triggeredTimestamp: null,\r\n  },\r\n  backendSigner: null,\r\n}).sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\r\nimport {\r\n  addUnlockedBucketV2,\r\n  genesis,\r\n} from '@metaplex-foundation/genesis'\r\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\r\nimport { generateSigner, keypairIdentity } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\r\n  .use(mplToolbox())\r\n  .use(genesis())\r\n\r\n// umi.use(keypairIdentity(yourKeypair));\r\n\r\n// Assumes genesisAccount, baseMint, claimStart, and claimEnd from previous steps.\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\nawait addUnlockedBucketV2(umi, {\r\n  genesisAccount,\r\n  baseMint: baseMint.publicKey,\r\n  baseTokenAllocation: 0n,\r\n  recipient: umi.identity.publicKey,\r\n  claimStartCondition: {\r\n    __kind: 'TimeAbsolute',\r\n    padding: Array(47).fill(0),\r\n    time: claimStart,\r\n    triggeredTimestamp: null,\r\n  },\r\n  claimEndCondition: {\r\n    __kind: 'TimeAbsolute',\r\n    padding: Array(47).fill(0),\r\n    time: claimEnd,\r\n    triggeredTimestamp: null,\r\n  },\r\n  backendSigner: null,\r\n}).sendAndConfirm(umi)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\n// [/OUTPUT]\r\n"
}

export const metadata = {
  title: "add_unlocked_bucket_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
