/**
 * Example: delegate-transfer-revoke
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getRevokeTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, owner, and transferDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address",
  "main": "// Revoke a Transfer delegate (pNFT only)\nconst revokeIx = await getRevokeTransferV1InstructionAsync({\n  mint: mintAddress,\n  delegate: transferDelegate,\n  authority: owner,\n  payer: owner,\n  tokenOwner: owner.address,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [owner]);",
  "output": "console.log('Transfer delegate revoked');",
  "full": "// [IMPORTS]\nimport {\n  getRevokeTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, owner, and transferDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address\n// [/SETUP]\n\n// [MAIN]\n// Revoke a Transfer delegate (pNFT only)\nconst revokeIx = await getRevokeTransferV1InstructionAsync({\n  mint: mintAddress,\n  delegate: transferDelegate,\n  authority: owner,\n  payer: owner,\n  tokenOwner: owner.address,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [owner]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Transfer delegate revoked');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { revokeTransferV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, mint, owner, and transferDelegate are set up",
  "main": "await revokeTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: transferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Transfer delegate revoked');",
  "full": "// [IMPORTS]\nimport { revokeTransferV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, mint, owner, and transferDelegate are set up\n// [/SETUP]\n\n// [MAIN]\nawait revokeTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: transferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Transfer delegate revoked');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-transfer-revoke",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
