/**
 * Example: fetch-group
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport { fetchGroupV1 } from '@metaplex-foundation/mpl-core'",
  "setup": "const groupAddress = publicKey('GroupAddress...')",
  "main": "const group = await fetchGroupV1(umi, groupAddress)",
  "output": "console.log(group.name)\nconsole.log(group.collections)\nconsole.log(group.groups)\nconsole.log(group.assets)",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { fetchGroupV1 } from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst groupAddress = publicKey('GroupAddress...')\n// [/SETUP]\n\n// [MAIN]\nconst group = await fetchGroupV1(umi, groupAddress)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log(group.name)\nconsole.log(group.collections)\nconsole.log(group.groups)\nconsole.log(group.assets)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-group",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
