/**
 * Example: Burn Fungible Tokens
 *
 * Burn fungible tokens from your wallet
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getBurnV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint",
  "main": "// Burn fungible tokens from your wallet\nconst burnIx = await getBurnV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  tokenOwner: authority.address,\n  amount: 100n, // Amount to burn (accounting for decimals)\n  tokenStandard: TokenStandard.Fungible,\n});\n\nawait sendAndConfirm({\n  instructions: [burnIx],\n  payer: authority,\n});",
  "output": "console.log('Burned tokens');\nconsole.log('Mint:', mintAddress);",
  "full": "// [IMPORTS]\nimport {\n  getBurnV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint\n// [/SETUP]\n\n// [MAIN]\n// Burn fungible tokens from your wallet\nconst burnIx = await getBurnV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  tokenOwner: authority.address,\n  amount: 100n, // Amount to burn (accounting for decimals)\n  tokenStandard: TokenStandard.Fungible,\n});\n\nawait sendAndConfirm({\n  instructions: [burnIx],\n  payer: authority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Burned tokens');\nconsole.log('Mint:', mintAddress);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "// To install all the required packages use the following command\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n    burnToken,\n    findAssociatedTokenPda,\n} from '@metaplex-foundation/mpl-toolbox';\nimport {\n    keypairIdentity,\n    publicKey,\n} from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { readFileSync } from 'fs';",
  "setup": "// Initialize Umi with Devnet endpoint\nconst umi = createUmi('https://api.devnet.solana.com')\n\n// Load your wallet/keypair\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address\nconst mintAddress = publicKey('<your token mint address>')",
  "main": "// Find the token account to burn from\nconst tokenAccount = findAssociatedTokenPda(umi, {\n  mint: mintAddress,\n  owner: umi.identity.publicKey,\n})\n\n// Burn 100 tokens\nawait burnToken(umi, {\n  account: tokenAccount,\n  mint: mintAddress,\n  amount: 100,\n}).sendAndConfirm(umi)",
  "output": "console.log('Burned 100 tokens')\nconsole.log('Mint:', mintAddress)\nconsole.log('Token Account:', tokenAccount)",
  "full": "// [IMPORTS]\n// To install all the required packages use the following command\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n    burnToken,\n    findAssociatedTokenPda,\n} from '@metaplex-foundation/mpl-toolbox';\nimport {\n    keypairIdentity,\n    publicKey,\n} from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { readFileSync } from 'fs';\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize Umi with Devnet endpoint\nconst umi = createUmi('https://api.devnet.solana.com')\n\n// Load your wallet/keypair\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address\nconst mintAddress = publicKey('<your token mint address>')\n// [/SETUP]\n\n// [MAIN]\n// Find the token account to burn from\nconst tokenAccount = findAssociatedTokenPda(umi, {\n  mint: mintAddress,\n  owner: umi.identity.publicKey,\n})\n\n// Burn 100 tokens\nawait burnToken(umi, {\n  account: tokenAccount,\n  mint: mintAddress,\n  amount: 100,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Burned 100 tokens')\nconsole.log('Mint:', mintAddress)\nconsole.log('Token Account:', tokenAccount)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Burn Fungible Tokens",
  description: "Burn fungible tokens from your wallet",
  tags: ['token-metadata', 'fungible', 'spl-token', 'burn', 'beginner'],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
