/**
 * Example: Burn Fungible Tokens
 *
 * Burn fungible tokens from your wallet
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getBurnV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint",
  "main": "// Burn fungible tokens from your wallet\nconst burnIx = await getBurnV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  tokenOwner: authority.address,\n  amount: 100n, // Amount to burn (accounting for decimals)\n  tokenStandard: TokenStandard.Fungible,\n});\n\nawait sendAndConfirm([burnIx], [authority]);",
  "output": "console.log('Burned tokens');\nconsole.log('Mint:', mintAddress);",
  "full": "// [IMPORTS]\nimport {\n  getBurnV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint\n// [/SETUP]\n\n// [MAIN]\n// Burn fungible tokens from your wallet\nconst burnIx = await getBurnV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  tokenOwner: authority.address,\n  amount: 100n, // Amount to burn (accounting for decimals)\n  tokenStandard: TokenStandard.Fungible,\n});\n\nawait sendAndConfirm([burnIx], [authority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Burned tokens');\nconsole.log('Mint:', mintAddress);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "// To install all the required packages use the following command\r\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\r\nimport {\r\n    burnToken,\r\n    findAssociatedTokenPda,\r\n} from '@metaplex-foundation/mpl-toolbox';\r\nimport {\r\n    keypairIdentity,\r\n    publicKey,\r\n} from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\r\nimport { readFileSync } from 'fs';",
  "setup": "// Initialize Umi with Devnet endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n\r\n// Load your wallet/keypair\r\nconst wallet = '<your wallet file path>'\r\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\r\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\r\numi.use(keypairIdentity(keypair))\r\n\r\n// Your token mint address\r\nconst mintAddress = publicKey('<your token mint address>')",
  "main": "// Find the token account to burn from\r\nconst tokenAccount = findAssociatedTokenPda(umi, {\r\n  mint: mintAddress,\r\n  owner: umi.identity.publicKey,\r\n})\r\n\r\n// Burn 100 tokens\r\nawait burnToken(umi, {\r\n  account: tokenAccount,\r\n  mint: mintAddress,\r\n  amount: 100,\r\n}).sendAndConfirm(umi)",
  "output": "console.log('Burned 100 tokens')\r\nconsole.log('Mint:', mintAddress)\r\nconsole.log('Token Account:', tokenAccount)",
  "full": "// [IMPORTS]\r\n// To install all the required packages use the following command\r\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\r\nimport {\r\n    burnToken,\r\n    findAssociatedTokenPda,\r\n} from '@metaplex-foundation/mpl-toolbox';\r\nimport {\r\n    keypairIdentity,\r\n    publicKey,\r\n} from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\r\nimport { readFileSync } from 'fs';\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize Umi with Devnet endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n\r\n// Load your wallet/keypair\r\nconst wallet = '<your wallet file path>'\r\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\r\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\r\numi.use(keypairIdentity(keypair))\r\n\r\n// Your token mint address\r\nconst mintAddress = publicKey('<your token mint address>')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Find the token account to burn from\r\nconst tokenAccount = findAssociatedTokenPda(umi, {\r\n  mint: mintAddress,\r\n  owner: umi.identity.publicKey,\r\n})\r\n\r\n// Burn 100 tokens\r\nawait burnToken(umi, {\r\n  account: tokenAccount,\r\n  mint: mintAddress,\r\n  amount: 100,\r\n}).sendAndConfirm(umi)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Burned 100 tokens')\r\nconsole.log('Mint:', mintAddress)\r\nconsole.log('Token Account:', tokenAccount)\r\n// [/OUTPUT]\r\n"
}

export const metadata = {
  title: "Burn Fungible Tokens",
  description: "Burn fungible tokens from your wallet",
  tags: ['token-metadata', 'fungible', 'spl-token', 'burn', 'beginner'],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
