import { CodeTabsWithContext } from './CodeTabsWithContext'

/**
 * CodeTabsImported - Load code examples from centralized example files
 *
 * Renders multi-framework code tabs by importing from src/examples/
 * This allows code to be maintained in one place and reused across
 * multiple pages and languages (EN/JA/KO).
 *
 * @param {Object} props
 * @param {string} props.from - Path to example file (e.g., "core/create-asset")
 * @param {string} props.frameworks - Comma-separated frameworks to show (e.g., "kit,umi,shank,anchor")
 * @param {string} props.defaultFramework - Default framework to show (defaults to "umi")
 * @param {boolean} props.showLineNumbers - Show line numbers in all tabs
 * @param {string} props.highlightLines - Lines to highlight (e.g., "1-5,7,10-12")
 * @param {string} props.showLines - Lines to display (e.g., "1-10,15-20")
 * @param {boolean} props.showCopy - Show copy button (default: true)
 *
 * @example
 * {% code-tabs-imported from="core/create-asset" frameworks="kit,umi,shank,anchor" %}
 *
 * @example
 * {% code-tabs-imported from="core/create-asset" frameworks="umi,anchor" defaultFramework="umi" showLineNumbers=true highlightLines="5-7" %}
 */
export function CodeTabsImported({
  from,
  frameworks = 'kit,umi,shank,anchor',
  defaultFramework = 'umi',
  showLineNumbers = true,
  highlightLines = '',
  showLines = '',
  showCopy = true
}) {
  // Dynamically import the example file
  // The index.js files are generated by scripts/build-examples.js
  // with code inlined as string constants (no runtime fs operations)
  let exampleModule
  try {
    exampleModule = require(`@/examples/${from}/index.js`)
  } catch (error) {
    console.error(`Failed to load example from "${from}":`, error)
    return (
      <div className="my-6 rounded-lg border-2 border-red-300 bg-red-50 p-4 dark:border-red-800 dark:bg-red-900/20">
        <p className="font-semibold text-red-800 dark:text-red-200">
          Error: Could not load example &quot;{from}&quot;
        </p>
        <p className="mt-2 text-sm text-red-700 dark:text-red-300">
          Make sure the file exists at: <code>src/examples/{from}/index.js</code>
        </p>
        <pre className="mt-2 text-xs text-red-600 dark:text-red-400">
          {error.message}
        </pre>
      </div>
    )
  }

  if (!exampleModule) {
    return (
      <div className="my-6 rounded-lg border-2 border-red-300 bg-red-50 p-4 dark:border-red-800 dark:bg-red-900/20">
        <p className="font-semibold text-red-800 dark:text-red-200">
          Error: Example module is undefined &quot;{from}&quot;
        </p>
      </div>
    )
  }

  const { examples, metadata } = exampleModule

  if (!examples) {
    return (
      <div className="my-6 rounded-lg border-2 border-yellow-300 bg-yellow-50 p-4 dark:border-yellow-800 dark:bg-yellow-900/20">
        <p className="font-semibold text-yellow-800 dark:text-yellow-200">
          Warning: No examples found in &quot;{from}&quot;
        </p>
        <p className="mt-2 text-sm text-yellow-700 dark:text-yellow-300">
          Make sure the file exports an <code>examples</code> object.
        </p>
      </div>
    )
  }

  // Parse frameworks to show
  const frameworksToShow = frameworks.split(',').map((f) => f.trim()).filter(Boolean)

  // Filter examples to only show requested frameworks
  const availableExamples = frameworksToShow
    .map((framework) => examples[framework])
    .filter(Boolean)

  if (availableExamples.length === 0) {
    return (
      <div className="my-6 rounded-lg border-2 border-yellow-300 bg-yellow-50 p-4 dark:border-yellow-800 dark:bg-yellow-900/20">
        <p className="font-semibold text-yellow-800 dark:text-yellow-200">
          Warning: No matching frameworks found
        </p>
        <p className="mt-2 text-sm text-yellow-700 dark:text-yellow-300">
          Requested: {frameworksToShow.join(', ')}
          <br />
          Available: {Object.keys(examples).join(', ')}
        </p>
      </div>
    )
  }

  // Determine default language based on default framework
  const defaultLanguage = examples[defaultFramework]?.language || availableExamples[0]?.language || 'javascript'

  return (
    <CodeTabsWithContext
      examples={availableExamples}
      defaultLanguage={defaultLanguage}
      persist={true}
      showLineNumbers={showLineNumbers}
      highlightLines={highlightLines}
      showLines={showLines}
      showCopy={showCopy}
    />
  )
}
