/**
 * Example: create-accounts
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { generateKeyPairSigner } from '@solana/signers';\nimport {\n  getCreateV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, and sendAndConfirm are set up\n// See getting-started for full setup\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet",
  "main": "// Create the onchain accounts (Mint + Metadata + MasterEdition for NFTs)\nconst createIx = await getCreateV1InstructionAsync({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My NFT',\n  uri: 'https://example.com/my-nft.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  tokenStandard: TokenStandard.NonFungible,\n});\n\n// Send the transaction\nawait sendAndConfirm([createIx], [mint, authority]);",
  "output": "console.log('Created NFT accounts');\nconsole.log('Mint:', mint.address);",
  "full": "// [IMPORTS]\nimport { generateKeyPairSigner } from '@solana/signers';\nimport {\n  getCreateV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, and sendAndConfirm are set up\n// See getting-started for full setup\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet\n// [/SETUP]\n\n// [MAIN]\n// Create the onchain accounts (Mint + Metadata + MasterEdition for NFTs)\nconst createIx = await getCreateV1InstructionAsync({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My NFT',\n  uri: 'https://example.com/my-nft.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  tokenStandard: TokenStandard.NonFungible,\n});\n\n// Send the transaction\nawait sendAndConfirm([createIx], [mint, authority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Created NFT accounts');\nconsole.log('Mint:', mint.address);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { generateSigner, percentAmount } from '@metaplex-foundation/umi';\nimport {\n  createV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mint = generateSigner(umi);",
  "main": "// Create the onchain accounts (Mint + Metadata + MasterEdition for NFTs)\nawait createV1(umi, {\n  mint,\n  authority: umi.identity,\n  name: 'My NFT',\n  uri: 'https://example.com/my-nft.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Created NFT accounts');\nconsole.log('Mint:', mint.publicKey);",
  "full": "// [IMPORTS]\nimport { generateSigner, percentAmount } from '@metaplex-foundation/umi';\nimport {\n  createV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mint = generateSigner(umi);\n// [/SETUP]\n\n// [MAIN]\n// Create the onchain accounts (Mint + Metadata + MasterEdition for NFTs)\nawait createV1(umi, {\n  mint,\n  authority: umi.identity,\n  name: 'My NFT',\n  uri: 'https://example.com/my-nft.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Created NFT accounts');\nconsole.log('Mint:', mint.publicKey);\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_token_metadata::{\n    accounts::Metadata,\n    instructions::CreateV1CpiBuilder,\n    types::{PrintSupply, TokenStandard},\n};",
  "setup": "",
  "main": "// 1. every account is specified by a reference to their AccountInfo\n\nlet create_cpi = CreateV1CpiBuilder::new(token_metadata_program_info)\n    .metadata(metadata_info)\n    .mint(mint_info, true)\n    .authority(payer_info)\n    .payer(payer_info)\n    .update_authority(update_authority_info, false)\n    .master_edition(Some(master_edition_info))\n    .system_program(system_program_info)\n    .sysvar_instructions(sysvar_instructions_info)\n    .spl_token_program(spl_token_program_info)\n    .token_standard(TokenStandard::NonFungible)\n    .name(String::from(\"My NFT\"))\n    .uri(uri)\n    .seller_fee_basis_points(550)\n    .token_standard(TokenStandard::NonFungible)\n    .print_supply(PrintSupply::Zero);\n\ncreate_cpi.invoke();",
  "output": "",
  "full": "// [IMPORTS]\nuse mpl_token_metadata::{\n    accounts::Metadata,\n    instructions::CreateV1CpiBuilder,\n    types::{PrintSupply, TokenStandard},\n};\n// [/IMPORTS]\n\n// [MAIN]\n// 1. every account is specified by a reference to their AccountInfo\n\nlet create_cpi = CreateV1CpiBuilder::new(token_metadata_program_info)\n    .metadata(metadata_info)\n    .mint(mint_info, true)\n    .authority(payer_info)\n    .payer(payer_info)\n    .update_authority(update_authority_info, false)\n    .master_edition(Some(master_edition_info))\n    .system_program(system_program_info)\n    .sysvar_instructions(sysvar_instructions_info)\n    .spl_token_program(spl_token_program_info)\n    .token_standard(TokenStandard::NonFungible)\n    .name(String::from(\"My NFT\"))\n    .uri(uri)\n    .seller_fee_basis_points(550)\n    .token_standard(TokenStandard::NonFungible)\n    .print_supply(PrintSupply::Zero);\n\ncreate_cpi.invoke();\n// [/MAIN]\n"
}

export const metadata = {
  title: "create-accounts",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

}
