/**
 * Example: wrap_sol
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  findAssociatedTokenPda,\n  createTokenIfMissing,\n  transferSol,\n  syncNative,\n  mplToolbox,\n} from '@metaplex-foundation/mpl-toolbox'\nimport { WRAPPED_SOL_MINT, genesis } from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey, sol } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));",
  "main": "const userWsolAccount = findAssociatedTokenPda(umi, {\n  owner: umi.identity.publicKey,\n  mint: WRAPPED_SOL_MINT,\n})\n\nawait createTokenIfMissing(umi, {\n  mint: WRAPPED_SOL_MINT,\n  owner: umi.identity.publicKey,\n  token: userWsolAccount,\n})\n  .add(\n    transferSol(umi, {\n      destination: publicKey(userWsolAccount),\n      amount: sol(10),\n    })\n  )\n  .add(syncNative(umi, { account: userWsolAccount }))\n  .sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  findAssociatedTokenPda,\n  createTokenIfMissing,\n  transferSol,\n  syncNative,\n  mplToolbox,\n} from '@metaplex-foundation/mpl-toolbox'\nimport { WRAPPED_SOL_MINT, genesis } from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey, sol } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n// [/SETUP]\n\n// [MAIN]\nconst userWsolAccount = findAssociatedTokenPda(umi, {\n  owner: umi.identity.publicKey,\n  mint: WRAPPED_SOL_MINT,\n})\n\nawait createTokenIfMissing(umi, {\n  mint: WRAPPED_SOL_MINT,\n  owner: umi.identity.publicKey,\n  token: userWsolAccount,\n})\n  .add(\n    transferSol(umi, {\n      destination: publicKey(userWsolAccount),\n      amount: sol(10),\n    })\n  )\n  .add(syncNative(umi, { account: userWsolAccount }))\n  .sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "wrap_sol",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
