/**
 * Example: Read Token Data
 *
 * Fetch fungible token information from the Solana blockchain
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "// npm install @metaplex-foundation/mpl-token-metadata @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\r\nimport { publicKey } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport {\r\n  fetchDigitalAsset,\r\n  mplTokenMetadata\r\n} from '@metaplex-foundation/mpl-token-metadata'",
  "setup": "// Initialize Umi with your RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(mplTokenMetadata())\r\n\r\n// The mint address of the token you want to fetch\r\nconst mintAddress = publicKey('YOUR_TOKEN_MINT_ADDRESS')",
  "main": "// Fetch the token's metadata from the blockchain\r\nconst asset = await fetchDigitalAsset(umi, mintAddress)",
  "output": "console.log('Token Name:', asset.metadata.name)\r\nconsole.log('Token Symbol:', asset.metadata.symbol)\r\nconsole.log('Token URI:', asset.metadata.uri)\r\nconsole.log('Decimals:', asset.mint.decimals)\r\nconsole.log('Supply:', asset.mint.supply)",
  "full": "// [IMPORTS]\r\n// npm install @metaplex-foundation/mpl-token-metadata @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\r\nimport { publicKey } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport {\r\n  fetchDigitalAsset,\r\n  mplTokenMetadata\r\n} from '@metaplex-foundation/mpl-token-metadata'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize Umi with your RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(mplTokenMetadata())\r\n\r\n// The mint address of the token you want to fetch\r\nconst mintAddress = publicKey('YOUR_TOKEN_MINT_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Fetch the token's metadata from the blockchain\r\nconst asset = await fetchDigitalAsset(umi, mintAddress)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Token Name:', asset.metadata.name)\r\nconsole.log('Token Symbol:', asset.metadata.symbol)\r\nconsole.log('Token URI:', asset.metadata.uri)\r\nconsole.log('Decimals:', asset.mint.decimals)\r\nconsole.log('Supply:', asset.mint.supply)\r\n// [/OUTPUT]\r\n"
}

const dasSections = {
  "imports": "// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "// Initialize Umi with a DAS-enabled RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\n// The mint address of the token you want to fetch\r\nconst mintAddress = publicKey('YOUR_TOKEN_MINT_ADDRESS')",
  "main": "// Fetch the asset using DAS API\r\nconst asset = await umi.rpc.getAsset(mintAddress, {\r\n  displayOptions: {\r\n    showFungible: true\r\n  }\r\n})",
  "output": "",
  "full": "// [IMPORTS]\r\n// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize Umi with a DAS-enabled RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\n// The mint address of the token you want to fetch\r\nconst mintAddress = publicKey('YOUR_TOKEN_MINT_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Fetch the asset using DAS API\r\nconst asset = await umi.rpc.getAsset(mintAddress, {\r\n  displayOptions: {\r\n    showFungible: true\r\n  }\r\n})\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Token ID:', asset.id)\r\nconsole.log('Name:', asset.content.metadata?.name)\r\nconsole.log('Symbol:', asset.content.metadata?.symbol)\r\nconsole.log('Interface:', asset.interface)"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "curl -X POST \\\r\n  -H \"Content-Type: application/json\" \\\r\n  -d '{\r\n    \"jsonrpc\": \"2.0\",\r\n    \"id\": 1,\r\n    \"method\": \"getAsset\",\r\n    \"params\": {\r\n      \"id\": \"<Mint Address>\"\r\n    }\r\n  }' \\\r\n  https://api.devnet.solana.com"
}

export const metadata = {
  title: "Read Token Data",
  description: "Fetch fungible token information from the Solana blockchain",
  tags: ['token-metadata', 'fungible', 'spl-token', 'read', 'fetch', 'das-api', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  das: {
    framework: 'DAS',
    language: 'javascript',
    code: dasSections.full,
    sections: dasSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
