/**
 * Example: add-to-collection-as-delegate
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'",
  "setup": "const assetId = publicKey('11111111111111111111111111111111')\nconst collectionId = publicKey('22222222222222222222222222222222')",
  "main": "const asset = await fetchAsset(umi, assetId)\n\n// umi.identity must be in the Collection's UpdateDelegate additionalDelegates\n// AND hold the Asset's update authority (or be in the Asset's UpdateDelegate additionalDelegates)\nawait update(umi, {\n  asset,\n  newCollection: collectionId,\n  newUpdateAuthority: updateAuthority('Collection', [collectionId]),\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset added to collection')",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst assetId = publicKey('11111111111111111111111111111111')\nconst collectionId = publicKey('22222222222222222222222222222222')\n// [/SETUP]\n\n// [MAIN]\nconst asset = await fetchAsset(umi, assetId)\n\n// umi.identity must be in the Collection's UpdateDelegate additionalDelegates\n// AND hold the Asset's update authority (or be in the Asset's UpdateDelegate additionalDelegates)\nawait update(umi, {\n  asset,\n  newCollection: collectionId,\n  newUpdateAuthority: updateAuthority('Collection', [collectionId]),\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset added to collection')\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::{instructions::UpdateV2Builder, types::UpdateAuthority};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "let asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet collection = Pubkey::from_str(\"CollectionAddressHere...\").unwrap();\n\n// Signer must be in the Collection's UpdateDelegate additionalDelegates\n// AND hold the Asset's update authority (or be in its UpdateDelegate additionalDelegates)\nlet update_ix = UpdateV2Builder::new()\n    .asset(asset)\n    .new_collection(Some(collection))\n    .payer(delegate.pubkey())\n    .authority(Some(delegate.pubkey()))\n    .new_update_authority(UpdateAuthority::Collection(collection))\n    .instruction();",
  "output": "println!(\"Asset added to collection\");",
  "full": "// [IMPORTS]\nuse mpl_core::{instructions::UpdateV2Builder, types::UpdateAuthority};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\nlet asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet collection = Pubkey::from_str(\"CollectionAddressHere...\").unwrap();\n\n// Signer must be in the Collection's UpdateDelegate additionalDelegates\n// AND hold the Asset's update authority (or be in its UpdateDelegate additionalDelegates)\nlet update_ix = UpdateV2Builder::new()\n    .asset(asset)\n    .new_collection(Some(collection))\n    .payer(delegate.pubkey())\n    .authority(Some(delegate.pubkey()))\n    .new_update_authority(UpdateAuthority::Collection(collection))\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Asset added to collection\");\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "add-to-collection-as-delegate",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

}
