import { documentationSection } from '@/shared/sections';
import { CommandLineIcon, SparklesIcon } from '@heroicons/react/24/outline';

export const cli = {
  name: 'CLI',
  headline: 'CLI to mint, transfer, and manage assets.',
  description: 'A command line interface for interacting with Metaplex programs — mint, transfer, and manage assets directly from your terminal.',
  skill: true,
  navigationMenuCatergory: 'Dev Tools',
  path: 'dev-tools/cli',
  icon: <CommandLineIcon />,
  github: 'https://github.com/metaplex-foundation/cli/',
  className: 'accent-green',
  primaryCta: {
    disabled: false,
  },
  sections: [
    {
      ...documentationSection('dev-tools/cli'),
      navigation: [
        {
          title: 'Getting Started',
          links: [
            {
              title: 'Introduction',
              href: '/dev-tools/cli',
            },
            {
              title: 'Installation',
              href: '/dev-tools/cli/installation',
            },
          ],
        },
        {
          title: 'Configuration',
          links: [
            {
              title: 'Wallets',
              href: '/dev-tools/cli/config/wallets',
            },
            {
              title: 'Asset-Signer Wallets',
              href: '/dev-tools/cli/config/asset-signer-wallets',
            },
            {
              title: 'RPCs',
              href: '/dev-tools/cli/config/rpcs',
            },
            {
              title: 'Explorer',
              href: '/dev-tools/cli/config/explorer',
            },
          ],
        },
        {
          title: 'Programs',
          links: [
            {
              title: 'Agents',
              href: '/dev-tools/cli/agents',
              children: [
                { title: 'Overview', href: '/dev-tools/cli/agents' },
                { title: 'Register Agent', href: '/dev-tools/cli/agents/register' },
                { title: 'Fetch Agent', href: '/dev-tools/cli/agents/fetch' },
                { title: 'Agent Token', href: '/dev-tools/cli/agents/set-agent-token' },
                { title: 'Executive Delegation', href: '/dev-tools/cli/agents/executive' },
              ],
            },
            {
              title: 'Genesis',
              href: '/dev-tools/cli/genesis',
              children: [
                { title: 'Overview', href: '/dev-tools/cli/genesis' },
                { title: 'Launch (API)', href: '/dev-tools/cli/genesis/launch' },
                { title: 'Create Genesis Account', href: '/dev-tools/cli/genesis/create' },
                { title: 'Bonding Curve', href: '/dev-tools/cli/genesis/bonding-curve' },
                { title: 'Launch Pool', href: '/dev-tools/cli/genesis/launch-pool' },
                { title: 'Presale', href: '/dev-tools/cli/genesis/presale' },
                { title: 'Manage', href: '/dev-tools/cli/genesis/manage' },
              ],
            },
            {
              title: 'Core',
              children: [
                { title: 'Create Asset', href: '/dev-tools/cli/core/create-asset' },
                { title: 'Create Collection', href: '/dev-tools/cli/core/create-collection' },
                { title: 'Update Asset', href: '/dev-tools/cli/core/update-asset' },
                { title: 'Transfer Asset', href: '/dev-tools/cli/core/transfer-asset' },
                { title: 'Burn Asset', href: '/dev-tools/cli/core/burn-asset' },
                { title: 'Fetch Asset or Collection', href: '/dev-tools/cli/core/fetch' },
                { title: 'Add and Update Plugins', href: '/dev-tools/cli/core/plugins' },
                { title: 'Execute', href: '/dev-tools/cli/core/execute' },
              ],
            },
            {
              title: 'Candy Machine',
              href: '/cli/cm',
              children: [
                { title: 'Overview', href: '/cli/cm' },
                { title: 'Create Candy Machine', href: '/cli/cm/create' },
                { title: 'Upload Assets', href: '/cli/cm/upload' },
                { title: 'Insert Items', href: '/cli/cm/insert' },
                { title: 'Validate Cache', href: '/cli/cm/validate' },
                { title: 'Fetch Information', href: '/cli/cm/fetch' },
                { title: 'Withdraw', href: '/cli/cm/withdraw' },
              ],
            },
            {
              title: 'Bubblegum',
              href: '/dev-tools/cli/bubblegum',
              children: [
                { title: 'Overview', href: '/dev-tools/cli/bubblegum' },
                { title: 'Create Tree', href: '/dev-tools/cli/bubblegum/create-tree' },
                { title: 'List Trees', href: '/dev-tools/cli/bubblegum/list-trees' },
                { title: 'Create Compressed NFT', href: '/dev-tools/cli/bubblegum/create-cnft' },
                { title: 'Fetch Compressed NFT', href: '/dev-tools/cli/bubblegum/fetch-cnft' },
                { title: 'Update Compressed NFT', href: '/dev-tools/cli/bubblegum/update-cnft' },
                { title: 'Transfer Compressed NFT', href: '/dev-tools/cli/bubblegum/transfer-cnft' },
                { title: 'Burn Compressed NFT', href: '/dev-tools/cli/bubblegum/burn-cnft' },
              ],
            },
          ],
        },
        {
          title: 'Toolbox',
          links: [
            {
              title: 'Token',
              children: [
                { title: 'Create', href: '/dev-tools/cli/toolbox/token-create' },
                { title: 'Mint', href: '/dev-tools/cli/toolbox/token-mint' },
                { title: 'Transfer', href: '/dev-tools/cli/toolbox/token-transfer' },
                { title: 'Add Metadata', href: '/dev-tools/cli/toolbox/add-metadata-to-token' },
                { title: 'Update Metadata', href: '/dev-tools/cli/toolbox/update-token-metadata' },
              ],
            },
            {
              title: 'SOL',
              children: [
                { title: 'Airdrop', href: '/dev-tools/cli/toolbox/sol-airdrop' },
                { title: 'Balance', href: '/dev-tools/cli/toolbox/sol-balance' },
                { title: 'Transfer', href: '/dev-tools/cli/toolbox/sol-transfer' },
                { title: 'Wrap', href: '/dev-tools/cli/toolbox/sol-wrap' },
                { title: 'Unwrap', href: '/dev-tools/cli/toolbox/sol-unwrap' },
              ],
            },
            {
              title: 'Storage',
              children: [
                { title: 'Upload', href: '/dev-tools/cli/toolbox/storage-upload' },
                { title: 'Balance', href: '/dev-tools/cli/toolbox/storage-balance' },
                { title: 'Fund', href: '/dev-tools/cli/toolbox/storage-fund' },
                { title: 'Withdraw', href: '/dev-tools/cli/toolbox/storage-withdraw' },
              ],
            },
            {
              title: 'Address Lookup Tables',
              children: [
                { title: 'Create', href: '/dev-tools/cli/toolbox/lut-create' },
                { title: 'Fetch', href: '/dev-tools/cli/toolbox/lut-fetch' },
                { title: 'Deactivate', href: '/dev-tools/cli/toolbox/lut-deactivate' },
                { title: 'Close', href: '/dev-tools/cli/toolbox/lut-close' },
              ],
            },
            {
              title: 'Scaffolding',
              children: [
                { title: 'Program Template', href: '/dev-tools/cli/toolbox/scaffolding-program' },
                { title: 'Website Template', href: '/dev-tools/cli/toolbox/scaffolding-website' },
              ],
            },
            {
              title: 'Utilities',
              children: [
                { title: 'Rent', href: '/dev-tools/cli/toolbox/rent' },
                { title: 'Transaction', href: '/dev-tools/cli/toolbox/transaction' },
              ],
            },
          ],
        },
      ],
    },
  ],
  localizedNavigation: {
    en: {
      headline: 'CLI to mint, transfer, and manage assets.',
      description: 'A command line interface for interacting with Metaplex programs — mint, transfer, and manage assets directly from your terminal.',
      sections: {
        'Getting Started': 'Getting Started',
        'Configuration': 'Configuration',
        'Programs': 'Programs',
        'Toolbox': 'Toolbox'
      },
      links: {
        'Agents': 'Agents',
        'Genesis': 'Genesis',
        'Core': 'Core',
        'Candy Machine': 'Candy Machine',
        'Bubblegum': 'Bubblegum',
        'Overview': 'Overview',
        'Installation': 'Installation',
        'Wallets': 'Wallets',
        'Asset-Signer Wallets': 'Asset-Signer Wallets',
        'RPCs': 'RPCs',
        'Explorer': 'Explorer',
        'Execute': 'Execute',
        'Launch (API)': 'Launch (API)',
        'Create Genesis Account': 'Create Genesis Account',
        'Launch Pool': 'Launch Pool',
        'Presale': 'Presale',
        'Bonding Curve': 'Bonding Curve',
        'Manage': 'Manage',
        'Register Agent': 'Register Agent',
        'Fetch Agent': 'Fetch Agent',
        'Agent Token': 'Agent Token',
        'Executive Delegation': 'Executive Delegation',
        'Create Tree': 'Create Tree',
        'List Trees': 'List Trees',
        'Create Compressed NFT': 'Create Compressed NFT',
        'Fetch Compressed NFT': 'Fetch Compressed NFT',
        'Update Compressed NFT': 'Update Compressed NFT',
        'Transfer Compressed NFT': 'Transfer Compressed NFT',
        'Burn Compressed NFT': 'Burn Compressed NFT',
        'Token': 'Token',
        'SOL': 'SOL',
        'Storage': 'Storage',
        'Address Lookup Tables': 'Address Lookup Tables',
        'Scaffolding': 'Scaffolding',
        'Utilities': 'Utilities',
        'Create': 'Create',
        'Mint': 'Mint',
        'Transfer': 'Transfer',
        'Airdrop': 'Airdrop',
        'Balance': 'Balance',
        'Wrap': 'Wrap',
        'Unwrap': 'Unwrap',
        'Upload': 'Upload',
        'Fund': 'Fund',
        'Withdraw': 'Withdraw',
        'Fetch': 'Fetch',
        'Deactivate': 'Deactivate',
        'Close': 'Close',
        'Program Template': 'Program Template',
        'Website Template': 'Website Template',
        'Rent': 'Rent',
        'Transaction': 'Transaction',
        'Add Metadata': 'Add Metadata',
        'Update Metadata': 'Update Metadata'
      }
    },
    ja: {
      headline: 'MPLX CLI',
      description: 'MPLXエコシステム用のCLI',
      sections: {
        'Getting Started': '紹介',
        'Configuration': '設定',
        'Programs': 'プログラム',
        'Toolbox': 'ツールボックス'
      },
      links: {
        'Agents': 'エージェント',
        'Genesis': 'Genesis',
        'Core': 'Core',
        'Candy Machine': 'Candy Machine',
        'Bubblegum': 'Bubblegum',
        'Overview': '概要',
        'Installation': 'インストール',
        'Wallets': 'ウォレット',
        'Asset-Signer Wallets': 'アセット署名者ウォレット',
        'RPCs': 'RPC',
        'Explorer': 'エクスプローラー',
        'Execute': 'Execute',
        'Launch (API)': 'ローンチ（API）',
        'Create Genesis Account': 'Genesisアカウント作成',
        'Launch Pool': 'ローンチプール',
        'Presale': 'プレセール',
        'Bonding Curve': 'ボンディングカーブ',
        'Manage': '管理',
        'Register Agent': 'エージェント登録',
        'Fetch Agent': 'エージェント取得',
        'Agent Token': 'エージェントトークン',
        'Executive Delegation': 'エグゼクティブ委任',
        'Create Tree': 'ツリー作成',
        'List Trees': 'ツリー一覧',
        'Create Compressed NFT': '圧縮NFT作成',
        'Fetch Compressed NFT': '圧縮NFT取得',
        'Update Compressed NFT': '圧縮NFT更新',
        'Transfer Asset': 'アセットを転送',
        'Transfer Compressed NFT': '圧縮NFT転送',
        'Burn Compressed NFT': '圧縮NFTバーン',
        'Token': 'トークン',
        'SOL': 'SOL',
        'Storage': 'ストレージ',
        'Address Lookup Tables': 'アドレスルックアップテーブル',
        'Scaffolding': 'スキャフォールディング',
        'Utilities': 'ユーティリティ',
        'Create': '作成',
        'Mint': 'ミント',
        'Transfer': '転送',
        'Airdrop': 'エアドロップ',
        'Balance': '残高',
        'Wrap': 'ラップ',
        'Unwrap': 'アンラップ',
        'Upload': 'アップロード',
        'Fund': '入金',
        'Withdraw': '出金',
        'Fetch': '取得',
        'Deactivate': '無効化',
        'Close': 'クローズ',
        'Program Template': 'プログラムテンプレート',
        'Website Template': 'ウェブサイトテンプレート',
        'Rent': 'レント',
        'Transaction': 'トランザクション',
        'Add Metadata': 'メタデータ追加',
        'Update Metadata': 'メタデータ更新'
      }
    },
    ko: {
      headline: 'MPLX CLI',
      description: 'MPLX 에코시스템을 위한 CLI',
      sections: {
        'Getting Started': '소개',
        'Configuration': '구성',
        'Programs': '프로그램',
        'Toolbox': '툴박스'
      },
      links: {
        'Agents': '에이전트',
        'Genesis': 'Genesis',
        'Core': 'Core',
        'Candy Machine': 'Candy Machine',
        'Bubblegum': 'Bubblegum',
        'Overview': '개요',
        'Installation': '설치',
        'Wallets': '지갑',
        'Asset-Signer Wallets': '에셋 서명자 지갑',
        'RPCs': 'RPC',
        'Explorer': '익스플로러',
        'Execute': 'Execute',
        'Launch (API)': '런치 (API)',
        'Create Genesis Account': 'Genesis 계정 생성',
        'Launch Pool': '런치 풀',
        'Presale': '프리세일',
        'Bonding Curve': '본딩 커브',
        'Manage': '관리',
        'Register Agent': '에이전트 등록',
        'Fetch Agent': '에이전트 조회',
        'Agent Token': '에이전트 토큰',
        'Executive Delegation': '실행 위임',
        'Create Tree': '트리 생성',
        'List Trees': '트리 목록',
        'Create Compressed NFT': '압축 NFT 생성',
        'Fetch Compressed NFT': '압축 NFT 조회',
        'Update Compressed NFT': '압축 NFT 업데이트',
        'Transfer Asset': '에셋 전송',
        'Transfer Compressed NFT': '압축 NFT 전송',
        'Burn Compressed NFT': '압축 NFT 소각',
        'Token': '토큰',
        'SOL': 'SOL',
        'Storage': '스토리지',
        'Address Lookup Tables': '주소 조회 테이블',
        'Scaffolding': '스캐폴딩',
        'Utilities': '유틸리티',
        'Create': '생성',
        'Mint': '민트',
        'Transfer': '전송',
        'Airdrop': '에어드롭',
        'Balance': '잔액',
        'Wrap': '래핑',
        'Unwrap': '언래핑',
        'Upload': '업로드',
        'Fund': '충전',
        'Withdraw': '출금',
        'Fetch': '조회',
        'Deactivate': '비활성화',
        'Close': '닫기',
        'Program Template': '프로그램 템플릿',
        'Website Template': '웹사이트 템플릿',
        'Rent': '렌트',
        'Transaction': '트랜잭션',
        'Add Metadata': '메타데이터 추가',
        'Update Metadata': '메타데이터 업데이트'
      }
    },
    zh: {
      headline: 'MPLX CLI',
      description: 'MPLX生态系统的命令行工具',
      sections: {
        'Getting Started': '快速入门',
        'Configuration': '配置',
        'Programs': '程序',
        'Toolbox': '工具箱'
      },
      links: {
        'Agents': '代理',
        'Genesis': 'Genesis',
        'Core': 'Core',
        'Candy Machine': 'Candy Machine',
        'Bubblegum': 'Bubblegum',
        'Introduction': '简介',
        'Overview': '概述',
        'Installation': '安装',
        'Wallets': '钱包',
        'Asset-Signer Wallets': '资产签名者钱包',
        'RPCs': 'RPC',
        'Explorer': '浏览器',
        'Execute': 'Execute',
        'Launch (API)': '启动（API）',
        'Create Genesis Account': '创建Genesis账户',
        'Launch Pool': '发行池',
        'Presale': '预售',
        'Bonding Curve': '债券曲线',
        'Manage': '管理',
        'Register Agent': '注册代理',
        'Fetch Agent': '查询代理',
        'Agent Token': '代理代币',
        'Executive Delegation': '执行委托',
        'Create Asset': '创建资产',
        'Create Collection': '创建合集',
        'Update Asset': '更新资产',
        'Transfer Asset': '转移资产',
        'Burn Asset': '销毁资产',
        'Fetch Asset or Collection': '获取资产或合集',
        'Add and Update Plugins': '添加和更新插件',
        'Create Candy Machine': '创建Candy Machine',
        'Upload Assets': '上传资产',
        'Insert Items': '插入项目',
        'Validate Cache': '验证缓存',
        'Fetch Information': '获取信息',
        'Withdraw': '提取',
        'Create Tree': '创建树',
        'List Trees': '树列表',
        'Create Compressed NFT': '创建压缩NFT',
        'Fetch Compressed NFT': '获取压缩NFT',
        'Update Compressed NFT': '更新压缩NFT',
        'Transfer Compressed NFT': '转移压缩NFT',
        'Burn Compressed NFT': '销毁压缩NFT',
        'Token': '代币',
        'SOL': 'SOL',
        'Storage': '存储',
        'Address Lookup Tables': '地址查找表',
        'Scaffolding': '脚手架',
        'Utilities': '实用工具',
        'Create': '创建',
        'Mint': '铸造',
        'Transfer': '转移',
        'Airdrop': '空投',
        'Balance': '余额',
        'Wrap': '包装',
        'Unwrap': '解包',
        'Upload': '上传',
        'Fund': '充值',
        'Withdraw': '提取',
        'Fetch': '获取',
        'Deactivate': '停用',
        'Close': '关闭',
        'Program Template': '程序模板',
        'Website Template': '网站模板',
        'Rent': '租金',
        'Transaction': '交易',
        'Add Metadata': '添加元数据',
        'Update Metadata': '更新元数据'
      }
    }
  }
}
