/**
 * Example: Mint an Agent on Devnet
 *
 * A test agent on devnet
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mintAndSubmitAgent, mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.devnet.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "const result = await mintAndSubmitAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  network: 'solana-devnet',\n  name: 'Test Agent',\n  uri: 'https://example.com/test-metadata.json',\n  agentMetadata: {\n    type: 'agent',\n    name: 'Test Agent',\n    description: 'A test agent on devnet',\n    services: [],\n    registrations: [],\n    supportedTrust: [],\n  },\n})\n\nconsole.log('Asset address:', result.assetAddress)\nconsole.log('Transaction signature:', result.signature)",
  "output": "// Asset address: <base58 address>\n// Transaction signature: <base58 signature>",
  "full": "// [IMPORTS]\nimport { mintAndSubmitAgent, mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\nconst result = await mintAndSubmitAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  network: 'solana-devnet',\n  name: 'Test Agent',\n  uri: 'https://example.com/test-metadata.json',\n  agentMetadata: {\n    type: 'agent',\n    name: 'Test Agent',\n    description: 'A test agent on devnet',\n    services: [],\n    registrations: [],\n    supportedTrust: [],\n  },\n})\n\nconsole.log('Asset address:', result.assetAddress)\nconsole.log('Transaction signature:', result.signature)\n// [/MAIN]\n\n// [OUTPUT]\n// Asset address: <base58 address>\n// Transaction signature: <base58 signature>\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Mint an Agent on Devnet",
  description: "A test agent on devnet",
  tags: ['agents', 'devnet', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
