/**
 * Example: transfer_claim_schedule_recipient_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  transferRecipientClaimScheduleBucketV2,\n} from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst vestingBucket = publicKey('CLAIM_SCHEDULE_BUCKET_PDA')",
  "main": "await transferRecipientClaimScheduleBucketV2(umi, {\n  genesisAccount,\n  bucket: vestingBucket,\n  signer: umi.identity,\n  newRecipient: publicKey('NEW_RECIPIENT'),\n  padding: Array(7).fill(0),\n}).sendAndConfirm(umi)",
  "output": "// Future claims are sent to the new stored recipient.",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  transferRecipientClaimScheduleBucketV2,\n} from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst vestingBucket = publicKey('CLAIM_SCHEDULE_BUCKET_PDA')\n// [/SETUP]\n\n// [MAIN]\nawait transferRecipientClaimScheduleBucketV2(umi, {\n  genesisAccount,\n  bucket: vestingBucket,\n  signer: umi.identity,\n  newRecipient: publicKey('NEW_RECIPIENT'),\n  padding: Array(7).fill(0),\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// Future claims are sent to the new stored recipient.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "transfer_claim_schedule_recipient_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
