/**
 * Example: read_agent_das_get
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('<DAS_ENDPOINT>').use(dasApi())",
  "main": "const asset = await umi.rpc.getAsset(publicKey('AGENT_CORE_ASSET_ADDRESS'))\n\nif (asset.is_agent) {\n  console.log('Agent wallet (asset_signer):', asset.asset_signer)\n  console.log('Canonical token mint:', asset.agent_token ?? 'not set')\n} else {\n  console.log('Core asset is not a registered agent')\n}",
  "output": "// Agent wallet (asset_signer): 6ttUwc5VVmHeVKTddB6XM5vQgBMfw62DThuoiVEufVZq\n// Canonical token mint: not set",
  "full": "// [IMPORTS]\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<DAS_ENDPOINT>').use(dasApi())\n// [/SETUP]\n\n// [MAIN]\nconst asset = await umi.rpc.getAsset(publicKey('AGENT_CORE_ASSET_ADDRESS'))\n\nif (asset.is_agent) {\n  console.log('Agent wallet (asset_signer):', asset.asset_signer)\n  console.log('Canonical token mint:', asset.agent_token ?? 'not set')\n} else {\n  console.log('Core asset is not a registered agent')\n}\n// [/MAIN]\n\n// [OUTPUT]\n// Agent wallet (asset_signer): 6ttUwc5VVmHeVKTddB6XM5vQgBMfw62DThuoiVEufVZq\n// Canonical token mint: not set\n// [/OUTPUT]\n"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "curl -X POST <DAS_ENDPOINT> \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"jsonrpc\": \"2.0\",\n    \"id\": 1,\n    \"method\": \"getAsset\",\n    \"params\": { \"id\": \"AGENT_CORE_ASSET_ADDRESS\" }\n  }'\n"
}

export const metadata = {
  title: "read_agent_das_get",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
