/**
 * Example: Transfer an Asset
 *
 * Transfer ownership of an NFT asset to a new owner
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { transfer } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())",
  "main": "// Transfer an existing NFT asset to a new owner\nconst result = await transfer(umi, {\n  asset: publicKey('AssetAddressHere...'),\n  newOwner: publicKey('RecipientAddressHere...'),\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset transferred:', result.signature)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { transfer } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n// [/SETUP]\n\n// [MAIN]\n// Transfer an existing NFT asset to a new owner\nconst result = await transfer(umi, {\n  asset: publicKey('AssetAddressHere...'),\n  newOwner: publicKey('RecipientAddressHere...'),\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset transferred:', result.signature)\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::instructions::TransferV1;\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Asset and recipient addresses\nlet asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet new_owner = Pubkey::from_str(\"RecipientAddressHere...\").unwrap();\n\n// Transfer an existing NFT asset to a new owner\nlet transfer_ix = TransferV1 {\n    asset,\n    new_owner,\n    ..Default::default()\n};\n\nlet instruction = transfer_ix.instruction();",
  "output": "println!(\"Transfer instruction created\");",
  "full": "// [IMPORTS]\nuse mpl_core::instructions::TransferV1;\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\n// Asset and recipient addresses\nlet asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet new_owner = Pubkey::from_str(\"RecipientAddressHere...\").unwrap();\n\n// Transfer an existing NFT asset to a new owner\nlet transfer_ix = TransferV1 {\n    asset,\n    new_owner,\n    ..Default::default()\n};\n\nlet instruction = transfer_ix.instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Transfer instruction created\");\n// [/OUTPUT]\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;",
  "setup": "",
  "main": "declare_id!(\"Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS\");\n\n#[program]\npub mod transfer_asset {\n    use super::*;\n\n    // Transfer an existing NFT asset to a new owner\n    pub fn transfer(\n        ctx: Context<TransferAsset>\n    ) -> Result<()> {\n        let asset = &mut ctx.accounts.asset;\n\n        // Verify current owner\n        require!(\n            asset.owner == ctx.accounts.current_owner.key(),\n            ErrorCode::Unauthorized\n        );\n\n        // Transfer ownership\n        asset.owner = ctx.accounts.new_owner.key();\n\n        msg!(\"Asset transferred to: {}\", asset.owner);\n        Ok(())\n    }\n}\n\n#[derive(Accounts)]\npub struct TransferAsset<'info> {\n    #[account(mut)]\n    pub asset: Account<'info, Asset>,\n    pub current_owner: Signer<'info>,\n    /// CHECK: New owner can be any account\n    pub new_owner: AccountInfo<'info>,\n}\n\n#[account]\npub struct Asset {\n    pub name: String,\n    pub uri: String,\n    pub owner: Pubkey,\n}\n\n#[error_code]\npub enum ErrorCode {\n    #[msg(\"Unauthorized: You are not the owner of this asset\")]\n    Unauthorized,\n}",
  "output": "",
  "full": "// [IMPORTS]\nuse anchor_lang::prelude::*;\n// [/IMPORTS]\n\n// [MAIN]\ndeclare_id!(\"Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS\");\n\n#[program]\npub mod transfer_asset {\n    use super::*;\n\n    // Transfer an existing NFT asset to a new owner\n    pub fn transfer(\n        ctx: Context<TransferAsset>\n    ) -> Result<()> {\n        let asset = &mut ctx.accounts.asset;\n\n        // Verify current owner\n        require!(\n            asset.owner == ctx.accounts.current_owner.key(),\n            ErrorCode::Unauthorized\n        );\n\n        // Transfer ownership\n        asset.owner = ctx.accounts.new_owner.key();\n\n        msg!(\"Asset transferred to: {}\", asset.owner);\n        Ok(())\n    }\n}\n\n#[derive(Accounts)]\npub struct TransferAsset<'info> {\n    #[account(mut)]\n    pub asset: Account<'info, Asset>,\n    pub current_owner: Signer<'info>,\n    /// CHECK: New owner can be any account\n    pub new_owner: AccountInfo<'info>,\n}\n\n#[account]\npub struct Asset {\n    pub name: String,\n    pub uri: String,\n    pub owner: Pubkey,\n}\n\n#[error_code]\npub enum ErrorCode {\n    #[msg(\"Unauthorized: You are not the owner of this asset\")]\n    Unauthorized,\n}\n// [/MAIN]\n"
}

export const metadata = {
  title: "Transfer an Asset",
  description: "Transfer ownership of an NFT asset to a new owner",
  tags: ['core', 'nft', 'transfer', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
