/**
 * Example: upload-assets
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createGenericFile } from '@metaplex-foundation/umi';\nimport { readFile } from 'fs/promises';",
  "setup": "// Assuming umi is set up with irysUploader plugin\n// See getting-started for full setup",
  "main": "// Read image from local filesystem\nconst imageFile = await readFile('./my-nft-image.png');\nconst umiImageFile = createGenericFile(imageFile, 'my-nft-image.png', {\n  contentType: 'image/png',\n});\n\n// Upload image to Arweave via Irys\nconst [imageUri] = await umi.uploader.upload([umiImageFile]);",
  "output": "console.log('Image URI:', imageUri);",
  "full": "// [IMPORTS]\nimport { createGenericFile } from '@metaplex-foundation/umi';\nimport { readFile } from 'fs/promises';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with irysUploader plugin\n// See getting-started for full setup\n// [/SETUP]\n\n// [MAIN]\n// Read image from local filesystem\nconst imageFile = await readFile('./my-nft-image.png');\nconst umiImageFile = createGenericFile(imageFile, 'my-nft-image.png', {\n  contentType: 'image/png',\n});\n\n// Upload image to Arweave via Irys\nconst [imageUri] = await umi.uploader.upload([umiImageFile]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Image URI:', imageUri);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "upload-assets",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
