/**
 * Example: api_easy_mode
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  createAndRegisterLaunch,\n  CreateLaunchInput,\n} from '@metaplex-foundation/genesis'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { genesis } from '@metaplex-foundation/genesis'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(genesis())\n\n// umi.use(keypairIdentity(myKeypair));",
  "main": "const input: CreateLaunchInput = {\n  wallet: umi.identity.publicKey,\n  token: {\n    name: 'My Token',\n    symbol: 'MTK',\n    image: 'https://gateway.irys.xyz/...',\n  },\n  launchType: 'project',\n  launch: {\n    launchpool: {\n      tokenAllocation: 500_000_000,\n      depositStartTime: new Date(Date.now() + 48 * 60 * 60 * 1000),\n      raiseGoal: 200,\n      raydiumLiquidityBps: 5000,\n      fundsRecipient: umi.identity.publicKey,\n    },\n  },\n};\n\nconst result = await createAndRegisterLaunch(umi, input);\nconsole.log(`Launch live at: ${result.launch.link}`);",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  createAndRegisterLaunch,\n  CreateLaunchInput,\n} from '@metaplex-foundation/genesis'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { genesis } from '@metaplex-foundation/genesis'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(genesis())\n\n// umi.use(keypairIdentity(myKeypair));\n// [/SETUP]\n\n// [MAIN]\nconst input: CreateLaunchInput = {\n  wallet: umi.identity.publicKey,\n  token: {\n    name: 'My Token',\n    symbol: 'MTK',\n    image: 'https://gateway.irys.xyz/...',\n  },\n  launchType: 'project',\n  launch: {\n    launchpool: {\n      tokenAllocation: 500_000_000,\n      depositStartTime: new Date(Date.now() + 48 * 60 * 60 * 1000),\n      raiseGoal: 200,\n      raydiumLiquidityBps: 5000,\n      fundsRecipient: umi.identity.publicKey,\n    },\n  },\n};\n\nconst result = await createAndRegisterLaunch(umi, input);\nconsole.log(`Launch live at: ${result.launch.link}`);\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "api_easy_mode",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
