/**
 * Example: Mint an Agent with Manual Signing
 *
 * An autonomous trading agent
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  mintAgent,\n  signAndSendAgentTransaction,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "// Step 1: Call the API — returns the unsigned transaction and the pre-computed asset address\nconst mintResult = await mintAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  name: 'My AI Agent',\n  uri: 'https://example.com/agent-metadata.json',\n  agentMetadata: {\n    type: 'agent',\n    name: 'My AI Agent',\n    description: 'An autonomous trading agent',\n    services: [\n      { name: 'trading', endpoint: 'https://myagent.ai/trade' },\n      { name: 'analysis', endpoint: 'https://myagent.ai/analyze' },\n    ],\n    registrations: [\n      { agentId: 'agent-123', agentRegistry: 'my-registry' },\n    ],\n    supportedTrust: ['tee'],\n  },\n})\n\nconsole.log('Asset address:', mintResult.assetAddress)\n\n// Step 2: Sign and send using the SDK helper\nconst signature = await signAndSendAgentTransaction(umi, mintResult)\nconsole.log('Confirmed signature:', signature)",
  "output": "// Asset address: <base58 address>\n// Confirmed signature: <base58 signature>",
  "full": "// [IMPORTS]\nimport {\n  mintAgent,\n  signAndSendAgentTransaction,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\n// Step 1: Call the API — returns the unsigned transaction and the pre-computed asset address\nconst mintResult = await mintAgent(umi, {}, {\n  wallet: umi.identity.publicKey,\n  name: 'My AI Agent',\n  uri: 'https://example.com/agent-metadata.json',\n  agentMetadata: {\n    type: 'agent',\n    name: 'My AI Agent',\n    description: 'An autonomous trading agent',\n    services: [\n      { name: 'trading', endpoint: 'https://myagent.ai/trade' },\n      { name: 'analysis', endpoint: 'https://myagent.ai/analyze' },\n    ],\n    registrations: [\n      { agentId: 'agent-123', agentRegistry: 'my-registry' },\n    ],\n    supportedTrust: ['tee'],\n  },\n})\n\nconsole.log('Asset address:', mintResult.assetAddress)\n\n// Step 2: Sign and send using the SDK helper\nconst signature = await signAndSendAgentTransaction(umi, mintResult)\nconsole.log('Confirmed signature:', signature)\n// [/MAIN]\n\n// [OUTPUT]\n// Asset address: <base58 address>\n// Confirmed signature: <base58 signature>\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Mint an Agent with Manual Signing",
  description: "An autonomous trading agent",
  tags: ['agents', 'mint', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
