/**
 * Example: delegate-standard-lock
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getLockV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, standardDelegate, and tokenOwner are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address",
  "main": "// Lock (freeze) as Standard delegate\nconst lockIx = await getLockV1InstructionAsync({\n  mint: mintAddress,\n  authority: standardDelegate,\n  payer: standardDelegate,\n  tokenOwner,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [lockIx],\n  payer: standardDelegate,\n});",
  "output": "console.log('Asset locked (frozen) by Standard delegate');",
  "full": "// [IMPORTS]\nimport {\n  getLockV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, standardDelegate, and tokenOwner are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address\n// [/SETUP]\n\n// [MAIN]\n// Lock (freeze) as Standard delegate\nconst lockIx = await getLockV1InstructionAsync({\n  mint: mintAddress,\n  authority: standardDelegate,\n  payer: standardDelegate,\n  tokenOwner,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [lockIx],\n  payer: standardDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset locked (frozen) by Standard delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { lockV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, mint, and standardDelegate are set up",
  "main": "await lockV1(umi, {\n  mint,\n  authority: standardDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Asset locked (frozen) by Standard delegate');",
  "full": "// [IMPORTS]\nimport { lockV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, mint, and standardDelegate are set up\n// [/SETUP]\n\n// [MAIN]\nawait lockV1(umi, {\n  mint,\n  authority: standardDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset locked (frozen) by Standard delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-standard-lock",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
