/**
 * Example: Error Handling
 *
 * Use the SDK
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  mintAgent,\n  isAgentApiError,\n  isAgentApiNetworkError,\n  isAgentValidationError,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "try {\n  const result = await mintAgent(umi, {}, input)\n} catch (err) {\n  if (isAgentValidationError(err)) {\n    // Client-side validation failed before the API was called\n    console.error(`Validation error on field \"${err.field}\": ${err.message}`)\n  } else if (isAgentApiNetworkError(err)) {\n    // Could not reach the API endpoint\n    console.error('Network error:', err.message, err.cause)\n  } else if (isAgentApiError(err)) {\n    // API responded with a non-2xx status\n    console.error(`API error (${err.statusCode}): ${err.message}`)\n    console.error('Response body:', err.responseBody)\n  } else {\n    throw err\n  }\n}",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  mintAgent,\n  isAgentApiError,\n  isAgentApiNetworkError,\n  isAgentValidationError,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\ntry {\n  const result = await mintAgent(umi, {}, input)\n} catch (err) {\n  if (isAgentValidationError(err)) {\n    // Client-side validation failed before the API was called\n    console.error(`Validation error on field \"${err.field}\": ${err.message}`)\n  } else if (isAgentApiNetworkError(err)) {\n    // Could not reach the API endpoint\n    console.error('Network error:', err.message, err.cause)\n  } else if (isAgentApiError(err)) {\n    // API responded with a non-2xx status\n    console.error(`API error (${err.statusCode}): ${err.message}`)\n    console.error('Response body:', err.responseBody)\n  } else {\n    throw err\n  }\n}\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Error Handling",
  description: "Use the SDK",
  tags: ['agents', 'error-handling', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
