/**
 * Example: print-edition
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { generateKeyPairSigner } from '@solana/kit';\nimport {\n  getPrintV1InstructionAsync,\n  fetchMasterEdition,\n  findMasterEditionPda,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, originalOwner are set up\n\nconst masterEditionMintAddress = 'masterEditionMintAddress...';\nconst ownerOfThePrintedEdition = 'ownerAddress...';\nconst editionMint = await generateKeyPairSigner();",
  "main": "// Fetch the master edition account to mint the next edition number\nconst [masterEditionPda] = await findMasterEditionPda({ mint: masterEditionMintAddress });\nconst masterEdition = await fetchMasterEdition(rpc, masterEditionPda);\n\n// Print a new edition\nconst printIx = await getPrintV1InstructionAsync({\n  masterTokenAccountOwner: originalOwner,\n  masterEditionMint: masterEditionMintAddress,\n  editionMint,\n  editionTokenAccountOwner: ownerOfThePrintedEdition,\n  editionNumber: masterEdition.data.supply + 1n,\n  tokenStandard: TokenStandard.NonFungible,\n  payer: originalOwner,\n});\n\nawait sendAndConfirm({\n  instructions: [printIx],\n  payer: originalOwner,\n});",
  "output": "console.log('Edition printed:', editionMint.address);",
  "full": "// [IMPORTS]\nimport { generateKeyPairSigner } from '@solana/kit';\nimport {\n  getPrintV1InstructionAsync,\n  fetchMasterEdition,\n  findMasterEditionPda,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, originalOwner are set up\n\nconst masterEditionMintAddress = 'masterEditionMintAddress...';\nconst ownerOfThePrintedEdition = 'ownerAddress...';\nconst editionMint = await generateKeyPairSigner();\n// [/SETUP]\n\n// [MAIN]\n// Fetch the master edition account to mint the next edition number\nconst [masterEditionPda] = await findMasterEditionPda({ mint: masterEditionMintAddress });\nconst masterEdition = await fetchMasterEdition(rpc, masterEditionPda);\n\n// Print a new edition\nconst printIx = await getPrintV1InstructionAsync({\n  masterTokenAccountOwner: originalOwner,\n  masterEditionMint: masterEditionMintAddress,\n  editionMint,\n  editionTokenAccountOwner: ownerOfThePrintedEdition,\n  editionNumber: masterEdition.data.supply + 1n,\n  tokenStandard: TokenStandard.NonFungible,\n  payer: originalOwner,\n});\n\nawait sendAndConfirm({\n  instructions: [printIx],\n  payer: originalOwner,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Edition printed:', editionMint.address);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { generateSigner } from '@metaplex-foundation/umi';\nimport {\n  printV1,\n  fetchMasterEditionFromSeeds,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, masterEditionMint, originalOwner, and ownerOfThePrintedEdition are set up\n\nconst editionMint = generateSigner(umi);",
  "main": "// (Optional) Fetch the master edition account to mint the next edition number.\nconst masterEdition = await fetchMasterEditionFromSeeds(umi, {\n  mint: masterEditionMint,\n});\n\nawait printV1(umi, {\n  masterTokenAccountOwner: originalOwner,\n  masterEditionMint,\n  editionMint,\n  editionTokenAccountOwner: ownerOfThePrintedEdition,\n  editionNumber: masterEdition.supply + 1n,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Edition printed:', editionMint.publicKey);",
  "full": "// [IMPORTS]\nimport { generateSigner } from '@metaplex-foundation/umi';\nimport {\n  printV1,\n  fetchMasterEditionFromSeeds,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, masterEditionMint, originalOwner, and ownerOfThePrintedEdition are set up\n\nconst editionMint = generateSigner(umi);\n// [/SETUP]\n\n// [MAIN]\n// (Optional) Fetch the master edition account to mint the next edition number.\nconst masterEdition = await fetchMasterEditionFromSeeds(umi, {\n  mint: masterEditionMint,\n});\n\nawait printV1(umi, {\n  masterTokenAccountOwner: originalOwner,\n  masterEditionMint,\n  editionMint,\n  editionTokenAccountOwner: ownerOfThePrintedEdition,\n  editionNumber: masterEdition.supply + 1n,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Edition printed:', editionMint.publicKey);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "print-edition",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
