/**
 * Example: skip-derive-plugins
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('<ENDPOINT>').use(dasApi())",
  "main": "const assetsByOwner = await das.getAssetsByOwner(umi, {\n  owner: publicKey('<ownerPublicKey>'),\n  skipDerivePlugins: true,\n})",
  "output": "console.log(assetsByOwner)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<ENDPOINT>').use(dasApi())\n// [/SETUP]\n\n// [MAIN]\nconst assetsByOwner = await das.getAssetsByOwner(umi, {\n  owner: publicKey('<ownerPublicKey>'),\n  skipDerivePlugins: true,\n})\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log(assetsByOwner)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "skip-derive-plugins",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
