/**
 * Example: delegate-collection-unverify
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getUnverifyCollectionV1InstructionAsync,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...'); // The item to unverify\nconst collectionMint = address('collectionMintAddress...');",
  "main": "const [metadata] = await findMetadataPda({ mint });\nconst unverifyIx = await getUnverifyCollectionV1InstructionAsync({\n  metadata,\n  collectionMint,\n  authority: collectionDelegate,\n});\n\nawait sendAndConfirm([unverifyIx], [collectionDelegate]);",
  "output": "console.log('Collection unverified on item');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getUnverifyCollectionV1InstructionAsync,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...'); // The item to unverify\nconst collectionMint = address('collectionMintAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst [metadata] = await findMetadataPda({ mint });\nconst unverifyIx = await getUnverifyCollectionV1InstructionAsync({\n  metadata,\n  collectionMint,\n  authority: collectionDelegate,\n});\n\nawait sendAndConfirm([unverifyIx], [collectionDelegate]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection unverified on item');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  unverifyCollectionV1,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...'); // The item to unverify\nconst collectionMint = publicKey('collectionMintAddress...');\nconst collectionDelegate = umi.identity; // The delegate authority",
  "main": "await unverifyCollectionV1(umi, {\n  metadata: findMetadataPda(umi, { mint }),\n  collectionMint,\n  authority: collectionDelegate,\n}).sendAndConfirm(umi);",
  "output": "console.log('Collection unverified on item');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  unverifyCollectionV1,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...'); // The item to unverify\nconst collectionMint = publicKey('collectionMintAddress...');\nconst collectionDelegate = umi.identity; // The delegate authority\n// [/SETUP]\n\n// [MAIN]\nawait unverifyCollectionV1(umi, {\n  metadata: findMetadataPda(umi, { mint }),\n  collectionMint,\n  authority: collectionDelegate,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection unverified on item');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-collection-unverify",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
