/**
 * Example: Add Plugin to Asset
 *
 * Example of adding a plugin to an existing Core asset
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { addPlugin, fetchAsset, ruleSet } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst assetAddress = publicKey('YOUR_ASSET_ADDRESS')",
  "main": "// Fetch the existing asset\nconst asset = await fetchAsset(umi, assetAddress)\n\n// Add a Royalties plugin to the asset\nawait addPlugin(umi, {\n  asset,\n  plugin: {\n    type: 'Royalties',\n    basisPoints: 500, // 5%\n    creators: [\n      { address: umi.identity.publicKey, percentage: 100 },\n    ],\n    ruleSet: ruleSet('None'),\n  },\n}).sendAndConfirm(umi)",
  "output": "console.log('Plugin added to asset:', assetAddress)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { addPlugin, fetchAsset, ruleSet } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst assetAddress = publicKey('YOUR_ASSET_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\n// Fetch the existing asset\nconst asset = await fetchAsset(umi, assetAddress)\n\n// Add a Royalties plugin to the asset\nawait addPlugin(umi, {\n  asset,\n  plugin: {\n    type: 'Royalties',\n    basisPoints: 500, // 5%\n    creators: [\n      { address: umi.identity.publicKey, percentage: 100 },\n    ],\n    ruleSet: ruleSet('None'),\n  },\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Plugin added to asset:', assetAddress)\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::{\n    instructions::AddPluginV1Builder,\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\n};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Add a Royalties plugin to the asset\nlet add_plugin_ix = AddPluginV1Builder::new()\n    .asset(asset_pubkey)\n    .payer(payer.pubkey())\n    .plugin(Plugin::Royalties(Royalties {\n        basis_points: 500, // 5%\n        creators: vec![Creator {\n            address: creator_pubkey,\n            percentage: 100,\n        }],\n        rule_set: RuleSet::None,\n    }))\n    .init_authority(PluginAuthority::UpdateAuthority)\n    .instruction();",
  "output": "println!(\"Plugin added to asset\");",
  "full": "// [IMPORTS]\nuse mpl_core::{\n    instructions::AddPluginV1Builder,\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\n};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\n// Add a Royalties plugin to the asset\nlet add_plugin_ix = AddPluginV1Builder::new()\n    .asset(asset_pubkey)\n    .payer(payer.pubkey())\n    .plugin(Plugin::Royalties(Royalties {\n        basis_points: 500, // 5%\n        creators: vec![Creator {\n            address: creator_pubkey,\n            percentage: 100,\n        }],\n        rule_set: RuleSet::None,\n    }))\n    .init_authority(PluginAuthority::UpdateAuthority)\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Plugin added to asset\");\n// [/OUTPUT]\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\nuse mpl_core::{\n    instructions::AddPluginV1CpiBuilder,\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\n};",
  "setup": "",
  "main": "// Add a Royalties plugin via CPI\nAddPluginV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .plugin(Plugin::Royalties(Royalties {\n        basis_points: 500, // 5%\n        creators: vec![Creator {\n            address: ctx.accounts.creator.key(),\n            percentage: 100,\n        }],\n        rule_set: RuleSet::None,\n    }))\n    .init_authority(PluginAuthority::UpdateAuthority)\n    .invoke()?;",
  "output": "msg!(\"Plugin added to asset: {}\", ctx.accounts.asset.key());",
  "full": "// [IMPORTS]\nuse anchor_lang::prelude::*;\nuse mpl_core::{\n    instructions::AddPluginV1CpiBuilder,\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\n};\n// [/IMPORTS]\n\n// [MAIN]\n// Add a Royalties plugin via CPI\nAddPluginV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .plugin(Plugin::Royalties(Royalties {\n        basis_points: 500, // 5%\n        creators: vec![Creator {\n            address: ctx.accounts.creator.key(),\n            percentage: 100,\n        }],\n        rule_set: RuleSet::None,\n    }))\n    .init_authority(PluginAuthority::UpdateAuthority)\n    .invoke()?;\n// [/MAIN]\n\n// [OUTPUT]\nmsg!(\"Plugin added to asset: {}\", ctx.accounts.asset.key());\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Add Plugin to Asset",
  description: "Example of adding a plugin to an existing Core asset",
  tags: ['core', 'plugin', 'royalties', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
