/**
 * Example: Add Plugin to Asset
 *
 * Example of adding a plugin to an existing Core asset
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { addPlugin, fetchAsset, ruleSet } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'\r\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n\r\nconst assetAddress = publicKey('YOUR_ASSET_ADDRESS')",
  "main": "// Fetch the existing asset\r\nconst asset = await fetchAsset(umi, assetAddress)\r\n\r\n// Add a Royalties plugin to the asset\r\nawait addPlugin(umi, {\r\n  asset,\r\n  plugin: {\r\n    type: 'Royalties',\r\n    basisPoints: 500, // 5%\r\n    creators: [\r\n      { address: umi.identity.publicKey, percentage: 100 },\r\n    ],\r\n    ruleSet: ruleSet('None'),\r\n  },\r\n}).sendAndConfirm(umi)",
  "output": "console.log('Plugin added to asset:', assetAddress)",
  "full": "// [IMPORTS]\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { addPlugin, fetchAsset, ruleSet } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'\r\nimport { publicKey } from '@metaplex-foundation/umi'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n\r\nconst assetAddress = publicKey('YOUR_ASSET_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Fetch the existing asset\r\nconst asset = await fetchAsset(umi, assetAddress)\r\n\r\n// Add a Royalties plugin to the asset\r\nawait addPlugin(umi, {\r\n  asset,\r\n  plugin: {\r\n    type: 'Royalties',\r\n    basisPoints: 500, // 5%\r\n    creators: [\r\n      { address: umi.identity.publicKey, percentage: 100 },\r\n    ],\r\n    ruleSet: ruleSet('None'),\r\n  },\r\n}).sendAndConfirm(umi)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Plugin added to asset:', assetAddress)\r\n// [/OUTPUT]\r\n"
}

const shankSections = {
  "imports": "use mpl_core::{\r\n    instructions::AddPluginV1Builder,\r\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\r\n};\r\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Add a Royalties plugin to the asset\r\nlet add_plugin_ix = AddPluginV1Builder::new()\r\n    .asset(asset_pubkey)\r\n    .payer(payer.pubkey())\r\n    .plugin(Plugin::Royalties(Royalties {\r\n        basis_points: 500, // 5%\r\n        creators: vec![Creator {\r\n            address: creator_pubkey,\r\n            percentage: 100,\r\n        }],\r\n        rule_set: RuleSet::None,\r\n    }))\r\n    .init_authority(PluginAuthority::UpdateAuthority)\r\n    .instruction();",
  "output": "println!(\"Plugin added to asset\");",
  "full": "// [IMPORTS]\r\nuse mpl_core::{\r\n    instructions::AddPluginV1Builder,\r\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\r\n};\r\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\n// Add a Royalties plugin to the asset\r\nlet add_plugin_ix = AddPluginV1Builder::new()\r\n    .asset(asset_pubkey)\r\n    .payer(payer.pubkey())\r\n    .plugin(Plugin::Royalties(Royalties {\r\n        basis_points: 500, // 5%\r\n        creators: vec![Creator {\r\n            address: creator_pubkey,\r\n            percentage: 100,\r\n        }],\r\n        rule_set: RuleSet::None,\r\n    }))\r\n    .init_authority(PluginAuthority::UpdateAuthority)\r\n    .instruction();\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nprintln!(\"Plugin added to asset\");\r\n// [/OUTPUT]\r\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\r\nuse mpl_core::{\r\n    instructions::AddPluginV1CpiBuilder,\r\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\r\n};",
  "setup": "",
  "main": "// Add a Royalties plugin via CPI\r\nAddPluginV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\r\n    .asset(&ctx.accounts.asset)\r\n    .payer(&ctx.accounts.payer)\r\n    .system_program(&ctx.accounts.system_program)\r\n    .plugin(Plugin::Royalties(Royalties {\r\n        basis_points: 500, // 5%\r\n        creators: vec![Creator {\r\n            address: ctx.accounts.creator.key(),\r\n            percentage: 100,\r\n        }],\r\n        rule_set: RuleSet::None,\r\n    }))\r\n    .init_authority(PluginAuthority::UpdateAuthority)\r\n    .invoke()?;",
  "output": "msg!(\"Plugin added to asset: {}\", ctx.accounts.asset.key());",
  "full": "// [IMPORTS]\r\nuse anchor_lang::prelude::*;\r\nuse mpl_core::{\r\n    instructions::AddPluginV1CpiBuilder,\r\n    types::{Plugin, PluginAuthority, Royalties, Creator, RuleSet},\r\n};\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\n// Add a Royalties plugin via CPI\r\nAddPluginV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\r\n    .asset(&ctx.accounts.asset)\r\n    .payer(&ctx.accounts.payer)\r\n    .system_program(&ctx.accounts.system_program)\r\n    .plugin(Plugin::Royalties(Royalties {\r\n        basis_points: 500, // 5%\r\n        creators: vec![Creator {\r\n            address: ctx.accounts.creator.key(),\r\n            percentage: 100,\r\n        }],\r\n        rule_set: RuleSet::None,\r\n    }))\r\n    .init_authority(PluginAuthority::UpdateAuthority)\r\n    .invoke()?;\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nmsg!(\"Plugin added to asset: {}\", ctx.accounts.asset.key());\r\n// [/OUTPUT]\r\n"
}

export const metadata = {
  title: "Add Plugin to Asset",
  description: "Example of adding a plugin to an existing Core asset",
  tags: ['core', 'plugin', 'royalties', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
