/**
 * Example: transfer-pnft
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address\nconst currentOwner = authority.address;\nconst destinationOwner = 'destinationWallet...';",
  "main": "// Transfer the Programmable NFT to a new owner\n// Note: pNFTs require additional Token Record accounts handled automatically\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  tokenOwner: currentOwner,\n  destinationOwner,\n  authority,\n  payer: authority,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([transferIx], [authority]);",
  "output": "console.log('pNFT transferred to:', destinationOwner);",
  "full": "// [IMPORTS]\nimport {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n\nconst mintAddress = 'mintAddress...'; // The pNFT mint address\nconst currentOwner = authority.address;\nconst destinationOwner = 'destinationWallet...';\n// [/SETUP]\n\n// [MAIN]\n// Transfer the Programmable NFT to a new owner\n// Note: pNFTs require additional Token Record accounts handled automatically\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  tokenOwner: currentOwner,\n  destinationOwner,\n  authority,\n  payer: authority,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([transferIx], [authority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred to:', destinationOwner);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  transferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mintAddress = publicKey('mintAddress...');\nconst currentOwner = umi.identity;\nconst destinationOwner = publicKey('destinationWallet...');",
  "main": "// Transfer the Programmable NFT to a new owner\n// Note: pNFTs require additional Token Record accounts handled automatically\nawait transferV1(umi, {\n  mint: mintAddress,\n  authority: currentOwner,\n  tokenOwner: currentOwner.publicKey,\n  destinationOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('pNFT transferred to:', destinationOwner);",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  transferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mintAddress = publicKey('mintAddress...');\nconst currentOwner = umi.identity;\nconst destinationOwner = publicKey('destinationWallet...');\n// [/SETUP]\n\n// [MAIN]\n// Transfer the Programmable NFT to a new owner\n// Note: pNFTs require additional Token Record accounts handled automatically\nawait transferV1(umi, {\n  mint: mintAddress,\n  authority: currentOwner,\n  tokenOwner: currentOwner.publicKey,\n  destinationOwner,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT transferred to:', destinationOwner);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "transfer-pnft",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
