/**
 * Example: create_agent_token
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createAndRegisterLaunch } from '@metaplex-foundation/genesis/api';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { keypairIdentity } from '@metaplex-foundation/umi';",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com');\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes);\numi.use(keypairIdentity(keypair));",
  "main": "const result = await createAndRegisterLaunch(umi, {}, {\n  wallet: umi.identity.publicKey,\n  agent: {\n    mint: agentAssetAddress, // Core asset address of the registered agent\n    setToken: true,          // permanently associates this token with the agent\n  },\n  launchType: 'bondingCurve',\n  token: {\n    name: 'Agent Token',\n    symbol: 'AGT',\n    image: 'https://gateway.irys.xyz/your-image-id',\n  },\n  launch: {},\n});\n\nconsole.log('Token launched!');\nconsole.log('Mint address:', result.mintAddress);\nconsole.log('View at:', result.launch.link);",
  "output": "// Token launched!\n// Mint address: <base58 mint address>\n// View at: https://www.metaplex.com/...",
  "full": "// [IMPORTS]\nimport { createAndRegisterLaunch } from '@metaplex-foundation/genesis/api';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { keypairIdentity } from '@metaplex-foundation/umi';\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com');\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes);\numi.use(keypairIdentity(keypair));\n// [/SETUP]\n\n// [MAIN]\nconst result = await createAndRegisterLaunch(umi, {}, {\n  wallet: umi.identity.publicKey,\n  agent: {\n    mint: agentAssetAddress, // Core asset address of the registered agent\n    setToken: true,          // permanently associates this token with the agent\n  },\n  launchType: 'bondingCurve',\n  token: {\n    name: 'Agent Token',\n    symbol: 'AGT',\n    image: 'https://gateway.irys.xyz/your-image-id',\n  },\n  launch: {},\n});\n\nconsole.log('Token launched!');\nconsole.log('Mint address:', result.mintAddress);\nconsole.log('View at:', result.launch.link);\n// [/MAIN]\n\n// [OUTPUT]\n// Token launched!\n// Mint address: <base58 mint address>\n// View at: https://www.metaplex.com/...\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "mplx genesis launch create --launchType bonding-curve \\\n  --name \"Agent Token\" \\\n  --symbol \"AGT\" \\\n  --image \"https://gateway.irys.xyz/your-image-id\" \\\n  --agentAsset <AGENT_CORE_ASSET_ADDRESS> \\\n  --agentSetToken\n"
}

export const metadata = {
  title: "create_agent_token",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
