/**
 * Example: delegate-collection-item-update
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getUpdateAsCollectionItemDelegateV2InstructionAsync,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst collectionMint = address('collectionMintAddress...');",
  "main": "const updateIx = await getUpdateAsCollectionItemDelegateV2InstructionAsync({\n  mint,\n  authority: collectionItemDelegate,\n  collection: {\n    __kind: 'Set',\n    fields: [{ key: collectionMint, verified: false }],\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: collectionItemDelegate,\n});",
  "output": "console.log('Collection set on asset via Collection Item delegate');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getUpdateAsCollectionItemDelegateV2InstructionAsync,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst collectionMint = address('collectionMintAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst updateIx = await getUpdateAsCollectionItemDelegateV2InstructionAsync({\n  mint,\n  authority: collectionItemDelegate,\n  collection: {\n    __kind: 'Set',\n    fields: [{ key: collectionMint, verified: false }],\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: collectionItemDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection set on asset via Collection Item delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsCollectionItemDelegateV2,\n  collectionToggle,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst collectionMint = publicKey('collectionMintAddress...');\nconst collectionItemDelegate = umi.identity; // The delegate authority",
  "main": "await updateAsCollectionItemDelegateV2(umi, {\n  mint,\n  authority: collectionItemDelegate,\n  collection: collectionToggle('Set', [\n    { key: collectionMint, verified: false },\n  ]),\n}).sendAndConfirm(umi);",
  "output": "console.log('Collection set on asset via Collection Item delegate');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsCollectionItemDelegateV2,\n  collectionToggle,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst collectionMint = publicKey('collectionMintAddress...');\nconst collectionItemDelegate = umi.identity; // The delegate authority\n// [/SETUP]\n\n// [MAIN]\nawait updateAsCollectionItemDelegateV2(umi, {\n  mint,\n  authority: collectionItemDelegate,\n  collection: collectionToggle('Set', [\n    { key: collectionMint, verified: false },\n  ]),\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection set on asset via Collection Item delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-collection-item-update",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
