/**
 * Example: delegate-locked-transfer-approve
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getDelegateLockedTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst lockedTransferDelegate = address('delegateAddress...');\nconst lockedAddress = address('escrowAddress...'); // Destination for locked transfers",
  "main": "const delegateIx = await getDelegateLockedTransferV1InstructionAsync({\n  mint,\n  tokenOwner: owner.address,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  lockedAddress,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: owner,\n});",
  "output": "console.log('Locked Transfer delegate approved');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getDelegateLockedTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst lockedTransferDelegate = address('delegateAddress...');\nconst lockedAddress = address('escrowAddress...'); // Destination for locked transfers\n// [/SETUP]\n\n// [MAIN]\nconst delegateIx = await getDelegateLockedTransferV1InstructionAsync({\n  mint,\n  tokenOwner: owner.address,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  lockedAddress,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: owner,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Locked Transfer delegate approved');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateLockedTransferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst owner = umi.identity;\nconst lockedTransferDelegate = publicKey('delegateAddress...');\nconst lockedAddress = publicKey('escrowAddress...'); // Destination for locked transfers",
  "main": "await delegateLockedTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  lockedAddress,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Locked Transfer delegate approved');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateLockedTransferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst owner = umi.identity;\nconst lockedTransferDelegate = publicKey('delegateAddress...');\nconst lockedAddress = publicKey('escrowAddress...'); // Destination for locked transfers\n// [/SETUP]\n\n// [MAIN]\nawait delegateLockedTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  lockedAddress,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Locked Transfer delegate approved');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-locked-transfer-approve",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
