/**
 * Example: pnft-fetch-with-token
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport { fetchDigitalAssetWithAssociatedToken } from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('11111111111111111111111111111111');\nconst owner = address('22222222222222222222222222222222');",
  "main": "const assetWithToken = await fetchDigitalAssetWithAssociatedToken(\n  rpc,\n  mint,\n  owner\n);",
  "output": "console.log('Metadata:', assetWithToken.metadata.name);\nconsole.log('Token Record:', assetWithToken.tokenRecord);",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport { fetchDigitalAssetWithAssociatedToken } from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('11111111111111111111111111111111');\nconst owner = address('22222222222222222222222222222222');\n// [/SETUP]\n\n// [MAIN]\nconst assetWithToken = await fetchDigitalAssetWithAssociatedToken(\n  rpc,\n  mint,\n  owner\n);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Metadata:', assetWithToken.metadata.name);\nconsole.log('Token Record:', assetWithToken.tokenRecord);\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAssetWithAssociatedToken } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('11111111111111111111111111111111');\nconst owner = publicKey('22222222222222222222222222222222');",
  "main": "const assetWithToken = await fetchDigitalAssetWithAssociatedToken(\n  umi,\n  mint,\n  owner\n);",
  "output": "console.log('Metadata:', assetWithToken.metadata.name);\nconsole.log('Token Record:', assetWithToken.tokenRecord);",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAssetWithAssociatedToken } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('11111111111111111111111111111111');\nconst owner = publicKey('22222222222222222222222222222222');\n// [/SETUP]\n\n// [MAIN]\nconst assetWithToken = await fetchDigitalAssetWithAssociatedToken(\n  umi,\n  mint,\n  owner\n);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Metadata:', assetWithToken.metadata.name);\nconsole.log('Token Record:', assetWithToken.tokenRecord);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "pnft-fetch-with-token",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
