/**
 * Example: change-collection
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  fetchCollection,\n  collectionAddress,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'",
  "setup": "const assetId = publicKey('11111111111111111111111111111111')\nconst newCollectionId = publicKey('22222222222222222222222222222222')",
  "main": "const asset = await fetchAsset(umi, assetId)\n\nconst currentCollectionId = collectionAddress(asset)\nif (!currentCollectionId) {\n  throw new Error('Asset does not belong to a collection')\n}\nconst currentCollection = await fetchCollection(umi, currentCollectionId)\n\nawait update(umi, {\n  asset,\n  collection: currentCollection,\n  newCollection: newCollectionId,\n  newUpdateAuthority: updateAuthority('Collection', [newCollectionId]),\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset moved to new collection')",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  fetchCollection,\n  collectionAddress,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst assetId = publicKey('11111111111111111111111111111111')\nconst newCollectionId = publicKey('22222222222222222222222222222222')\n// [/SETUP]\n\n// [MAIN]\nconst asset = await fetchAsset(umi, assetId)\n\nconst currentCollectionId = collectionAddress(asset)\nif (!currentCollectionId) {\n  throw new Error('Asset does not belong to a collection')\n}\nconst currentCollection = await fetchCollection(umi, currentCollectionId)\n\nawait update(umi, {\n  asset,\n  collection: currentCollection,\n  newCollection: newCollectionId,\n  newUpdateAuthority: updateAuthority('Collection', [newCollectionId]),\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset moved to new collection')\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Move an asset from its current collection to a different one\nmplx core asset update <assetId> --collection <newCollectionId>\n"
}

export const metadata = {
  title: "change-collection",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
