/**
 * Example: manual-plugin-derivation
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { deriveAssetPlugins } from '@metaplex-foundation/mpl-core'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('<ENDPOINT>').use(dasApi())\nconst collectionId = publicKey('<PublicKey>')",
  "main": "const collection = await das.getCollection(umi, collectionId)\nconst assetsByCollection = await das.getAssetsByCollection(umi, {\n  collection: collection.publicKey,\n  skipDerivePlugins: true,\n})\n\nconst derivedAssets = assetsByCollection.map((asset) =>\n  deriveAssetPlugins(asset, collection)\n)",
  "output": "console.log(derivedAssets)",
  "full": "// [IMPORTS]\nimport { deriveAssetPlugins } from '@metaplex-foundation/mpl-core'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<ENDPOINT>').use(dasApi())\nconst collectionId = publicKey('<PublicKey>')\n// [/SETUP]\n\n// [MAIN]\nconst collection = await das.getCollection(umi, collectionId)\nconst assetsByCollection = await das.getAssetsByCollection(umi, {\n  collection: collection.publicKey,\n  skipDerivePlugins: true,\n})\n\nconst derivedAssets = assetsByCollection.map((asset) =>\n  deriveAssetPlugins(asset, collection)\n)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log(derivedAssets)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "manual-plugin-derivation",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
