/**
 * Example: Create Asset in Collection
 *
 * Example of creating an NFT asset within an existing collection
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { create, fetchCollection } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst collectionAddress = publicKey('YOUR_COLLECTION_ADDRESS')",
  "main": "// Fetch the existing collection\nconst collection = await fetchCollection(umi, collectionAddress)\n\n// Generate a new keypair for the asset\nconst assetSigner = generateSigner(umi)\n\n// Create asset in the collection\nawait create(umi, {\n  asset: assetSigner,\n  collection,\n  name: 'Collection Item #1',\n  uri: 'https://example.com/item1.json',\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset created in collection:', assetSigner.publicKey)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { create, fetchCollection } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst collectionAddress = publicKey('YOUR_COLLECTION_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\n// Fetch the existing collection\nconst collection = await fetchCollection(umi, collectionAddress)\n\n// Generate a new keypair for the asset\nconst assetSigner = generateSigner(umi)\n\n// Create asset in the collection\nawait create(umi, {\n  asset: assetSigner,\n  collection,\n  name: 'Collection Item #1',\n  uri: 'https://example.com/item1.json',\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset created in collection:', assetSigner.publicKey)\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::instructions::CreateV1Builder;\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Create asset in a collection\nlet create_ix = CreateV1Builder::new()\n    .asset(asset.pubkey())\n    .collection(Some(collection_pubkey))\n    .payer(payer.pubkey())\n    .name(\"Collection Item #1\".to_string())\n    .uri(\"https://example.com/item1.json\".to_string())\n    .instruction();",
  "output": "println!(\"Asset created in collection\");",
  "full": "// [IMPORTS]\nuse mpl_core::instructions::CreateV1Builder;\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\n// Create asset in a collection\nlet create_ix = CreateV1Builder::new()\n    .asset(asset.pubkey())\n    .collection(Some(collection_pubkey))\n    .payer(payer.pubkey())\n    .name(\"Collection Item #1\".to_string())\n    .uri(\"https://example.com/item1.json\".to_string())\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Asset created in collection\");\n// [/OUTPUT]\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\nuse mpl_core::instructions::CreateV1CpiBuilder;",
  "setup": "",
  "main": "// Create asset in a collection via CPI\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .collection(Some(&ctx.accounts.collection))\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"Collection Item #1\".to_string())\n    .uri(\"https://example.com/item1.json\".to_string())\n    .invoke()?;",
  "output": "msg!(\"Asset created in collection: {}\", ctx.accounts.asset.key());",
  "full": "// [IMPORTS]\nuse anchor_lang::prelude::*;\nuse mpl_core::instructions::CreateV1CpiBuilder;\n// [/IMPORTS]\n\n// [MAIN]\n// Create asset in a collection via CPI\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .collection(Some(&ctx.accounts.collection))\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"Collection Item #1\".to_string())\n    .uri(\"https://example.com/item1.json\".to_string())\n    .invoke()?;\n// [/MAIN]\n\n// [OUTPUT]\nmsg!(\"Asset created in collection: {}\", ctx.accounts.asset.key());\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Create Asset in Collection",
  description: "Example of creating an NFT asset within an existing collection",
  tags: ['core', 'nft', 'collection', 'create', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
