/**
 * Example: Mint Fungible Tokens
 *
 * Mint additional fungible tokens to a wallet
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "// To install all the required packages use the following command\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n    createTokenIfMissing,\n    findAssociatedTokenPda,\n    mintTokensTo,\n} from '@metaplex-foundation/mpl-toolbox';\nimport {\n    keypairIdentity,\n    publicKey,\n    transactionBuilder,\n} from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { readFileSync } from 'fs';",
  "setup": "// Initialize Umi with Devnet endpoint\nconst umi = createUmi('https://api.devnet.solana.com')\n\n// Load your wallet/keypair\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address and destination wallet\nconst mintAddress = publicKey('<your token mint address>')\nconst destinationAddress = publicKey('<destination wallet address>')",
  "main": "// Find the destination token account\nconst destinationTokenAccount = findAssociatedTokenPda(umi, {\n  mint: mintAddress,\n  owner: destinationAddress,\n})\n\n// Create the destination token account if it doesn't exist and mint tokens\nawait transactionBuilder()\n  .add(createTokenIfMissing(umi, {\n    mint: mintAddress,\n    owner: destinationAddress,\n  }))\n  // Mint 100 tokens to the destination\n  .add(\n    mintTokensTo(umi, {\n    mint: mintAddress,\n    token: destinationTokenAccount,\n    amount: 100,\n  }))\n  .sendAndConfirm(umi)",
  "output": "console.log('Minted 100 tokens')\nconsole.log('Mint:', mintAddress)\nconsole.log('To:', destinationTokenAccount)",
  "full": "// [IMPORTS]\n// To install all the required packages use the following command\n// npm install @metaplex-foundation/mpl-toolbox @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n    createTokenIfMissing,\n    findAssociatedTokenPda,\n    mintTokensTo,\n} from '@metaplex-foundation/mpl-toolbox';\nimport {\n    keypairIdentity,\n    publicKey,\n    transactionBuilder,\n} from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\nimport { readFileSync } from 'fs';\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize Umi with Devnet endpoint\nconst umi = createUmi('https://api.devnet.solana.com')\n\n// Load your wallet/keypair\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address and destination wallet\nconst mintAddress = publicKey('<your token mint address>')\nconst destinationAddress = publicKey('<destination wallet address>')\n// [/SETUP]\n\n// [MAIN]\n// Find the destination token account\nconst destinationTokenAccount = findAssociatedTokenPda(umi, {\n  mint: mintAddress,\n  owner: destinationAddress,\n})\n\n// Create the destination token account if it doesn't exist and mint tokens\nawait transactionBuilder()\n  .add(createTokenIfMissing(umi, {\n    mint: mintAddress,\n    owner: destinationAddress,\n  }))\n  // Mint 100 tokens to the destination\n  .add(\n    mintTokensTo(umi, {\n    mint: mintAddress,\n    token: destinationTokenAccount,\n    amount: 100,\n  }))\n  .sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Minted 100 tokens')\nconsole.log('Mint:', mintAddress)\nconsole.log('To:', destinationTokenAccount)\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Mint Additional Tokens using the Metaplex CLI\n\n# Mint tokens to your own wallet (default)\n# Usage: mplx toolbox token mint <MINT_ADDRESS> <AMOUNT>\nmplx toolbox token mint <MINT_ADDRESS> <AMOUNT>\n\n# Mint tokens to a specific recipient\nmplx toolbox token mint <MINT_ADDRESS> <AMOUNT> --recipient <RECIPIENT_ADDRESS>\n\n# Example: Mint 1000 tokens (0 decimals) to your wallet\nmplx toolbox token mint 7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU 1000\n\n# Example: Mint 1000 tokens (9 decimals) to your wallet\n# Amount is in smallest units: 1000 * 10^9 = 1000000000000\nmplx toolbox token mint 7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU 1000000000000\n\n# Example: Mint tokens to another wallet\nmplx toolbox token mint 7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU 1000 \\\n  --recipient 9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM\n\n# Note: You must be the mint authority to mint additional tokens\n"
}

export const metadata = {
  title: "Mint Fungible Tokens",
  description: "Mint additional fungible tokens to a wallet",
  tags: ['token-metadata', 'fungible', 'spl-token', 'mint', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
