/**
 * Example: Get All Tokens by Owner
 *
 * Retrieve all fungible tokens owned by a wallet address using DAS API
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const dasSections = {
  "imports": "// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "const umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\nconst walletAddress = publicKey('WALLET_ADDRESS')",
  "main": "// Get all fungible assets owned by the wallet using searchAssets\r\n// Using interface: 'FungibleToken' filters server-side (more efficient)\r\nconst result = await umi.rpc.searchAssets({\r\n  owner: walletAddress,\r\n  interface: 'FungibleToken',\r\n  limit: 1000,\r\n  displayOptions: {\r\n    showFungible: true\r\n  }\r\n})\r\n\r\nconst fungibleTokens = result.items",
  "output": "console.log(`Found ${fungibleTokens.length} fungible tokens\\n`)\r\n\r\nfungibleTokens.forEach(token => {\r\n  const decimals = token.token_info?.decimals || 0\r\n  const rawBalance = token.token_info?.balance || 0\r\n  const balance = Number(rawBalance) / Math.pow(10, decimals)\r\n\r\n  console.log(`${token.content.metadata?.name} (${token.content.metadata?.symbol})`)\r\n  console.log(`  Mint: ${token.id}`)\r\n  console.log(`  Balance: ${balance.toLocaleString()}`)\r\n})",
  "full": "// [IMPORTS]\r\n// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\nconst umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\nconst walletAddress = publicKey('WALLET_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Get all fungible assets owned by the wallet using searchAssets\r\n// Using interface: 'FungibleToken' filters server-side (more efficient)\r\nconst result = await umi.rpc.searchAssets({\r\n  owner: walletAddress,\r\n  interface: 'FungibleToken',\r\n  limit: 1000,\r\n  displayOptions: {\r\n    showFungible: true\r\n  }\r\n})\r\n\r\nconst fungibleTokens = result.items\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log(`Found ${fungibleTokens.length} fungible tokens\\n`)\r\n\r\nfungibleTokens.forEach(token => {\r\n  const decimals = token.token_info?.decimals || 0\r\n  const rawBalance = token.token_info?.balance || 0\r\n  const balance = Number(rawBalance) / Math.pow(10, decimals)\r\n\r\n  console.log(`${token.content.metadata?.name} (${token.content.metadata?.symbol})`)\r\n  console.log(`  Mint: ${token.id}`)\r\n  console.log(`  Balance: ${balance.toLocaleString()}`)\r\n})\r\n// [/OUTPUT]\r\n"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Get all fungible tokens owned by a wallet using searchAssets\r\n# Using interface: \"FungibleToken\" filters server-side (more efficient)\r\ncurl -X POST \\\r\n  -H \"Content-Type: application/json\" \\\r\n  -d '{\r\n    \"jsonrpc\": \"2.0\",\r\n    \"id\": 1,\r\n    \"method\": \"searchAssets\",\r\n    \"params\": {\r\n      \"ownerAddress\": \"GfK2Xz6pzQp1sC1FvxePKnikZA7iyaCSVXZykixLjem5\",\r\n      \"interface\": \"FungibleToken\",\r\n      \"options\": {\r\n        \"showFungible\": true\r\n      }\r\n    }\r\n  }' \\\r\n  https://api.devnet.solana.com"
}

export const metadata = {
  title: "Get All Tokens by Owner",
  description: "Retrieve all fungible tokens owned by a wallet address using DAS API",
  tags: ['token-metadata', 'fungible', 'das-api', 'searchAssets', 'beginner'],
}

export const examples = {
  das: {
    framework: 'DAS',
    language: 'javascript',
    code: dasSections.full,
    sections: dasSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
