/**
 * Example: claim_legacy_nft
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  distributeToLegacyNft,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// Default nftOwner to the Umi identity, or pass nftOwner explicitly\n// for a sponsored claim.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst nftMint = publicKey(process.env.LEGACY_NFT_MINT!)\nconst allocations = [{ address: nftMint, amount: 100_000n }]\nconst { proofs } = prepareDistribution(allocations)",
  "main": "await distributeToLegacyNft(umi, {\n  distribution,\n  mint,\n  nftMint,\n  amount: allocations[0].amount,\n  proof: proofs[0],\n  nonce: 0,\n}).sendAndConfirm(umi)",
  "output": "// The current NFT owner's ATA receives 100000 base units.\n// The receipt is keyed by the NFT mint, so the allocation cannot be claimed twice.",
  "full": "// [IMPORTS]\nimport {\n  distributeToLegacyNft,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\n// Default nftOwner to the Umi identity, or pass nftOwner explicitly\n// for a sponsored claim.\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst nftMint = publicKey(process.env.LEGACY_NFT_MINT!)\nconst allocations = [{ address: nftMint, amount: 100_000n }]\nconst { proofs } = prepareDistribution(allocations)\n// [/SETUP]\n\n// [MAIN]\nawait distributeToLegacyNft(umi, {\n  distribution,\n  mint,\n  nftMint,\n  amount: allocations[0].amount,\n  proof: proofs[0],\n  nonce: 0,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// The current NFT owner's ATA receives 100000 base units.\n// The receipt is keyed by the NFT mint, so the allocation cannot be claimed twice.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "claim_legacy_nft",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
