/**
 * Example: delegate-data-item-revoke
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getRevokeDataItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst dataItemDelegate = address('delegateAddress...');",
  "main": "const revokeIx = await getRevokeDataItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke\n  delegate: dataItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [updateAuthority]);",
  "output": "console.log('Data Item delegate revoked');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getRevokeDataItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst dataItemDelegate = address('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst revokeIx = await getRevokeDataItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke\n  delegate: dataItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [updateAuthority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Data Item delegate revoked');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  revokeDataItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst dataItemDelegate = publicKey('delegateAddress...');",
  "main": "await revokeDataItemV1(umi, {\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke\n  delegate: dataItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Data Item delegate revoked');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  revokeDataItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst dataItemDelegate = publicKey('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait revokeDataItemV1(umi, {\n  mint,\n  authority: updateAuthority, // Or pass the delegate authority as a Signer to self-revoke\n  delegate: dataItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Data Item delegate revoked');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-data-item-revoke",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
