/**
 * Example: add_claim_schedule_bucket_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  addClaimScheduleBucketV2,\n  createClaimSchedule,\n  createTimeAbsoluteCondition,\n  findClaimScheduleBucketV2Pda,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst baseMint = publicKey('YOUR_PROJECT_TOKEN_MINT')\nconst recipient = publicKey('VESTING_RECIPIENT')\nconst bucketIndex = 0",
  "main": "const [vestingBucket] = findClaimScheduleBucketV2Pda(umi, {\n  genesisAccount,\n  bucketIndex,\n})\n\nconst DAY = 86_400n\nconst vestingStart = BigInt(Math.floor(Date.now() / 1000)) + 7n * DAY\nconst vestingEnd = vestingStart + 365n * DAY\n\nawait addClaimScheduleBucketV2(umi, {\n  genesisAccount,\n  baseMint,\n  authority: umi.identity,\n  recipient,\n  bucketIndex,\n  baseTokenAllocation: 100_000_000_000_000n, // 100,000 tokens at 9 decimals\n  claimStartCondition: createTimeAbsoluteCondition(vestingStart),\n  claimSchedule: createClaimSchedule({\n    startTime: vestingStart,\n    endTime: vestingEnd,\n    period: 30n * DAY,\n    cliffTime: vestingStart,\n    cliffAmountBps: 1_000, // 10%\n  }),\n  pausable: true,\n  cancelable: true,\n  cancelableByRecipient: false,\n  transferable: true,\n  transferableByRecipient: false,\n  backendSigner: null,\n  endBehaviors: [],\n}).sendAndConfirm(umi)",
  "output": "console.log('ClaimScheduleBucketV2:', vestingBucket)",
  "full": "// [IMPORTS]\nimport {\n  addClaimScheduleBucketV2,\n  createClaimSchedule,\n  createTimeAbsoluteCondition,\n  findClaimScheduleBucketV2Pda,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { keypairIdentity, publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair))\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst baseMint = publicKey('YOUR_PROJECT_TOKEN_MINT')\nconst recipient = publicKey('VESTING_RECIPIENT')\nconst bucketIndex = 0\n// [/SETUP]\n\n// [MAIN]\nconst [vestingBucket] = findClaimScheduleBucketV2Pda(umi, {\n  genesisAccount,\n  bucketIndex,\n})\n\nconst DAY = 86_400n\nconst vestingStart = BigInt(Math.floor(Date.now() / 1000)) + 7n * DAY\nconst vestingEnd = vestingStart + 365n * DAY\n\nawait addClaimScheduleBucketV2(umi, {\n  genesisAccount,\n  baseMint,\n  authority: umi.identity,\n  recipient,\n  bucketIndex,\n  baseTokenAllocation: 100_000_000_000_000n, // 100,000 tokens at 9 decimals\n  claimStartCondition: createTimeAbsoluteCondition(vestingStart),\n  claimSchedule: createClaimSchedule({\n    startTime: vestingStart,\n    endTime: vestingEnd,\n    period: 30n * DAY,\n    cliffTime: vestingStart,\n    cliffAmountBps: 1_000, // 10%\n  }),\n  pausable: true,\n  cancelable: true,\n  cancelableByRecipient: false,\n  transferable: true,\n  transferableByRecipient: false,\n  backendSigner: null,\n  endBehaviors: [],\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('ClaimScheduleBucketV2:', vestingBucket)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "add_claim_schedule_bucket_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
