/**
 * Example: sponsored_legacy_nft_claim
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  distributeToLegacyNft,\n  mplDistro,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst airdropService = umi.payer\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst rewardMint = publicKey(process.env.TOKEN_MINT!)\nconst nftMint = publicKey(process.env.LEGACY_NFT_MINT!)\nconst currentOwner = publicKey(process.env.NFT_OWNER!)\nconst amount = 100_000n\nconst proof = []\nconst nonce = 0",
  "main": "await distributeToLegacyNft(umi, {\n  payer: airdropService,\n  distribution,\n  mint: rewardMint,\n  nftMint,\n  nftOwner: currentOwner,\n  amount,\n  proof,\n  nonce,\n}).sendAndConfirm(umi)",
  "output": "// The current NFT owner's ATA receives the allocation.",
  "full": "// [IMPORTS]\nimport {\n  distributeToLegacyNft,\n  mplDistro,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst airdropService = umi.payer\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst rewardMint = publicKey(process.env.TOKEN_MINT!)\nconst nftMint = publicKey(process.env.LEGACY_NFT_MINT!)\nconst currentOwner = publicKey(process.env.NFT_OWNER!)\nconst amount = 100_000n\nconst proof = []\nconst nonce = 0\n// [/SETUP]\n\n// [MAIN]\nawait distributeToLegacyNft(umi, {\n  payer: airdropService,\n  distribution,\n  mint: rewardMint,\n  nftMint,\n  nftOwner: currentOwner,\n  amount,\n  proof,\n  nonce,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// The current NFT owner's ATA receives the allocation.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "sponsored_legacy_nft_claim",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
