/**
 * Example: delegate-locked-transfer-lock
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getLockV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');",
  "main": "const lockIx = await getLockV1InstructionAsync({\n  mint,\n  authority: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [lockIx],\n  payer: lockedTransferDelegate,\n});",
  "output": "console.log('pNFT locked via Locked Transfer delegate');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getLockV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst lockIx = await getLockV1InstructionAsync({\n  mint,\n  authority: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [lockIx],\n  payer: lockedTransferDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT locked via Locked Transfer delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  lockV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst lockedTransferDelegate = umi.identity; // The delegate authority",
  "main": "await lockV1(umi, {\n  mint,\n  authority: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('pNFT locked via Locked Transfer delegate');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  lockV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst lockedTransferDelegate = umi.identity; // The delegate authority\n// [/SETUP]\n\n// [MAIN]\nawait lockV1(umi, {\n  mint,\n  authority: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('pNFT locked via Locked Transfer delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-locked-transfer-lock",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
