/**
 * Example: get-assets-by-owner
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('<ENDPOINT>').use(dasApi())\nconst owner = publicKey('<PublicKey>')",
  "main": "const assets = await das.getAssetsByOwner(umi, { owner })",
  "output": "console.log(assets)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\nimport { das } from '@metaplex-foundation/mpl-core-das'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('<ENDPOINT>').use(dasApi())\nconst owner = publicKey('<PublicKey>')\n// [/SETUP]\n\n// [MAIN]\nconst assets = await das.getAssetsByOwner(umi, { owner })\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log(assets)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "get-assets-by-owner",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
