/**
 * Example: delegate-programmable-config-item-approve
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getDelegateProgrammableConfigItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst programmableConfigItemDelegate = address('delegateAddress...');",
  "main": "const delegateIx = await getDelegateProgrammableConfigItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: programmableConfigItemDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: updateAuthority,\n});",
  "output": "console.log('Programmable Config Item delegate approved');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getDelegateProgrammableConfigItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst programmableConfigItemDelegate = address('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst delegateIx = await getDelegateProgrammableConfigItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: programmableConfigItemDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: updateAuthority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Programmable Config Item delegate approved');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateProgrammableConfigItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst programmableConfigItemDelegate = publicKey('delegateAddress...');",
  "main": "await delegateProgrammableConfigItemV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: programmableConfigItemDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Programmable Config Item delegate approved');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateProgrammableConfigItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst programmableConfigItemDelegate = publicKey('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait delegateProgrammableConfigItemV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: programmableConfigItemDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Programmable Config Item delegate approved');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-programmable-config-item-approve",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
