/**
 * Example: swap_quote_buy
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n} from '@metaplex-foundation/genesis';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);",
  "main": "const SOL_IN = 1_000_000_000n; // 1 SOL in lamports\n\nconst buyQuote = getSwapResult(bucket, SOL_IN, 'buy');\n\nconsole.log('SOL input:  ', buyQuote.amountIn.toString(), 'lamports');\nconsole.log('Total fee:  ', buyQuote.fee.toString(), 'lamports');\nconsole.log('Tokens out: ', buyQuote.amountOut.toString());",
  "output": "// SOL input:   1000000000 lamports\n// Total fee:   10000000 lamports\n// Tokens out:  <calculated token amount>",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n} from '@metaplex-foundation/genesis';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);\n// [/SETUP]\n\n// [MAIN]\nconst SOL_IN = 1_000_000_000n; // 1 SOL in lamports\n\nconst buyQuote = getSwapResult(bucket, SOL_IN, 'buy');\n\nconsole.log('SOL input:  ', buyQuote.amountIn.toString(), 'lamports');\nconsole.log('Total fee:  ', buyQuote.fee.toString(), 'lamports');\nconsole.log('Tokens out: ', buyQuote.amountOut.toString());\n// [/MAIN]\n\n// [OUTPUT]\n// SOL input:   1000000000 lamports\n// Total fee:   10000000 lamports\n// Tokens out:  <calculated token amount>\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Get a buy quote without executing a swap (--info flag)\nmplx genesis swap <GENESIS_ACCOUNT> --info --buyAmount 1000000000\n"
}

export const metadata = {
  title: "swap_quote_buy",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
