/**
 * Example: wallet_allocations
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst contributorA = publicKey(process.env.RECIPIENT_1!)\nconst contributorB = publicKey(process.env.RECIPIENT_2!)",
  "main": "const allocations = [\n  { address: contributorA, amount: 1_000_000n, nonce: 0n },\n  { address: contributorB, amount: 2_500_000n, nonce: 0n },\n]\n\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\nconsole.log(root, proofs.length, treeHeight)",
  "output": "// Merkle root, two proofs, and treeHeight for the wallet allocations",
  "full": "// [IMPORTS]\nimport { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst contributorA = publicKey(process.env.RECIPIENT_1!)\nconst contributorB = publicKey(process.env.RECIPIENT_2!)\n// [/SETUP]\n\n// [MAIN]\nconst allocations = [\n  { address: contributorA, amount: 1_000_000n, nonce: 0n },\n  { address: contributorB, amount: 2_500_000n, nonce: 0n },\n]\n\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\nconsole.log(root, proofs.length, treeHeight)\n// [/MAIN]\n\n// [OUTPUT]\n// Merkle root, two proofs, and treeHeight for the wallet allocations\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "wallet_allocations",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
