/**
 * Example: delegate-locked-transfer-revoke
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getRevokeLockedTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst lockedTransferDelegate = address('delegateAddress...');",
  "main": "const revokeIx = await getRevokeLockedTransferV1InstructionAsync({\n  mint,\n  tokenOwner: owner.address,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [owner]);",
  "output": "console.log('Locked Transfer delegate revoked');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getRevokeLockedTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst lockedTransferDelegate = address('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst revokeIx = await getRevokeLockedTransferV1InstructionAsync({\n  mint,\n  tokenOwner: owner.address,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n});\n\nawait sendAndConfirm([revokeIx], [owner]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Locked Transfer delegate revoked');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  revokeLockedTransferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst owner = umi.identity;\nconst lockedTransferDelegate = publicKey('delegateAddress...');",
  "main": "await revokeLockedTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Locked Transfer delegate revoked');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  revokeLockedTransferV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst owner = umi.identity;\nconst lockedTransferDelegate = publicKey('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait revokeLockedTransferV1(umi, {\n  mint,\n  tokenOwner: owner.publicKey,\n  authority: owner,\n  delegate: lockedTransferDelegate,\n  tokenStandard: TokenStandard.ProgrammableNonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Locked Transfer delegate revoked');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-locked-transfer-revoke",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
