/**
 * Example: delegate-standard-transfer
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and standardDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address\nconst currentOwner = 'currentOwnerAddress...';\nconst newOwner = 'newOwnerAddress...';",
  "main": "// Transfer as Standard delegate\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  authority: standardDelegate,\n  payer: standardDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([transferIx], [standardDelegate]);",
  "output": "console.log('Asset transferred by Standard delegate');",
  "full": "// [IMPORTS]\nimport {\n  getTransferV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and standardDelegate are set up\n\nconst mintAddress = 'mintAddress...'; // The NFT mint address\nconst currentOwner = 'currentOwnerAddress...';\nconst newOwner = 'newOwnerAddress...';\n// [/SETUP]\n\n// [MAIN]\n// Transfer as Standard delegate\nconst transferIx = await getTransferV1InstructionAsync({\n  mint: mintAddress,\n  authority: standardDelegate,\n  payer: standardDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm([transferIx], [standardDelegate]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset transferred by Standard delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { transferV1 } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi, mint, standardDelegate, currentOwner, and newOwner are set up",
  "main": "await transferV1(umi, {\n  mint,\n  authority: standardDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Asset transferred by Standard delegate');",
  "full": "// [IMPORTS]\nimport { transferV1 } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi, mint, standardDelegate, currentOwner, and newOwner are set up\n// [/SETUP]\n\n// [MAIN]\nawait transferV1(umi, {\n  mint,\n  authority: standardDelegate,\n  tokenOwner: currentOwner,\n  destinationOwner: newOwner,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset transferred by Standard delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-standard-transfer",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
