/**
 * Example: fetch-asset
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport { fetchDigitalAsset } from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc is set up\n// See getting-started for full setup\n\nconst mintAddress = address('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');",
  "main": "// Fetch a digital asset by its mint address\nconst asset = await fetchDigitalAsset(rpc, mintAddress);",
  "output": "console.log('Asset:', asset.address);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\nconsole.log('Seller Fee:', asset.metadata.sellerFeeBasisPoints);\nif (asset.edition) {\n  console.log('Is Original:', asset.edition.isOriginal);\n}",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport { fetchDigitalAsset } from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc is set up\n// See getting-started for full setup\n\nconst mintAddress = address('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');\n// [/SETUP]\n\n// [MAIN]\n// Fetch a digital asset by its mint address\nconst asset = await fetchDigitalAsset(rpc, mintAddress);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset:', asset.address);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\nconsole.log('Seller Fee:', asset.metadata.sellerFeeBasisPoints);\nif (asset.edition) {\n  console.log('Is Original:', asset.edition.isOriginal);\n}\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAsset } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mintAddress = publicKey('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');",
  "main": "// Fetch a digital asset by its mint address\nconst asset = await fetchDigitalAsset(umi, mintAddress);",
  "output": "console.log('Asset:', asset.publicKey);\nconsole.log('Metadata:', asset.metadata.publicKey);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\nconsole.log('Seller Fee:', asset.metadata.sellerFeeBasisPoints);",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { fetchDigitalAsset } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n// See getting-started for full setup\n\nconst mintAddress = publicKey('Ay1U9DWphDgc7hq58Yj1yHabt91zTzvV2YJbAWkPNbaK');\n// [/SETUP]\n\n// [MAIN]\n// Fetch a digital asset by its mint address\nconst asset = await fetchDigitalAsset(umi, mintAddress);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset:', asset.publicKey);\nconsole.log('Metadata:', asset.metadata.publicKey);\nconsole.log('Name:', asset.metadata.name);\nconsole.log('URI:', asset.metadata.uri);\nconsole.log('Seller Fee:', asset.metadata.sellerFeeBasisPoints);\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-asset",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
