/**
 * Example: read_agent_check_registration
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  safeFetchAgentIdentityV1,\n  findAgentIdentityV1Pda,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(mplAgentIdentity())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')",
  "main": "const pda = findAgentIdentityV1Pda(umi, { asset: assetPublicKey })\nconst identity = await safeFetchAgentIdentityV1(umi, pda)\n\nconsole.log('Registered:', identity !== null)",
  "output": "// Registered: true",
  "full": "// [IMPORTS]\nimport {\n  safeFetchAgentIdentityV1,\n  findAgentIdentityV1Pda,\n  mplAgentIdentity,\n} from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(mplAgentIdentity())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\nconst pda = findAgentIdentityV1Pda(umi, { asset: assetPublicKey })\nconst identity = await safeFetchAgentIdentityV1(umi, pda)\n\nconsole.log('Registered:', identity !== null)\n// [/MAIN]\n\n// [OUTPUT]\n// Registered: true\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "read_agent_check_registration",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
