/**
 * Example: swap_buy
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n  applySlippage,\n  swapBondingCurveV2,\n  isSwappable,\n} from '@metaplex-foundation/genesis';\nimport { findAssociatedTokenPda } from '@metaplex-foundation/mpl-toolbox';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst baseMint = publicKey('TOKEN_MINT_PUBKEY');\nconst quoteMint = publicKey('So11111111111111111111111111111111111111112'); // wSOL\n\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);",
  "main": "if (!isSwappable(bucket)) throw new Error('Curve is not currently accepting swaps');\n\nconst SOL_IN = 1_000_000_000n; // 1 SOL in lamports\nconst quote = getSwapResult(bucket, SOL_IN, 'buy');\nconst minAmountOut = applySlippage(quote.amountOut, 100); // 1% slippage\n\nconst [userBaseTokenAccount] = findAssociatedTokenPda(umi, { mint: baseMint, owner: umi.identity.publicKey });\nconst [userQuoteTokenAccount] = findAssociatedTokenPda(umi, { mint: quoteMint, owner: umi.identity.publicKey });\n\n// NOTE: Fund the wSOL ATA before this call — see the wSOL Wrapping Note on this page.\nconst result = await swapBondingCurveV2(umi, {\n  genesisAccount,\n  bucketPda,\n  baseMint,\n  quoteMint,\n  userBaseTokenAccount,\n  userQuoteTokenAccount,\n  amountIn: quote.amountIn,\n  minAmountOut,\n  direction: 'buy',\n}).sendAndConfirm(umi);\n\nconsole.log('Buy confirmed:', result.signature);",
  "output": "// Buy confirmed: <base58 transaction signature>",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  findBondingCurveBucketV2Pda,\n  fetchBondingCurveBucketV2,\n  getSwapResult,\n  applySlippage,\n  swapBondingCurveV2,\n  isSwappable,\n} from '@metaplex-foundation/genesis';\nimport { findAssociatedTokenPda } from '@metaplex-foundation/mpl-toolbox';\nimport { publicKey } from '@metaplex-foundation/umi';\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis());\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT_PUBKEY');\nconst baseMint = publicKey('TOKEN_MINT_PUBKEY');\nconst quoteMint = publicKey('So11111111111111111111111111111111111111112'); // wSOL\n\nconst [bucketPda] = findBondingCurveBucketV2Pda(umi, { genesisAccount, bucketIndex: 0 });\nconst bucket = await fetchBondingCurveBucketV2(umi, bucketPda);\n// [/SETUP]\n\n// [MAIN]\nif (!isSwappable(bucket)) throw new Error('Curve is not currently accepting swaps');\n\nconst SOL_IN = 1_000_000_000n; // 1 SOL in lamports\nconst quote = getSwapResult(bucket, SOL_IN, 'buy');\nconst minAmountOut = applySlippage(quote.amountOut, 100); // 1% slippage\n\nconst [userBaseTokenAccount] = findAssociatedTokenPda(umi, { mint: baseMint, owner: umi.identity.publicKey });\nconst [userQuoteTokenAccount] = findAssociatedTokenPda(umi, { mint: quoteMint, owner: umi.identity.publicKey });\n\n// NOTE: Fund the wSOL ATA before this call — see the wSOL Wrapping Note on this page.\nconst result = await swapBondingCurveV2(umi, {\n  genesisAccount,\n  bucketPda,\n  baseMint,\n  quoteMint,\n  userBaseTokenAccount,\n  userQuoteTokenAccount,\n  amountIn: quote.amountIn,\n  minAmountOut,\n  direction: 'buy',\n}).sendAndConfirm(umi);\n\nconsole.log('Buy confirmed:', result.signature);\n// [/MAIN]\n\n// [OUTPUT]\n// Buy confirmed: <base58 transaction signature>\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Buy tokens — SOL is wrapped automatically\n# --buyAmount is in lamports (1 SOL = 1000000000)\nmplx genesis swap <GENESIS_ACCOUNT> --buyAmount 1000000000\n\n# With custom slippage (100 bps = 1%)\nmplx genesis swap <GENESIS_ACCOUNT> --buyAmount 1000000000 --slippage 100\n"
}

export const metadata = {
  title: "swap_buy",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
