/**
 * Example: prepare_distribution
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst allocations = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100n, nonce: 0n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 200n, nonce: 0n },\n]",
  "main": "const { root, proofs, treeHeight } = prepareDistribution(allocations)\nconsole.log(root, proofs, treeHeight)",
  "output": "// root, one proof array per allocation, and treeHeight",
  "full": "// [IMPORTS]\nimport { mplDistro, prepareDistribution } from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst allocations = [\n  { address: publicKey(process.env.RECIPIENT_1!), amount: 100n, nonce: 0n },\n  { address: publicKey(process.env.RECIPIENT_2!), amount: 200n, nonce: 0n },\n]\n// [/SETUP]\n\n// [MAIN]\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\nconsole.log(root, proofs, treeHeight)\n// [/MAIN]\n\n// [OUTPUT]\n// root, one proof array per allocation, and treeHeight\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "prepare_distribution",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
