/**
 * Example: remove-from-collection-as-delegate
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  fetchCollection,\n  collectionAddress,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'",
  "setup": "const assetId = publicKey('11111111111111111111111111111111')",
  "main": "const asset = await fetchAsset(umi, assetId)\n\nconst currentCollectionId = collectionAddress(asset)\nif (!currentCollectionId) {\n  throw new Error('Asset does not belong to a collection')\n}\nconst collection = await fetchCollection(umi, currentCollectionId)\n\n// collectionDelegate only needs to be in the Collection's UpdateDelegate additionalDelegates\nconst collectionDelegate = umi.identity // replace with your delegate signer if different\nawait update(umi, {\n  asset,\n  collection,\n  newUpdateAuthority: updateAuthority('Address', [umi.identity.publicKey]),\n  authority: collectionDelegate,\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset removed from collection')",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport {\n  update,\n  fetchAsset,\n  fetchCollection,\n  collectionAddress,\n  updateAuthority,\n} from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst assetId = publicKey('11111111111111111111111111111111')\n// [/SETUP]\n\n// [MAIN]\nconst asset = await fetchAsset(umi, assetId)\n\nconst currentCollectionId = collectionAddress(asset)\nif (!currentCollectionId) {\n  throw new Error('Asset does not belong to a collection')\n}\nconst collection = await fetchCollection(umi, currentCollectionId)\n\n// collectionDelegate only needs to be in the Collection's UpdateDelegate additionalDelegates\nconst collectionDelegate = umi.identity // replace with your delegate signer if different\nawait update(umi, {\n  asset,\n  collection,\n  newUpdateAuthority: updateAuthority('Address', [umi.identity.publicKey]),\n  authority: collectionDelegate,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset removed from collection')\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::{instructions::UpdateV2Builder, types::UpdateAuthority};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "let asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet collection = Pubkey::from_str(\"CollectionAddressHere...\").unwrap();\nlet new_authority = Pubkey::from_str(\"NewAuthorityHere...\").unwrap();\n\n// Signer only needs to be in the Collection's UpdateDelegate additionalDelegates\nlet update_ix = UpdateV2Builder::new()\n    .asset(asset)\n    .collection(Some(collection))\n    .payer(delegate.pubkey())\n    .authority(Some(delegate.pubkey()))\n    .new_update_authority(UpdateAuthority::Address(new_authority))\n    .instruction();",
  "output": "println!(\"Asset removed from collection\");",
  "full": "// [IMPORTS]\nuse mpl_core::{instructions::UpdateV2Builder, types::UpdateAuthority};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\nlet asset = Pubkey::from_str(\"AssetAddressHere...\").unwrap();\nlet collection = Pubkey::from_str(\"CollectionAddressHere...\").unwrap();\nlet new_authority = Pubkey::from_str(\"NewAuthorityHere...\").unwrap();\n\n// Signer only needs to be in the Collection's UpdateDelegate additionalDelegates\nlet update_ix = UpdateV2Builder::new()\n    .asset(asset)\n    .collection(Some(collection))\n    .payer(delegate.pubkey())\n    .authority(Some(delegate.pubkey()))\n    .new_update_authority(UpdateAuthority::Address(new_authority))\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Asset removed from collection\");\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "remove-from-collection-as-delegate",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

}
