/**
 * Example: add-asset-to-group
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport { addAssetsToGroup } from '@metaplex-foundation/mpl-core'",
  "setup": "const group = publicKey('GroupAddress...')\nconst asset = publicKey('AssetAddress...')",
  "main": "await addAssetsToGroup(umi, {\n  group,\n  authority: umi.identity,\n})\n  .addRemainingAccounts([\n    { pubkey: asset, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)",
  "output": "console.log('Asset added to group')",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { addAssetsToGroup } from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst group = publicKey('GroupAddress...')\nconst asset = publicKey('AssetAddress...')\n// [/SETUP]\n\n// [MAIN]\nawait addAssetsToGroup(umi, {\n  group,\n  authority: umi.identity,\n})\n  .addRemainingAccounts([\n    { pubkey: asset, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset added to group')\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "add-asset-to-group",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
