/**
 * Example: refund_launch_pool_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  refundLaunchPoolV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, launchPoolBucket, and baseMint from previous steps.\n// Only valid after the deposit window closed AND either the\n// minimumQuoteTokenThreshold was missed or the softCap was exceeded.",
  "main": "// The program computes the refundable amount, so there is no amount argument.\n// A missed threshold refunds the full deposit; an exceeded soft cap refunds\n// only the excess, leaving the depositor's token allocation intact.\nawait refundLaunchPoolV2(umi, {\n  genesisAccount,\n  bucket: launchPoolBucket,\n  baseMint: baseMint.publicKey,\n  recipient: umi.identity.publicKey,\n}).sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  refundLaunchPoolV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, launchPoolBucket, and baseMint from previous steps.\n// Only valid after the deposit window closed AND either the\n// minimumQuoteTokenThreshold was missed or the softCap was exceeded.\n// [/SETUP]\n\n// [MAIN]\n// The program computes the refundable amount, so there is no amount argument.\n// A missed threshold refunds the full deposit; an exceeded soft cap refunds\n// only the excess, leaving the depositor's token allocation intact.\nawait refundLaunchPoolV2(umi, {\n  genesisAccount,\n  bucket: launchPoolBucket,\n  baseMint: baseMint.publicKey,\n  recipient: umi.identity.publicKey,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "refund_launch_pool_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
