/**
 * Example: Custom API Base URL
 *
 * Agent targeting staging API
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { mintAgent, mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))",
  "main": "const result = await mintAgent(\n  umi,\n  { baseUrl: 'https://staging-api.metaplex.com' },\n  {\n    wallet: umi.identity.publicKey,\n    name: 'My Agent',\n    uri: 'https://example.com/metadata.json',\n    agentMetadata: {\n      type: 'agent',\n      name: 'My Agent',\n      description: 'Agent targeting staging API',\n      services: [],\n      registrations: [],\n      supportedTrust: [],\n    },\n  }\n)\n\nconsole.log('Asset address:', result.assetAddress)",
  "output": "// Asset address: <base58 address>",
  "full": "// [IMPORTS]\nimport { mintAgent, mplAgentIdentity } from '@metaplex-foundation/mpl-agent-registry'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplAgentIdentity())\n\nconst keypair = umi.eddsa.createKeypairFromSecretKey(mySecretKeyBytes)\numi.use(keypairIdentity(keypair))\n// [/SETUP]\n\n// [MAIN]\nconst result = await mintAgent(\n  umi,\n  { baseUrl: 'https://staging-api.metaplex.com' },\n  {\n    wallet: umi.identity.publicKey,\n    name: 'My Agent',\n    uri: 'https://example.com/metadata.json',\n    agentMetadata: {\n      type: 'agent',\n      name: 'My Agent',\n      description: 'Agent targeting staging API',\n      services: [],\n      registrations: [],\n      supportedTrust: [],\n    },\n  }\n)\n\nconsole.log('Asset address:', result.assetAddress)\n// [/MAIN]\n\n// [OUTPUT]\n// Asset address: <base58 address>\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Custom API Base URL",
  description: "Agent targeting staging API",
  tags: ['agents', 'custom-api', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
