/**
 * Example: Create an Asset
 *
 * Basic example of creating an NFT asset with Core
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { create } from '@metaplex-kit/core'",
  "setup": "// Initialize client\r\nconst client = createClient()",
  "main": "// Create a new NFT asset\r\nconst asset = await create({\r\n  name: 'My NFT',\r\n  uri: 'https://example.com/metadata.json'\r\n})",
  "output": "console.log('Asset created:', asset.publicKey)",
  "full": "// [IMPORTS]\r\nimport { create } from '@metaplex-kit/core'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize client\r\nconst client = createClient()\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Create a new NFT asset\r\nconst asset = await create({\r\n  name: 'My NFT',\r\n  uri: 'https://example.com/metadata.json'\r\n})\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Asset created:', asset.publicKey)\r\n// [/OUTPUT]\r\n"
}

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { create } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'",
  "setup": "// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())",
  "main": "// Create a new NFT asset\r\nconst asset = await create(umi, {\r\n  name: 'My NFT',\r\n  uri: 'https://example.com/metadata.json'\r\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset created:', asset.publicKey)",
  "full": "// [IMPORTS]\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { create } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Create a new NFT asset\r\nconst asset = await create(umi, {\r\n  name: 'My NFT',\r\n  uri: 'https://example.com/metadata.json'\r\n}).sendAndConfirm(umi)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Asset created:', asset.publicKey)\r\n// [/OUTPUT]\r\n"
}

const shankSections = {
  "imports": "use mpl_core::instructions::CreateV1;\r\nuse solana_sdk::signer::Signer;",
  "setup": "",
  "main": "// Create a new NFT asset\r\nlet create_ix = CreateV1 {\r\n    name: \"My NFT\".to_string(),\r\n    uri: \"https://example.com/metadata.json\".to_string(),\r\n    ..Default::default()\r\n};\r\n\r\nlet instruction = create_ix.instruction();",
  "output": "println!(\"Asset instruction created\");",
  "full": "// [IMPORTS]\r\nuse mpl_core::instructions::CreateV1;\r\nuse solana_sdk::signer::Signer;\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\n// Create a new NFT asset\r\nlet create_ix = CreateV1 {\r\n    name: \"My NFT\".to_string(),\r\n    uri: \"https://example.com/metadata.json\".to_string(),\r\n    ..Default::default()\r\n};\r\n\r\nlet instruction = create_ix.instruction();\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nprintln!(\"Asset instruction created\");\r\n// [/OUTPUT]\r\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;",
  "setup": "",
  "main": "declare_id!(\"Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS\");\r\n\r\n#[program]\r\npub mod create_asset {\r\n    use super::*;\r\n\r\n    // Create a new NFT asset\r\n    pub fn create(\r\n        ctx: Context<CreateAsset>,\r\n        name: String,\r\n        uri: String\r\n    ) -> Result<()> {\r\n        let asset = &mut ctx.accounts.asset;\r\n        asset.name = name;\r\n        asset.uri = uri;\r\n        asset.owner = ctx.accounts.owner.key();\r\n\r\n        msg!(\"Asset created: {}\", asset.key());\r\n        Ok(())\r\n    }\r\n}\r\n\r\n#[derive(Accounts)]\r\npub struct CreateAsset<'info> {\r\n    #[account(init, payer = owner, space = 8 + 200)]\r\n    pub asset: Account<'info, Asset>,\r\n    #[account(mut)]\r\n    pub owner: Signer<'info>,\r\n    pub system_program: Program<'info, System>,\r\n}\r\n\r\n#[account]\r\npub struct Asset {\r\n    pub name: String,\r\n    pub uri: String,\r\n    pub owner: Pubkey,\r\n}",
  "output": "",
  "full": "// [IMPORTS]\r\nuse anchor_lang::prelude::*;\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\ndeclare_id!(\"Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS\");\r\n\r\n#[program]\r\npub mod create_asset {\r\n    use super::*;\r\n\r\n    // Create a new NFT asset\r\n    pub fn create(\r\n        ctx: Context<CreateAsset>,\r\n        name: String,\r\n        uri: String\r\n    ) -> Result<()> {\r\n        let asset = &mut ctx.accounts.asset;\r\n        asset.name = name;\r\n        asset.uri = uri;\r\n        asset.owner = ctx.accounts.owner.key();\r\n\r\n        msg!(\"Asset created: {}\", asset.key());\r\n        Ok(())\r\n    }\r\n}\r\n\r\n#[derive(Accounts)]\r\npub struct CreateAsset<'info> {\r\n    #[account(init, payer = owner, space = 8 + 200)]\r\n    pub asset: Account<'info, Asset>,\r\n    #[account(mut)]\r\n    pub owner: Signer<'info>,\r\n    pub system_program: Program<'info, System>,\r\n}\r\n\r\n#[account]\r\npub struct Asset {\r\n    pub name: String,\r\n    pub uri: String,\r\n    pub owner: Pubkey,\r\n}\r\n// [/MAIN]\r\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Create an NFT using the Metaplex CLI\r\n\r\n# Interactive wizard mode (recommended)\r\nmplx core asset create --wizard\r\n\r\n# Simple creation with name and URI\r\nmplx core asset create --name \"My NFT\" --uri \"https://example.com/metadata.json\"\r\n\r\n# Create with files (image + metadata)\r\nmplx core asset create --files --image \"./my-nft.png\" --json \"./metadata.json\"\r\n"
}

export const metadata = {
  title: "Create an Asset",
  description: "Basic example of creating an NFT asset with Core",
  tags: ['core', 'nft', 'create', 'beginner'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
