/**
 * Example: nest-groups
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { addGroupsToGroup } from '@metaplex-foundation/mpl-core'",
  "setup": "// parentGroup and childGroup are existing GroupV1 accounts",
  "main": "await addGroupsToGroup(umi, {\n  parentGroup: parentGroup.publicKey,\n  groups: [childGroup.publicKey],\n  authority: umi.identity,\n})\n  .addRemainingAccounts([\n    { pubkey: childGroup.publicKey, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)",
  "output": "console.log('Child group nested under parent')",
  "full": "// [IMPORTS]\nimport { addGroupsToGroup } from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\n// parentGroup and childGroup are existing GroupV1 accounts\n// [/SETUP]\n\n// [MAIN]\nawait addGroupsToGroup(umi, {\n  parentGroup: parentGroup.publicKey,\n  groups: [childGroup.publicKey],\n  authority: umi.identity,\n})\n  .addRemainingAccounts([\n    { pubkey: childGroup.publicKey, isSigner: false, isWritable: true },\n  ])\n  .sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Child group nested under parent')\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "nest-groups",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
