/**
 * Example: create-fungible-asset
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { generateKeyPairSigner } from '@solana/signers';\nimport { createFungibleAsset } from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, and sendAndConfirm are set up\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet",
  "main": "// Create a FungibleAsset (SFT - mint tokens separately later)\nconst createIx = await createFungibleAsset({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My Fungible Asset',\n  uri: 'https://example.com/my-fungible-asset.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  // decimals: 0, // Optional: FungibleAssets typically have 0 decimals\n});\n\nawait sendAndConfirm([createIx], [mint, authority]);",
  "output": "console.log('Fungible Asset created:', mint.address);\n// Mint tokens using getMintV1InstructionAsync",
  "full": "// [IMPORTS]\nimport { generateKeyPairSigner } from '@solana/signers';\nimport { createFungibleAsset } from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, and sendAndConfirm are set up\n\nconst mint = await generateKeyPairSigner();\nconst authority = await generateKeyPairSigner(); // Your wallet\n// [/SETUP]\n\n// [MAIN]\n// Create a FungibleAsset (SFT - mint tokens separately later)\nconst createIx = await createFungibleAsset({\n  mint,\n  authority,\n  payer: authority,\n  name: 'My Fungible Asset',\n  uri: 'https://example.com/my-fungible-asset.json',\n  sellerFeeBasisPoints: 550, // 5.5%\n  // decimals: 0, // Optional: FungibleAssets typically have 0 decimals\n});\n\nawait sendAndConfirm([createIx], [mint, authority]);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Fungible Asset created:', mint.address);\n// Mint tokens using getMintV1InstructionAsync\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { percentAmount, generateSigner, some } from '@metaplex-foundation/umi';\nimport { createFungibleAsset } from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mint = generateSigner(umi);",
  "main": "// Create a FungibleAsset (SFT - mint tokens separately later)\nawait createFungibleAsset(umi, {\n  mint,\n  name: 'My Fungible Asset',\n  uri: 'https://example.com/my-fungible-asset.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  decimals: some(0), // FungibleAssets typically have 0 decimals\n}).sendAndConfirm(umi);",
  "output": "console.log('Fungible Asset created:', mint.publicKey);\n// Mint tokens using mintV1",
  "full": "// [IMPORTS]\nimport { percentAmount, generateSigner, some } from '@metaplex-foundation/umi';\nimport { createFungibleAsset } from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming umi is set up with mplTokenMetadata plugin\n\nconst mint = generateSigner(umi);\n// [/SETUP]\n\n// [MAIN]\n// Create a FungibleAsset (SFT - mint tokens separately later)\nawait createFungibleAsset(umi, {\n  mint,\n  name: 'My Fungible Asset',\n  uri: 'https://example.com/my-fungible-asset.json',\n  sellerFeeBasisPoints: percentAmount(5.5),\n  decimals: some(0), // FungibleAssets typically have 0 decimals\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Fungible Asset created:', mint.publicKey);\n// Mint tokens using mintV1\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "create-fungible-asset",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
