/**
 * Example: Create Asset with Plugins
 *
 * Example of creating an NFT asset with plugins at creation time
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { create, ruleSet } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'\r\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n\r\nconst creator = publicKey('YOUR_CREATOR_ADDRESS')",
  "main": "// Generate a new keypair for the asset\r\nconst assetSigner = generateSigner(umi)\r\n\r\n// Create asset with Royalties plugin\r\nawait create(umi, {\r\n  asset: assetSigner,\r\n  name: 'NFT with Royalties',\r\n  uri: 'https://example.com/metadata.json',\r\n  plugins: [\r\n    {\r\n      type: 'Royalties',\r\n      basisPoints: 500, // 5%\r\n      creators: [\r\n        { address: creator, percentage: 100 },\r\n      ],\r\n      ruleSet: ruleSet('None'),\r\n    },\r\n  ],\r\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset created with plugins:', assetSigner.publicKey)",
  "full": "// [IMPORTS]\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { create, ruleSet } from '@metaplex-foundation/mpl-core'\r\nimport { mplCore } from '@metaplex-foundation/mpl-core'\r\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n\r\nconst creator = publicKey('YOUR_CREATOR_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Generate a new keypair for the asset\r\nconst assetSigner = generateSigner(umi)\r\n\r\n// Create asset with Royalties plugin\r\nawait create(umi, {\r\n  asset: assetSigner,\r\n  name: 'NFT with Royalties',\r\n  uri: 'https://example.com/metadata.json',\r\n  plugins: [\r\n    {\r\n      type: 'Royalties',\r\n      basisPoints: 500, // 5%\r\n      creators: [\r\n        { address: creator, percentage: 100 },\r\n      ],\r\n      ruleSet: ruleSet('None'),\r\n    },\r\n  ],\r\n}).sendAndConfirm(umi)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Asset created with plugins:', assetSigner.publicKey)\r\n// [/OUTPUT]\r\n"
}

const shankSections = {
  "imports": "use mpl_core::{\r\n    instructions::CreateV1Builder,\r\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\r\n};\r\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Create asset with Royalties plugin\r\nlet create_ix = CreateV1Builder::new()\r\n    .asset(asset.pubkey())\r\n    .payer(payer.pubkey())\r\n    .name(\"NFT with Royalties\".to_string())\r\n    .uri(\"https://example.com/metadata.json\".to_string())\r\n    .plugins(vec![PluginAuthorityPair {\r\n        plugin: Plugin::Royalties(Royalties {\r\n            basis_points: 500, // 5%\r\n            creators: vec![Creator {\r\n                address: creator_pubkey,\r\n                percentage: 100,\r\n            }],\r\n            rule_set: RuleSet::None,\r\n        }),\r\n        authority: Some(PluginAuthority::None),\r\n    }])\r\n    .instruction();",
  "output": "println!(\"Asset created with plugins\");",
  "full": "// [IMPORTS]\r\nuse mpl_core::{\r\n    instructions::CreateV1Builder,\r\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\r\n};\r\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\n// Create asset with Royalties plugin\r\nlet create_ix = CreateV1Builder::new()\r\n    .asset(asset.pubkey())\r\n    .payer(payer.pubkey())\r\n    .name(\"NFT with Royalties\".to_string())\r\n    .uri(\"https://example.com/metadata.json\".to_string())\r\n    .plugins(vec![PluginAuthorityPair {\r\n        plugin: Plugin::Royalties(Royalties {\r\n            basis_points: 500, // 5%\r\n            creators: vec![Creator {\r\n                address: creator_pubkey,\r\n                percentage: 100,\r\n            }],\r\n            rule_set: RuleSet::None,\r\n        }),\r\n        authority: Some(PluginAuthority::None),\r\n    }])\r\n    .instruction();\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nprintln!(\"Asset created with plugins\");\r\n// [/OUTPUT]\r\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\r\nuse mpl_core::{\r\n    instructions::CreateV1CpiBuilder,\r\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\r\n};",
  "setup": "",
  "main": "// Create asset with Royalties plugin via CPI\r\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\r\n    .asset(&ctx.accounts.asset)\r\n    .payer(&ctx.accounts.payer)\r\n    .system_program(&ctx.accounts.system_program)\r\n    .name(\"NFT with Royalties\".to_string())\r\n    .uri(\"https://example.com/metadata.json\".to_string())\r\n    .plugins(vec![PluginAuthorityPair {\r\n        plugin: Plugin::Royalties(Royalties {\r\n            basis_points: 500, // 5%\r\n            creators: vec![Creator {\r\n                address: ctx.accounts.creator.key(),\r\n                percentage: 100,\r\n            }],\r\n            rule_set: RuleSet::None,\r\n        }),\r\n        authority: Some(PluginAuthority::None),\r\n    }])\r\n    .invoke()?;",
  "output": "msg!(\"Asset created with plugins: {}\", ctx.accounts.asset.key());",
  "full": "// [IMPORTS]\r\nuse anchor_lang::prelude::*;\r\nuse mpl_core::{\r\n    instructions::CreateV1CpiBuilder,\r\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\r\n};\r\n// [/IMPORTS]\r\n\r\n// [MAIN]\r\n// Create asset with Royalties plugin via CPI\r\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\r\n    .asset(&ctx.accounts.asset)\r\n    .payer(&ctx.accounts.payer)\r\n    .system_program(&ctx.accounts.system_program)\r\n    .name(\"NFT with Royalties\".to_string())\r\n    .uri(\"https://example.com/metadata.json\".to_string())\r\n    .plugins(vec![PluginAuthorityPair {\r\n        plugin: Plugin::Royalties(Royalties {\r\n            basis_points: 500, // 5%\r\n            creators: vec![Creator {\r\n                address: ctx.accounts.creator.key(),\r\n                percentage: 100,\r\n            }],\r\n            rule_set: RuleSet::None,\r\n        }),\r\n        authority: Some(PluginAuthority::None),\r\n    }])\r\n    .invoke()?;\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nmsg!(\"Asset created with plugins: {}\", ctx.accounts.asset.key());\r\n// [/OUTPUT]\r\n"
}

export const metadata = {
  title: "Create Asset with Plugins",
  description: "Example of creating an NFT asset with plugins at creation time",
  tags: ['core', 'nft', 'plugin', 'royalties', 'create', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
