/**
 * Example: Create Asset with Plugins
 *
 * Example of creating an NFT asset with plugins at creation time
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { create, ruleSet } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'",
  "setup": "// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst creator = publicKey('YOUR_CREATOR_ADDRESS')",
  "main": "// Generate a new keypair for the asset\nconst assetSigner = generateSigner(umi)\n\n// Create asset with Royalties plugin\nawait create(umi, {\n  asset: assetSigner,\n  name: 'NFT with Royalties',\n  uri: 'https://example.com/metadata.json',\n  plugins: [\n    {\n      type: 'Royalties',\n      basisPoints: 500, // 5%\n      creators: [\n        { address: creator, percentage: 100 },\n      ],\n      ruleSet: ruleSet('None'),\n    },\n  ],\n}).sendAndConfirm(umi)",
  "output": "console.log('Asset created with plugins:', assetSigner.publicKey)",
  "full": "// [IMPORTS]\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { create, ruleSet } from '@metaplex-foundation/mpl-core'\nimport { mplCore } from '@metaplex-foundation/mpl-core'\nimport { generateSigner, publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize UMI\nconst umi = createUmi('https://api.devnet.solana.com')\n  .use(mplCore())\n\nconst creator = publicKey('YOUR_CREATOR_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\n// Generate a new keypair for the asset\nconst assetSigner = generateSigner(umi)\n\n// Create asset with Royalties plugin\nawait create(umi, {\n  asset: assetSigner,\n  name: 'NFT with Royalties',\n  uri: 'https://example.com/metadata.json',\n  plugins: [\n    {\n      type: 'Royalties',\n      basisPoints: 500, // 5%\n      creators: [\n        { address: creator, percentage: 100 },\n      ],\n      ruleSet: ruleSet('None'),\n    },\n  ],\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset created with plugins:', assetSigner.publicKey)\n// [/OUTPUT]\n"
}

const shankSections = {
  "imports": "use mpl_core::{\n    instructions::CreateV1Builder,\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\n};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};",
  "setup": "",
  "main": "// Create asset with Royalties plugin\nlet create_ix = CreateV1Builder::new()\n    .asset(asset.pubkey())\n    .payer(payer.pubkey())\n    .name(\"NFT with Royalties\".to_string())\n    .uri(\"https://example.com/metadata.json\".to_string())\n    .plugins(vec![PluginAuthorityPair {\n        plugin: Plugin::Royalties(Royalties {\n            basis_points: 500, // 5%\n            creators: vec![Creator {\n                address: creator_pubkey,\n                percentage: 100,\n            }],\n            rule_set: RuleSet::None,\n        }),\n        authority: Some(PluginAuthority::None),\n    }])\n    .instruction();",
  "output": "println!(\"Asset created with plugins\");",
  "full": "// [IMPORTS]\nuse mpl_core::{\n    instructions::CreateV1Builder,\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\n};\nuse solana_sdk::{pubkey::Pubkey, signer::Signer};\n// [/IMPORTS]\n\n// [MAIN]\n// Create asset with Royalties plugin\nlet create_ix = CreateV1Builder::new()\n    .asset(asset.pubkey())\n    .payer(payer.pubkey())\n    .name(\"NFT with Royalties\".to_string())\n    .uri(\"https://example.com/metadata.json\".to_string())\n    .plugins(vec![PluginAuthorityPair {\n        plugin: Plugin::Royalties(Royalties {\n            basis_points: 500, // 5%\n            creators: vec![Creator {\n                address: creator_pubkey,\n                percentage: 100,\n            }],\n            rule_set: RuleSet::None,\n        }),\n        authority: Some(PluginAuthority::None),\n    }])\n    .instruction();\n// [/MAIN]\n\n// [OUTPUT]\nprintln!(\"Asset created with plugins\");\n// [/OUTPUT]\n"
}

const anchorSections = {
  "imports": "use anchor_lang::prelude::*;\nuse mpl_core::{\n    instructions::CreateV1CpiBuilder,\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\n};",
  "setup": "",
  "main": "// Create asset with Royalties plugin via CPI\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"NFT with Royalties\".to_string())\n    .uri(\"https://example.com/metadata.json\".to_string())\n    .plugins(vec![PluginAuthorityPair {\n        plugin: Plugin::Royalties(Royalties {\n            basis_points: 500, // 5%\n            creators: vec![Creator {\n                address: ctx.accounts.creator.key(),\n                percentage: 100,\n            }],\n            rule_set: RuleSet::None,\n        }),\n        authority: Some(PluginAuthority::None),\n    }])\n    .invoke()?;",
  "output": "msg!(\"Asset created with plugins: {}\", ctx.accounts.asset.key());",
  "full": "// [IMPORTS]\nuse anchor_lang::prelude::*;\nuse mpl_core::{\n    instructions::CreateV1CpiBuilder,\n    types::{Plugin, PluginAuthority, PluginAuthorityPair, Royalties, Creator, RuleSet},\n};\n// [/IMPORTS]\n\n// [MAIN]\n// Create asset with Royalties plugin via CPI\nCreateV1CpiBuilder::new(&ctx.accounts.mpl_core_program)\n    .asset(&ctx.accounts.asset)\n    .payer(&ctx.accounts.payer)\n    .system_program(&ctx.accounts.system_program)\n    .name(\"NFT with Royalties\".to_string())\n    .uri(\"https://example.com/metadata.json\".to_string())\n    .plugins(vec![PluginAuthorityPair {\n        plugin: Plugin::Royalties(Royalties {\n            basis_points: 500, // 5%\n            creators: vec![Creator {\n                address: ctx.accounts.creator.key(),\n                percentage: 100,\n            }],\n            rule_set: RuleSet::None,\n        }),\n        authority: Some(PluginAuthority::None),\n    }])\n    .invoke()?;\n// [/MAIN]\n\n// [OUTPUT]\nmsg!(\"Asset created with plugins: {}\", ctx.accounts.asset.key());\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Create Asset with Plugins",
  description: "Example of creating an NFT asset with plugins at creation time",
  tags: ['core', 'nft', 'plugin', 'royalties', 'create', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  shank: {
    framework: 'Shank',
    language: 'rust',
    code: shankSections.full,
    sections: shankSections,
  },

  anchor: {
    framework: 'Anchor',
    language: 'rust',
    code: anchorSections.full,
    sections: anchorSections,
  },

}
