/**
 * Example: fetch_claim_schedule_bucket_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  fetchClaimScheduleBucketV2,\n  findClaimScheduleBucketV2Pda,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst [vestingBucket] = findClaimScheduleBucketV2Pda(umi, {\n  genesisAccount,\n  bucketIndex: 0,\n})",
  "main": "const account = await fetchClaimScheduleBucketV2(umi, vestingBucket)",
  "output": "console.log('Recipient:', account.recipient)\nconsole.log('Allocation:', account.bucket.baseTokenAllocation)\nconsole.log('Remaining balance:', account.bucket.baseTokenBalance)\nconsole.log('Claimed:', account.amountClaimed)\nconsole.log('Paused:', account.paused)\nconsole.log('Total seconds paused:', account.totalSecondsPaused)",
  "full": "// [IMPORTS]\nimport {\n  fetchClaimScheduleBucketV2,\n  findClaimScheduleBucketV2Pda,\n  genesis,\n} from '@metaplex-foundation/genesis'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(genesis())\n\nconst genesisAccount = publicKey('YOUR_GENESIS_ACCOUNT')\nconst [vestingBucket] = findClaimScheduleBucketV2Pda(umi, {\n  genesisAccount,\n  bucketIndex: 0,\n})\n// [/SETUP]\n\n// [MAIN]\nconst account = await fetchClaimScheduleBucketV2(umi, vestingBucket)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Recipient:', account.recipient)\nconsole.log('Allocation:', account.bucket.baseTokenAllocation)\nconsole.log('Remaining balance:', account.bucket.baseTokenBalance)\nconsole.log('Claimed:', account.amountClaimed)\nconsole.log('Paused:', account.paused)\nconsole.log('Total seconds paused:', account.totalSecondsPaused)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch_claim_schedule_bucket_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
