/**
 * Example: fetch-groups-by-authority
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi'\nimport { getGroupV1GpaBuilder, Key } from '@metaplex-foundation/mpl-core'",
  "setup": "const updateAuthority = publicKey('UpdateAuthorityAddress...')",
  "main": "const groups = await getGroupV1GpaBuilder(umi)\n  .whereField('updateAuthority', updateAuthority)\n  .whereField('key', Key.GroupV1)\n  .getDeserialized()",
  "output": "for (const group of groups) {\n  console.log(group.publicKey, group.name)\n}",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { getGroupV1GpaBuilder, Key } from '@metaplex-foundation/mpl-core'\n// [/IMPORTS]\n\n// [SETUP]\nconst updateAuthority = publicKey('UpdateAuthorityAddress...')\n// [/SETUP]\n\n// [MAIN]\nconst groups = await getGroupV1GpaBuilder(umi)\n  .whereField('updateAuthority', updateAuthority)\n  .whereField('key', Key.GroupV1)\n  .getDeserialized()\n// [/MAIN]\n\n// [OUTPUT]\nfor (const group of groups) {\n  console.log(group.publicKey, group.name)\n}\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "fetch-groups-by-authority",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
