/**
 * Example: delegate-programmable-config-item-update
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getUpdateAsProgrammableConfigItemDelegateV2InstructionAsync,\n  findAssociatedTokenPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst assetOwner = address('ownerAddress...');\nconst ruleSet = address('ruleSetAddress...');",
  "main": "const [token] = await findAssociatedTokenPda({ mint, owner: assetOwner });\nconst updateIx = await getUpdateAsProgrammableConfigItemDelegateV2InstructionAsync({\n  mint,\n  token,\n  authority: programmableConfigItemDelegate,\n  ruleSet: { __kind: 'Set', fields: [ruleSet] },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: programmableConfigItemDelegate,\n});",
  "output": "console.log('Rule set updated via Programmable Config Item delegate');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getUpdateAsProgrammableConfigItemDelegateV2InstructionAsync,\n  findAssociatedTokenPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst assetOwner = address('ownerAddress...');\nconst ruleSet = address('ruleSetAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst [token] = await findAssociatedTokenPda({ mint, owner: assetOwner });\nconst updateIx = await getUpdateAsProgrammableConfigItemDelegateV2InstructionAsync({\n  mint,\n  token,\n  authority: programmableConfigItemDelegate,\n  ruleSet: { __kind: 'Set', fields: [ruleSet] },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: programmableConfigItemDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Rule set updated via Programmable Config Item delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsProgrammableConfigItemDelegateV2,\n  ruleSetToggle,\n} from '@metaplex-foundation/mpl-token-metadata';\nimport { findAssociatedTokenPda } from '@metaplex-foundation/mpl-toolbox';",
  "setup": "const mint = publicKey('mintAddress...');\nconst assetOwner = publicKey('ownerAddress...');\nconst programmableConfigItemDelegate = umi.identity; // The delegate authority\nconst ruleSet = publicKey('ruleSetAddress...');",
  "main": "await updateAsProgrammableConfigItemDelegateV2(umi, {\n  mint,\n  token: findAssociatedTokenPda(umi, { mint, owner: assetOwner }),\n  authority: programmableConfigItemDelegate,\n  ruleSet: ruleSetToggle('Set', [ruleSet]),\n}).sendAndConfirm(umi);",
  "output": "console.log('Rule set updated via Programmable Config Item delegate');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsProgrammableConfigItemDelegateV2,\n  ruleSetToggle,\n} from '@metaplex-foundation/mpl-token-metadata';\nimport { findAssociatedTokenPda } from '@metaplex-foundation/mpl-toolbox';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst assetOwner = publicKey('ownerAddress...');\nconst programmableConfigItemDelegate = umi.identity; // The delegate authority\nconst ruleSet = publicKey('ruleSetAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait updateAsProgrammableConfigItemDelegateV2(umi, {\n  mint,\n  token: findAssociatedTokenPda(umi, { mint, owner: assetOwner }),\n  authority: programmableConfigItemDelegate,\n  ruleSet: ruleSetToggle('Set', [ruleSet]),\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Rule set updated via Programmable Config Item delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-programmable-config-item-update",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
