/**
 * Example: Update Fungible Token Metadata
 *
 * Update the metadata of a fungible token
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import {\n  getUpdateV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint",
  "main": "// Update the fungible token metadata\nconst updateIx = await getUpdateV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  // Specify fields to update (creators must be explicitly set, use null to keep existing)\n  data: {\n    name: 'Updated Token Name',\n    symbol: 'UTN',\n    uri: 'https://example.com/updated-metadata.json',\n    sellerFeeBasisPoints: 0,\n    creators: null, // Keep existing creators\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: authority,\n});",
  "output": "console.log('Token metadata updated successfully');\nconsole.log('Mint:', mintAddress);\nconsole.log('New name:', 'Updated Token Name');",
  "full": "// [IMPORTS]\nimport {\n  getUpdateV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\n// Assuming rpc, rpcSubscriptions, sendAndConfirm, and authority are set up\n// See getting-started for full setup\n\nconst mintAddress = 'YOUR_TOKEN_MINT_ADDRESS'; // Your fungible token mint\n// [/SETUP]\n\n// [MAIN]\n// Update the fungible token metadata\nconst updateIx = await getUpdateV1InstructionAsync({\n  mint: mintAddress,\n  authority,\n  payer: authority,\n  // Specify fields to update (creators must be explicitly set, use null to keep existing)\n  data: {\n    name: 'Updated Token Name',\n    symbol: 'UTN',\n    uri: 'https://example.com/updated-metadata.json',\n    sellerFeeBasisPoints: 0,\n    creators: null, // Keep existing creators\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: authority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Token metadata updated successfully');\nconsole.log('Mint:', mintAddress);\nconsole.log('New name:', 'Updated Token Name');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "// npm install @metaplex-foundation/mpl-token-metadata @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n  fetchDigitalAsset,\n  mplTokenMetadata,\n  updateV1,\n} from '@metaplex-foundation/mpl-token-metadata'\nimport {\n  keypairIdentity,\n  publicKey,\n} from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { readFileSync } from 'fs'",
  "setup": "// Initialize Umi with your RPC endpoint\nconst umi = createUmi('https://api.devnet.solana.com').use(mplTokenMetadata())\n\n// Load your wallet keypair (must be the update authority)\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address\nconst mintAddress = publicKey('<your token mint address>')",
  "main": "// Fetch existing token data\nconst asset = await fetchDigitalAsset(umi, mintAddress)\n\n// Update the token metadata (name, symbol, and URI)\nawait updateV1(umi, {\n  mint: mintAddress,\n  authority: umi.identity,\n  data: {\n    ...asset.metadata,\n    name: 'Updated Token Name',\n    symbol: 'UTN',\n    uri: 'https://example.com/updated-metadata.json',\n  },\n}).sendAndConfirm(umi)",
  "output": "console.log('Token metadata updated successfully')\nconsole.log('Mint:', mintAddress)\nconsole.log('New name:', 'Updated Token Name')\nconsole.log('New URI:', 'https://example.com/updated-metadata.json')",
  "full": "// [IMPORTS]\n// npm install @metaplex-foundation/mpl-token-metadata @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults\nimport {\n  fetchDigitalAsset,\n  mplTokenMetadata,\n  updateV1,\n} from '@metaplex-foundation/mpl-token-metadata'\nimport {\n  keypairIdentity,\n  publicKey,\n} from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { readFileSync } from 'fs'\n// [/IMPORTS]\n\n// [SETUP]\n// Initialize Umi with your RPC endpoint\nconst umi = createUmi('https://api.devnet.solana.com').use(mplTokenMetadata())\n\n// Load your wallet keypair (must be the update authority)\nconst wallet = '<your wallet file path>'\nconst secretKey = JSON.parse(readFileSync(wallet, 'utf-8'))\nconst keypair = umi.eddsa.createKeypairFromSecretKey(new Uint8Array(secretKey))\numi.use(keypairIdentity(keypair))\n\n// Your token mint address\nconst mintAddress = publicKey('<your token mint address>')\n// [/SETUP]\n\n// [MAIN]\n// Fetch existing token data\nconst asset = await fetchDigitalAsset(umi, mintAddress)\n\n// Update the token metadata (name, symbol, and URI)\nawait updateV1(umi, {\n  mint: mintAddress,\n  authority: umi.identity,\n  data: {\n    ...asset.metadata,\n    name: 'Updated Token Name',\n    symbol: 'UTN',\n    uri: 'https://example.com/updated-metadata.json',\n  },\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Token metadata updated successfully')\nconsole.log('Mint:', mintAddress)\nconsole.log('New name:', 'Updated Token Name')\nconsole.log('New URI:', 'https://example.com/updated-metadata.json')\n// [/OUTPUT]\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Update Token Metadata using the Metaplex CLI\n\n# Interactive editor mode (opens metadata JSON in your default editor)\nmplx toolbox token update <MINT_ADDRESS> --editor\n\n# Update specific fields via flags\nmplx toolbox token update <MINT_ADDRESS> --name \"New Token Name\"\nmplx toolbox token update <MINT_ADDRESS> --symbol \"NEW\"\nmplx toolbox token update <MINT_ADDRESS> --description \"Updated description\"\n\n# Update with new image\nmplx toolbox token update <MINT_ADDRESS> --image ./new-image.png\n\n# Update multiple fields at once\nmplx toolbox token update <MINT_ADDRESS> \\\n  --name \"Updated Token\" \\\n  --symbol \"UPD\" \\\n  --description \"An updated token description\" \\\n  --image ./updated-image.png\n\n# Note: You must be the update authority to update token metadata\n# Note: --editor flag cannot be combined with other update flags\n"
}

export const metadata = {
  title: "Update Fungible Token Metadata",
  description: "Update the metadata of a fungible token",
  tags: ['token-metadata', 'fungible', 'spl-token', 'update', 'beginner'],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

}
