/**
 * Example: legacy_nft_allocations
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  DistributionType,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst nftMintA = publicKey(process.env.LEGACY_NFT_MINT_A!)\nconst nftMintB = publicKey(process.env.LEGACY_NFT_MINT_B!)",
  "main": "const allocations = [\n  { address: nftMintA, amount: 100_000n },\n  { address: nftMintB, amount: 100_000n },\n]\n\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\n\nconst distributionFields = {\n  merkleRoot: root,\n  treeHeight,\n  totalClaimants: BigInt(allocations.length),\n  distributionType: DistributionType.LegacyNft,\n}\n\nconsole.log(distributionFields, proofs.length)",
  "output": "// Root, treeHeight, and LegacyNft fields for createDistribution",
  "full": "// [IMPORTS]\nimport {\n  DistributionType,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst nftMintA = publicKey(process.env.LEGACY_NFT_MINT_A!)\nconst nftMintB = publicKey(process.env.LEGACY_NFT_MINT_B!)\n// [/SETUP]\n\n// [MAIN]\nconst allocations = [\n  { address: nftMintA, amount: 100_000n },\n  { address: nftMintB, amount: 100_000n },\n]\n\nconst { root, proofs, treeHeight } = prepareDistribution(allocations)\n\nconst distributionFields = {\n  merkleRoot: root,\n  treeHeight,\n  totalClaimants: BigInt(allocations.length),\n  distributionType: DistributionType.LegacyNft,\n}\n\nconsole.log(distributionFields, proofs.length)\n// [/MAIN]\n\n// [OUTPUT]\n// Root, treeHeight, and LegacyNft fields for createDistribution\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "legacy_nft_allocations",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
