/**
 * Example: claim_presale_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  claimPresaleV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, presaleBucket, and baseMint from previous steps.",
  "main": "await claimPresaleV2(umi, {\n  genesisAccount,\n  bucket: presaleBucket,\n  baseMint: baseMint.publicKey,\n  recipient: umi.identity.publicKey,\n}).sendAndConfirm(umi)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  claimPresaleV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, presaleBucket, and baseMint from previous steps.\n// [/SETUP]\n\n// [MAIN]\nawait claimPresaleV2(umi, {\n  genesisAccount,\n  bucket: presaleBucket,\n  baseMint: baseMint.publicKey,\n  recipient: umi.identity.publicKey,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "claim_presale_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
