/**
 * Example: read_agent_verify_plugin
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { fetchAsset, mplCore } from '@metaplex-foundation/mpl-core'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com').use(mplCore())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')",
  "main": "const assetData = await fetchAsset(umi, assetPublicKey)\nconst agentIdentity = assetData.agentIdentities?.[0]\n\nconsole.log(agentIdentity?.uri)\nconsole.log(agentIdentity?.lifecycleChecks?.transfer)\nconsole.log(agentIdentity?.lifecycleChecks?.update)\nconsole.log(agentIdentity?.lifecycleChecks?.execute)",
  "output": "// https://example.com/agent-registration.json\n// { __kind: 'Listen' }\n// { __kind: 'Listen' }\n// { __kind: 'Listen' }",
  "full": "// [IMPORTS]\nimport { fetchAsset, mplCore } from '@metaplex-foundation/mpl-core'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\nimport { publicKey } from '@metaplex-foundation/umi'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com').use(mplCore())\nconst assetPublicKey = publicKey('AGENT_CORE_ASSET_ADDRESS')\n// [/SETUP]\n\n// [MAIN]\nconst assetData = await fetchAsset(umi, assetPublicKey)\nconst agentIdentity = assetData.agentIdentities?.[0]\n\nconsole.log(agentIdentity?.uri)\nconsole.log(agentIdentity?.lifecycleChecks?.transfer)\nconsole.log(agentIdentity?.lifecycleChecks?.update)\nconsole.log(agentIdentity?.lifecycleChecks?.execute)\n// [/MAIN]\n\n// [OUTPUT]\n// https://example.com/agent-registration.json\n// { __kind: 'Listen' }\n// { __kind: 'Listen' }\n// { __kind: 'Listen' }\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "read_agent_verify_plugin",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
