/**
 * Example: delegate-collection-item-approve
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getDelegateCollectionItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');\nconst collectionItemDelegate = address('delegateAddress...');",
  "main": "const delegateIx = await getDelegateCollectionItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: collectionItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: updateAuthority,\n});",
  "output": "console.log('Collection Item delegate approved');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getDelegateCollectionItemV1InstructionAsync,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\nconst collectionItemDelegate = address('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst delegateIx = await getDelegateCollectionItemV1InstructionAsync({\n  mint,\n  authority: updateAuthority,\n  delegate: collectionItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n});\n\nawait sendAndConfirm({\n  instructions: [delegateIx],\n  payer: updateAuthority,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection Item delegate approved');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateCollectionItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst collectionItemDelegate = publicKey('delegateAddress...');",
  "main": "await delegateCollectionItemV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: collectionItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);",
  "output": "console.log('Collection Item delegate approved');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  delegateCollectionItemV1,\n  TokenStandard,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst updateAuthority = umi.identity;\nconst collectionItemDelegate = publicKey('delegateAddress...');\n// [/SETUP]\n\n// [MAIN]\nawait delegateCollectionItemV1(umi, {\n  mint,\n  authority: updateAuthority,\n  delegate: collectionItemDelegate,\n  tokenStandard: TokenStandard.NonFungible,\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Collection Item delegate approved');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-collection-item-approve",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
