/**
 * Example: delegate-data-update
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js and .rs files, then run: node scripts/build-examples.js
 */

const kitSections = {
  "imports": "import { address } from '@solana/addresses';\nimport {\n  getUpdateAsDataDelegateV2InstructionAsync,\n  fetchMetadata,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';",
  "setup": "const mint = address('mintAddress...');",
  "main": "const [metadataAddress] = await findMetadataPda({ mint });\nconst initialMetadata = await fetchMetadata(rpc, metadataAddress);\n\nconst updateIx = await getUpdateAsDataDelegateV2InstructionAsync({\n  mint,\n  authority: dataDelegate,\n  data: {\n    ...initialMetadata,\n    name: 'Updated Name',\n    creators: null, // Required when passing data\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: dataDelegate,\n});",
  "output": "console.log('Asset data updated via Data delegate');",
  "full": "// [IMPORTS]\nimport { address } from '@solana/addresses';\nimport {\n  getUpdateAsDataDelegateV2InstructionAsync,\n  fetchMetadata,\n  findMetadataPda,\n} from '@metaplex-foundation/mpl-token-metadata-kit';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = address('mintAddress...');\n// [/SETUP]\n\n// [MAIN]\nconst [metadataAddress] = await findMetadataPda({ mint });\nconst initialMetadata = await fetchMetadata(rpc, metadataAddress);\n\nconst updateIx = await getUpdateAsDataDelegateV2InstructionAsync({\n  mint,\n  authority: dataDelegate,\n  data: {\n    ...initialMetadata,\n    name: 'Updated Name',\n    creators: null, // Required when passing data\n  },\n});\n\nawait sendAndConfirm({\n  instructions: [updateIx],\n  payer: dataDelegate,\n});\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset data updated via Data delegate');\n// [/OUTPUT]\n"
}

const umiSections = {
  "imports": "import { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsDataDelegateV2,\n  fetchMetadataFromSeeds,\n} from '@metaplex-foundation/mpl-token-metadata';",
  "setup": "const mint = publicKey('mintAddress...');\nconst dataDelegate = umi.identity; // The delegate authority",
  "main": "const initialMetadata = await fetchMetadataFromSeeds(umi, { mint });\nawait updateAsDataDelegateV2(umi, {\n  mint,\n  authority: dataDelegate,\n  data: { ...initialMetadata, name: 'Updated Name' },\n}).sendAndConfirm(umi);",
  "output": "console.log('Asset data updated via Data delegate');",
  "full": "// [IMPORTS]\nimport { publicKey } from '@metaplex-foundation/umi';\nimport {\n  updateAsDataDelegateV2,\n  fetchMetadataFromSeeds,\n} from '@metaplex-foundation/mpl-token-metadata';\n// [/IMPORTS]\n\n// [SETUP]\nconst mint = publicKey('mintAddress...');\nconst dataDelegate = umi.identity; // The delegate authority\n// [/SETUP]\n\n// [MAIN]\nconst initialMetadata = await fetchMetadataFromSeeds(umi, { mint });\nawait updateAsDataDelegateV2(umi, {\n  mint,\n  authority: dataDelegate,\n  data: { ...initialMetadata, name: 'Updated Name' },\n}).sendAndConfirm(umi);\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Asset data updated via Data delegate');\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "delegate-data-update",
  description: "",
  tags: [],
}

export const examples = {
  kit: {
    framework: 'Kit',
    language: 'javascript',
    code: kitSections.full,
    sections: kitSections,
  },

  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
