/**
 * Example: deposit_launch_pool_v2
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  genesis,\n  depositLaunchPoolV2,\n  findLaunchPoolDepositV2Pda,\n  fetchLaunchPoolDepositV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity, sol } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, launchPoolBucket, and baseMint from previous steps.",
  "main": "await depositLaunchPoolV2(umi, {\n  genesisAccount,\n  bucket: launchPoolBucket,\n  baseMint: baseMint.publicKey,\n  amountQuoteToken: sol(10).basisPoints,\n}).sendAndConfirm(umi)\n\n// Verify\nconst [depositPda] = findLaunchPoolDepositV2Pda(umi, {\n  bucket: launchPoolBucket,\n  recipient: umi.identity.publicKey,\n})\nconst deposit = await fetchLaunchPoolDepositV2(umi, depositPda)",
  "output": "console.log('Deposited (after fee):', deposit.amountQuoteToken)",
  "full": "// [IMPORTS]\nimport {\n  genesis,\n  depositLaunchPoolV2,\n  findLaunchPoolDepositV2Pda,\n  fetchLaunchPoolDepositV2,\n} from '@metaplex-foundation/genesis'\nimport { mplToolbox } from '@metaplex-foundation/mpl-toolbox'\nimport { keypairIdentity, sol } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.mainnet-beta.solana.com')\n  .use(mplToolbox())\n  .use(genesis())\n\n// umi.use(keypairIdentity(yourKeypair));\n\n// Assumes genesisAccount, launchPoolBucket, and baseMint from previous steps.\n// [/SETUP]\n\n// [MAIN]\nawait depositLaunchPoolV2(umi, {\n  genesisAccount,\n  bucket: launchPoolBucket,\n  baseMint: baseMint.publicKey,\n  amountQuoteToken: sol(10).basisPoints,\n}).sendAndConfirm(umi)\n\n// Verify\nconst [depositPda] = findLaunchPoolDepositV2Pda(umi, {\n  bucket: launchPoolBucket,\n  recipient: umi.identity.publicKey,\n})\nconst deposit = await fetchLaunchPoolDepositV2(umi, depositPda)\n// [/MAIN]\n\n// [OUTPUT]\nconsole.log('Deposited (after fee):', deposit.amountQuoteToken)\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "deposit_launch_pool_v2",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

}
