/**
 * Example: claim_to_core_asset
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { findAssetSignerPda } from '@metaplex-foundation/mpl-core'\nimport {\n  distributeToAssetAndClaim,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst asset = publicKey(process.env.CORE_ASSET!)\nconst currentOwner = publicKey(process.env.CORE_ASSET_OWNER!)",
  "main": "const [assetSigner] = findAssetSignerPda(umi, { asset })\nconst allocations = [{ address: assetSigner, amount: 100_000n }]\nconst { proofs } = prepareDistribution(allocations)\n\nawait distributeToAssetAndClaim(umi, {\n  distribution,\n  mint,\n  asset,\n  recipient: currentOwner,\n  amount: allocations[0].amount,\n  proof: proofs[0],\n  nonce: 0,\n}).sendAndConfirm(umi)",
  "output": "// Tokens are claimed to the asset-signer PDA, then transferred to the current owner.",
  "full": "// [IMPORTS]\nimport { findAssetSignerPda } from '@metaplex-foundation/mpl-core'\nimport {\n  distributeToAssetAndClaim,\n  mplDistro,\n  prepareDistribution,\n} from '@metaplex-foundation/mpl-distro'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi(\n  process.env.RPC_URL ?? 'https://api.devnet.solana.com'\n).use(mplDistro())\n\nconst distribution = publicKey(process.env.DISTRIBUTION_ADDRESS!)\nconst mint = publicKey(process.env.TOKEN_MINT!)\nconst asset = publicKey(process.env.CORE_ASSET!)\nconst currentOwner = publicKey(process.env.CORE_ASSET_OWNER!)\n// [/SETUP]\n\n// [MAIN]\nconst [assetSigner] = findAssetSignerPda(umi, { asset })\nconst allocations = [{ address: assetSigner, amount: 100_000n }]\nconst { proofs } = prepareDistribution(allocations)\n\nawait distributeToAssetAndClaim(umi, {\n  distribution,\n  mint,\n  asset,\n  recipient: currentOwner,\n  amount: allocations[0].amount,\n  proof: proofs[0],\n  nonce: 0,\n}).sendAndConfirm(umi)\n// [/MAIN]\n\n// [OUTPUT]\n// Tokens are claimed to the asset-signer PDA, then transferred to the current owner.\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "claim_to_core_asset",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
