/**
 * Example: getAssetWithProof with inherited royalties
 *
 * Leaf metadata keeps the on-chain sentinel; DAS main royalty fields hold the collection-resolved display rate.
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { getAssetWithProof, mplBubblegum } from '@metaplex-foundation/mpl-bubblegum'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.devnet.solana.com').use(mplBubblegum())\n\nconst assetId = publicKey('YOUR_ASSET_ID')",
  "main": "const assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Leaf / hashing value (65535 when inherited)\nconsole.log(assetWithProof.metadata.sellerFeeBasisPoints)\n\n// Display / payout value from DAS main fields\nconsole.log(assetWithProof.rpcAsset.royalty?.basis_points)",
  "output": "// 65535\n// 500",
  "full": "// [IMPORTS]\nimport { getAssetWithProof, mplBubblegum } from '@metaplex-foundation/mpl-bubblegum'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.devnet.solana.com').use(mplBubblegum())\n\nconst assetId = publicKey('YOUR_ASSET_ID')\n// [/SETUP]\n\n// [MAIN]\nconst assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Leaf / hashing value (65535 when inherited)\nconsole.log(assetWithProof.metadata.sellerFeeBasisPoints)\n\n// Display / payout value from DAS main fields\nconsole.log(assetWithProof.rpcAsset.royalty?.basis_points)\n// [/MAIN]\n\n// [OUTPUT]\n// 65535\n// 500\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "getAssetWithProof with inherited royalties",
  description: "Leaf metadata keeps the on-chain sentinel; DAS main royalty fields hold the collection-resolved display rate.",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
