/**
 * Example: getAssetWithProof with inherited royalties
 *
 * Leaf metadata keeps the on-chain sentinel; DAS main royalty fields hold the collection-resolved display rate.
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { getAssetWithProof, mplBubblegum } from '@metaplex-foundation/mpl-bubblegum'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'",
  "setup": "const umi = createUmi('https://api.devnet.solana.com').use(mplBubblegum())\n\nconst assetId = publicKey('YOUR_ASSET_ID')",
  "main": "const assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Reading: metadata mirrors DAS main / resolved fields\nconsole.log(assetWithProof.metadata.sellerFeeBasisPoints) // e.g. 500 when inherited\nconsole.log(assetWithProof.metadata.creators) // collection payees when inherited\nconsole.log(assetWithProof.inherited) // true\n\n// Writes / hashing: currentMetadata is leaf-canonical (V2)\nconsole.log(assetWithProof.currentMetadata.sellerFeeBasisPoints) // 65535 when inherited\nconsole.log(assetWithProof.currentMetadata.creators) // usually []\n\n// Optional DAS-aligned _raw siblings (same leaf values)\nconsole.log(assetWithProof.sellerFeeBasisPointsRaw) // 65535 when inherited\nconsole.log(assetWithProof.creatorsRaw) // usually []\n\n// Explicit DAS raw + flag\nconsole.log(assetWithProof.rpcAsset.royalty?.basis_points_raw) // 65535\nconsole.log(assetWithProof.rpcAsset.creators_raw) // []\nconsole.log(assetWithProof.rpcAsset.royalty?.inherited) // true",
  "output": "// 500\n// [{ address: '...', share: 100, verified: true }]\n// true\n// 65535\n// []\n// 65535\n// []\n// 65535\n// []\n// true",
  "full": "// [IMPORTS]\nimport { getAssetWithProof, mplBubblegum } from '@metaplex-foundation/mpl-bubblegum'\nimport { publicKey } from '@metaplex-foundation/umi'\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\n// [/IMPORTS]\n\n// [SETUP]\nconst umi = createUmi('https://api.devnet.solana.com').use(mplBubblegum())\n\nconst assetId = publicKey('YOUR_ASSET_ID')\n// [/SETUP]\n\n// [MAIN]\nconst assetWithProof = await getAssetWithProof(umi, assetId, {\n  truncateCanopy: true,\n})\n\n// Reading: metadata mirrors DAS main / resolved fields\nconsole.log(assetWithProof.metadata.sellerFeeBasisPoints) // e.g. 500 when inherited\nconsole.log(assetWithProof.metadata.creators) // collection payees when inherited\nconsole.log(assetWithProof.inherited) // true\n\n// Writes / hashing: currentMetadata is leaf-canonical (V2)\nconsole.log(assetWithProof.currentMetadata.sellerFeeBasisPoints) // 65535 when inherited\nconsole.log(assetWithProof.currentMetadata.creators) // usually []\n\n// Optional DAS-aligned _raw siblings (same leaf values)\nconsole.log(assetWithProof.sellerFeeBasisPointsRaw) // 65535 when inherited\nconsole.log(assetWithProof.creatorsRaw) // usually []\n\n// Explicit DAS raw + flag\nconsole.log(assetWithProof.rpcAsset.royalty?.basis_points_raw) // 65535\nconsole.log(assetWithProof.rpcAsset.creators_raw) // []\nconsole.log(assetWithProof.rpcAsset.royalty?.inherited) // true\n// [/MAIN]\n\n// [OUTPUT]\n// 500\n// [{ address: '...', share: 100, verified: true }]\n// true\n// 65535\n// []\n// 65535\n// []\n// 65535\n// []\n// true\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "getAssetWithProof with inherited royalties",
  description: "Leaf metadata keeps the on-chain sentinel; DAS main royalty fields hold the collection-resolved display rate.",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
