/**
 * Example: fetch-asset
 *
 * 
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import { fetchAsset, fetchCollection, mplCore } from '@metaplex-foundation/mpl-core';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';",
  "setup": "// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())",
  "main": "// Fetch a Core Asset\r\nconst assetAddress = publicKey('AssetAddressHere...')\r\nconst asset = await fetchAsset(umi, assetAddress)\r\n\r\n// Fetch a Core Collection\r\nconst collectionAddress = publicKey('CollectionAddressHere...')\r\nconst collection = await fetchCollection(umi, collectionAddress)",
  "output": "console.log('Asset fetched:', asset)\r\nconsole.log('Name:', asset.name)\r\nconsole.log('Owner:', asset.owner)\r\nconsole.log('URI:', asset.uri)\r\n\r\nconsole.log('\\nCollection fetched:', collection)\r\nconsole.log('Name:', collection.name)\r\nconsole.log('URI:', collection.uri)",
  "full": "// [IMPORTS]\r\nimport { fetchAsset, fetchCollection, mplCore } from '@metaplex-foundation/mpl-core';\r\nimport { publicKey } from '@metaplex-foundation/umi';\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults';\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize UMI\r\nconst umi = createUmi('https://api.devnet.solana.com')\r\n  .use(mplCore())\r\n\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Fetch a Core Asset\r\nconst assetAddress = publicKey('AssetAddressHere...')\r\nconst asset = await fetchAsset(umi, assetAddress)\r\n\r\n// Fetch a Core Collection\r\nconst collectionAddress = publicKey('CollectionAddressHere...')\r\nconst collection = await fetchCollection(umi, collectionAddress)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Asset fetched:', asset)\r\nconsole.log('Name:', asset.name)\r\nconsole.log('Owner:', asset.owner)\r\nconsole.log('URI:', asset.uri)\r\n\r\nconsole.log('\\nCollection fetched:', collection)\r\nconsole.log('Name:', collection.name)\r\nconsole.log('URI:', collection.uri)\r\n// [/OUTPUT]\r\n"
}

const dasSections = {
  "imports": "// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { publicKey } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'",
  "setup": "// Initialize Umi with a DAS-enabled RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\n// The address of the NFT you want to fetch\r\nconst assetAddress = publicKey('YOUR_NFT_ADDRESS')",
  "main": "// Fetch the asset using DAS API\r\nconst asset = await umi.rpc.getAsset(assetAddress)",
  "output": "console.log('Asset ID:', asset.id)\r\nconsole.log('Name:', asset.content.metadata?.name)\r\nconsole.log('Description:', asset.content.metadata?.description)\r\nconsole.log('Image:', asset.content.links?.image)\r\nconsole.log('Owner:', asset.ownership.owner)\r\nconsole.log('Interface:', asset.interface)",
  "full": "// [IMPORTS]\r\n// npm install @metaplex-foundation/umi @metaplex-foundation/umi-bundle-defaults @metaplex-foundation/digital-asset-standard-api\r\nimport { publicKey } from '@metaplex-foundation/umi'\r\nimport { createUmi } from '@metaplex-foundation/umi-bundle-defaults'\r\nimport { dasApi } from '@metaplex-foundation/digital-asset-standard-api'\r\n// [/IMPORTS]\r\n\r\n// [SETUP]\r\n// Initialize Umi with a DAS-enabled RPC endpoint\r\nconst umi = createUmi('https://api.devnet.solana.com').use(dasApi())\r\n\r\n// The address of the NFT you want to fetch\r\nconst assetAddress = publicKey('YOUR_NFT_ADDRESS')\r\n// [/SETUP]\r\n\r\n// [MAIN]\r\n// Fetch the asset using DAS API\r\nconst asset = await umi.rpc.getAsset(assetAddress)\r\n// [/MAIN]\r\n\r\n// [OUTPUT]\r\nconsole.log('Asset ID:', asset.id)\r\nconsole.log('Name:', asset.content.metadata?.name)\r\nconsole.log('Description:', asset.content.metadata?.description)\r\nconsole.log('Image:', asset.content.links?.image)\r\nconsole.log('Owner:', asset.ownership.owner)\r\nconsole.log('Interface:', asset.interface)\r\n// [/OUTPUT]\r\n"
}

const cliSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Fetch an NFT using the Metaplex CLI\r\n\r\n# Fetch asset by ID\r\nmplx core fetch asset <assetId>\r\n\r\n# Download all files to a directory\r\nmplx core fetch asset <assetId> --download --output ./assets\r\n\r\n# Download only the image\r\nmplx core fetch asset <assetId> --download --image\r\n\r\n# Download only the metadata\r\nmplx core fetch asset <assetId> --download --metadata\r\n"
}

const curlSections = {
  "imports": "",
  "setup": "",
  "main": "",
  "output": "",
  "full": "# Fetch an NFT using the DAS API\r\ncurl -X POST \\\r\n  -H \"Content-Type: application/json\" \\\r\n  -d '{\r\n    \"jsonrpc\": \"2.0\",\r\n    \"id\": 1,\r\n    \"method\": \"getAsset\",\r\n    \"params\": {\r\n      \"id\": \"<NFT Mint Address>\"\r\n    }\r\n  }' \\\r\n  https://api.devnet.solana.com"
}

export const metadata = {
  title: "fetch-asset",
  description: "",
  tags: [],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'javascript',
    code: umiSections.full,
    sections: umiSections,
  },

  das: {
    framework: 'DAS',
    language: 'javascript',
    code: dasSections.full,
    sections: dasSections,
  },

  cli: {
    framework: 'CLI',
    language: 'bash',
    code: cliSections.full,
    sections: cliSections,
  },

  curl: {
    framework: 'cURL',
    language: 'bash',
    code: curlSections.full,
    sections: curlSections,
  },
}
