/**
 * Example: Custom Transaction Sender
 *
 * Use a custom transaction sender for full control over signing and sending.
 *
 * This file is auto-generated by scripts/build-examples.js
 * Edit the native .js/.ts and .rs files, then run: node scripts/build-examples.js
 */

const umiSections = {
  "imports": "import {\n  createAndRegisterLaunch,\n  SignAndSendOptions,\n} from '@metaplex-foundation/genesis'",
  "setup": "// Assumes umi and input from the Easy Mode example.",
  "main": "const options: SignAndSendOptions = {\n  txSender: async (transactions) => {\n    // Replace myCustomSign / myCustomSend with your own\n    // signing and sending implementation.\n    const signatures: Uint8Array[] = []\n    for (const tx of transactions) {\n      const signed = await myCustomSign(tx)   // your signer\n      const sig = await myCustomSend(signed)   // your sender\n      signatures.push(sig)\n    }\n    return signatures\n  },\n}\n\nconst result = await createAndRegisterLaunch(umi, {}, input, options)\nconsole.log(`Launch live at: ${result.launch.link}`)",
  "output": "",
  "full": "// [IMPORTS]\nimport {\n  createAndRegisterLaunch,\n  SignAndSendOptions,\n} from '@metaplex-foundation/genesis'\n// [/IMPORTS]\n\n// [SETUP]\n// Assumes umi and input from the Easy Mode example.\n// [/SETUP]\n\n// [MAIN]\nconst options: SignAndSendOptions = {\n  txSender: async (transactions) => {\n    // Replace myCustomSign / myCustomSend with your own\n    // signing and sending implementation.\n    const signatures: Uint8Array[] = []\n    for (const tx of transactions) {\n      const signed = await myCustomSign(tx)   // your signer\n      const sig = await myCustomSend(signed)   // your sender\n      signatures.push(sig)\n    }\n    return signatures\n  },\n}\n\nconst result = await createAndRegisterLaunch(umi, {}, input, options)\nconsole.log(`Launch live at: ${result.launch.link}`)\n// [/MAIN]\n\n// [OUTPUT]\n// [/OUTPUT]\n"
}

export const metadata = {
  title: "Custom Transaction Sender",
  description: "Use a custom transaction sender for full control over signing and sending.",
  tags: ['genesis', 'api-client', 'custom-sender', 'intermediate'],
}

export const examples = {
  umi: {
    framework: 'Umi',
    language: 'typescript',
    code: umiSections.full,
    sections: umiSections,
  },

}
